import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { NextRequest, NextResponse } from "next/server";

/**
 * Tests for POST /api/simulator (G15-002).
 *
 * Mirrors the rate-limit / CSRF / auth / Zod / forwarding gauntlet pinned
 * for the `send-intro` and `bridge/outcome` routes. The forwarding cases
 * (TC7 / TC8) pin the AnalyticsUpstreamError contract: 4xx upstream must
 * stay 4xx, 5xx upstream must stay 5xx — not flattened to 500.
 *
 * TC4 (G15-046) asserts the desired behavior for ratelimit_misconfigured:
 * the route SHOULD convert the fail-CLOSED reason into a 503 so canary
 * alarms fire instead of looking like ordinary 429 throttling. The route
 * does not currently call isRateLimitMisconfigured(rl); we mark the test
 * as it.fails so the regression is visible and unblocks merge until the
 * fix lands in a follow-up PR.
 */

// route.ts (indirectly via analytics-client) and csrf import server-only.
vi.mock("server-only", () => ({}));

const STATE = vi.hoisted(() => ({
  authUser: {
    id: "00000000-0000-0000-0000-000000000001",
    email: "alloc@test.sec",
  } as { id: string; email: string } | null,
  // Discriminated CheckLimitResult shape; misconfigured is the
  // ratelimit_misconfigured fail-CLOSED variant.
  checkLimitResult: { success: true } as
    | { success: true }
    | { success: false; retryAfter: number; reason?: "ratelimit_misconfigured" },
  csrfShouldReject: false,
  portfolioFound: true,
  simulateImpl: (async () => ({
    status: "ok",
    candidate_id: "cand-1",
    candidate_name: "Test",
    portfolio_id: "00000000-0000-0000-0000-000000000010",
  })) as (
    portfolioId: string,
    candidateStrategyId: string,
    userId: string,
  ) => Promise<unknown>,
}));

vi.mock("@/lib/supabase/server", () => ({
  createClient: async () => ({
    auth: {
      getUser: async () => ({
        data: { user: STATE.authUser },
        error: null,
      }),
    },
    from: (table: string) => {
      if (table === "portfolios") {
        return {
          select: () => ({
            eq: () => ({
              eq: () => ({
                single: async () =>
                  STATE.portfolioFound
                    ? {
                        data: { id: "00000000-0000-0000-0000-000000000010" },
                        error: null,
                      }
                    : { data: null, error: { message: "not found" } },
              }),
            }),
          }),
        };
      }
      throw new Error(`unexpected from(${table})`);
    },
  }),
}));

vi.mock("@/lib/csrf", () => ({
  assertSameOrigin: () =>
    STATE.csrfShouldReject
      ? NextResponse.json({ error: "Origin not allowed" }, { status: 403 })
      : null,
}));

vi.mock("@/lib/ratelimit", () => ({
  simulatorLimiter: {},
  checkLimit: async () => STATE.checkLimitResult,
  isRateLimitMisconfigured: (
    rl: { success: boolean; reason?: string },
  ): boolean =>
    rl.success === false && rl.reason === "ratelimit_misconfigured",
}));

// Mock analytics-client so we control the upstream response. We re-export
// the real AnalyticsUpstreamError class so `err instanceof AnalyticsUpstreamError`
// inside the route resolves against the same constructor identity.
vi.mock("@/lib/analytics-client", async () => {
  class AnalyticsUpstreamError extends Error {
    readonly status: number;
    constructor(message: string, status: number) {
      super(message);
      this.name = "AnalyticsUpstreamError";
      this.status = status;
    }
  }
  class AnalyticsTimeoutError extends Error {
    constructor(path: string, timeoutMs: number) {
      super(`Analytics request to ${path} timed out after ${timeoutMs}ms`);
      this.name = "AnalyticsTimeoutError";
    }
  }
  return {
    AnalyticsUpstreamError,
    AnalyticsTimeoutError,
    simulateAddCandidate: (
      portfolioId: string,
      candidateStrategyId: string,
      userId: string,
    ) => STATE.simulateImpl(portfolioId, candidateStrategyId, userId),
  };
});

// Sentry capture is fire-and-forget; spy so the 5xx tests can pin that the
// detail still reaches Sentry now that err.message is no longer echoed.
const captureSpy = vi.hoisted(() => vi.fn());
vi.mock("@/lib/sentry-capture", () => ({
  captureToSentry: captureSpy,
}));

// PR-3+4 H-1143 (audit-2026-05-07): SimulatorRequestSchema tightened
// portfolio_id from `.min(1)` to `.uuid()`. The pre-fix fixture
// "00000000-0000-0000-0000-000000000010" is NOT a valid v4 UUID per
// RFC 4122 (zod v4 enforces the version+variant nibbles), but every
// real prod portfolio_id is generated by gen_random_uuid() and IS
// compliant. Switch to a proper v4 UUID so the fixture matches what
// prod actually emits.
const PORTFOLIO_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const CANDIDATE_ID = "11111111-1111-4111-8111-111111111111";

function makeRequest(body: unknown, opts?: { rawBody?: string }): NextRequest {
  return new NextRequest("http://localhost:3000/api/simulator", {
    method: "POST",
    headers: {
      origin: "http://localhost:3000",
      "content-type": "application/json",
    },
    body: opts?.rawBody ?? JSON.stringify(body),
  });
}

beforeEach(() => {
  STATE.authUser = {
    id: "00000000-0000-0000-0000-000000000001",
    email: "alloc@test.sec",
  };
  STATE.checkLimitResult = { success: true };
  STATE.csrfShouldReject = false;
  STATE.portfolioFound = true;
  STATE.simulateImpl = async () => ({
    status: "ok",
    candidate_id: "cand-1",
    candidate_name: "Test",
    portfolio_id: PORTFOLIO_ID,
  });
  captureSpy.mockClear();
});

afterEach(() => {
  vi.clearAllMocks();
});

describe("POST /api/simulator", () => {
  it("TC1 — 401 when no user", async () => {
    STATE.authUser = null;
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(401);
    const body = await res.json();
    expect(body.error).toBe("Unauthorized");
  });

  it("M-0957 — success AND 401 carry Cache-Control: private, no-store", async () => {
    const { POST } = await import("./route");
    // 200 success — user-specific portfolio metrics must never be shared-cached.
    const ok = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(ok.status).toBe(200);
    expect(ok.headers.get("Cache-Control")).toBe("private, no-store");

    // 401 — the hand-rolled auth path stamps NO_STORE_HEADERS too.
    STATE.authUser = null;
    const unauth = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(unauth.status).toBe(401);
    expect(unauth.headers.get("Cache-Control")).toBe("private, no-store");
  });

  it("M-0957 — error paths (404, upstream-4xx-forward, 504, 500) all carry no-store", async () => {
    // F5b review #3: pin the leak-bearing error branches, not just 200+401.
    const { POST } = await import("./route");
    const req = () =>
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      });

    STATE.portfolioFound = false; // 404 portfolio-not-found
    let res = await POST(req());
    expect(res.status).toBe(404);
    expect(res.headers.get("Cache-Control")).toBe("private, no-store");
    STATE.portfolioFound = true;

    STATE.simulateImpl = async () => {
      const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
      throw new AnalyticsUpstreamError("already in portfolio", 400); // 4xx fwd
    };
    res = await POST(req());
    expect(res.status).toBe(400);
    expect(res.headers.get("Cache-Control")).toBe("private, no-store");

    STATE.simulateImpl = async () => {
      const { AnalyticsTimeoutError } = await import("@/lib/analytics-client");
      throw new AnalyticsTimeoutError("/api/portfolio-simulate", 15000); // 504
    };
    res = await POST(req());
    expect(res.status).toBe(504);
    expect(res.headers.get("Cache-Control")).toBe("private, no-store");

    STATE.simulateImpl = async () => {
      const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
      throw new AnalyticsUpstreamError("traceback", 502); // 500 generic
    };
    res = await POST(req());
    expect(res.status).toBe(500);
    expect(res.headers.get("Cache-Control")).toBe("private, no-store");
  });

  it("F5b — pending-approval user is denied 403 (gate parity with bridge / portfolio-optimizer)", async () => {
    // The compute-heavy simulateAddCandidate round-trip must be gated like its
    // siblings. assertProfileApproved is globally mocked to null (approved) in
    // test-setup; override it once to return a denial NextResponse.
    const { assertProfileApproved } = await import("@/lib/api/approval-gate");
    vi.mocked(assertProfileApproved).mockResolvedValueOnce(
      NextResponse.json(
        { error: "Account pending approval" },
        { status: 403, headers: { "Cache-Control": "private, no-store" } },
      ),
    );
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(403);
    expect(res.headers.get("Cache-Control")).toBe("private, no-store");
  });

  it("TC2 — 403 CSRF when origin allowlist fails", async () => {
    STATE.csrfShouldReject = true;
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(403);
    const body = await res.json();
    expect(body.error).toBe("Origin not allowed");
  });

  it("TC3 — 429 when checkLimit() denies (real throttle)", async () => {
    STATE.checkLimitResult = { success: false, retryAfter: 42 };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(429);
    expect(res.headers.get("Retry-After")).toBe("42");
    const body = await res.json();
    expect(body.error).toMatch(/Too many simulations/i);
    expect(body.retryAfter).toBe(42);
  });

  // TC4: G15-046 — ratelimit_misconfigured surfaces as 503 (fail-CLOSED on
  // limiter outage) so canary alarms catch the configuration outage rather
  // than treating users as throttled. Closed by the route narrowing on
  // isRateLimitMisconfigured(rl) before the 429 branch.
  it("TC4 — 503 when checkLimit() returns ratelimit_misconfigured (G15-046)", async () => {
    STATE.checkLimitResult = {
      success: false,
      retryAfter: 60,
      reason: "ratelimit_misconfigured",
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(503);
  });

  it("TC5 — 400 on Zod parse failure", async () => {
    const { POST } = await import("./route");
    // candidate_strategy_id missing — fails SimulatorRequestSchema.
    const res = await POST(
      makeRequest({ portfolio_id: PORTFOLIO_ID }),
    );
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toMatch(/required/i);
  });

  it("TC5b — 400 on invalid JSON body", async () => {
    const { POST } = await import("./route");
    const res = await POST(makeRequest(null, { rawBody: "{not json" }));
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toBe("Invalid JSON");
  });

  it("TC6 — happy path forwards body shape from analytics-client", async () => {
    let capturedArgs: { portfolio: string; candidate: string; user: string } | null =
      null;
    STATE.simulateImpl = async (portfolioId, candidateStrategyId, userId) => {
      capturedArgs = {
        portfolio: portfolioId,
        candidate: candidateStrategyId,
        user: userId,
      };
      return {
        status: "ok",
        candidate_id: candidateStrategyId,
        candidate_name: "Test",
        portfolio_id: portfolioId,
      };
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toMatchObject({
      status: "ok",
      candidate_id: CANDIDATE_ID,
      portfolio_id: PORTFOLIO_ID,
    });
    expect(capturedArgs).toEqual({
      portfolio: PORTFOLIO_ID,
      candidate: CANDIDATE_ID,
      user: "00000000-0000-0000-0000-000000000001",
    });
  });

  it("TC7 — 4xx AnalyticsUpstreamError forwarded as 4xx (NOT collapsed to 500)", async () => {
    const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
    STATE.simulateImpl = async () => {
      throw new AnalyticsUpstreamError("Already in portfolio", 400);
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toBe("Already in portfolio");
  });

  it("TC7b — 404 AnalyticsUpstreamError forwarded as 404", async () => {
    const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
    STATE.simulateImpl = async () => {
      throw new AnalyticsUpstreamError("Portfolio not found", 404);
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(404);
    const body = await res.json();
    expect(body.error).toBe("Portfolio not found");
  });

  it("TC8 — 5xx AnalyticsUpstreamError → 500 with STATIC message (M-0959/M-0963: no leak)", async () => {
    // Route only special-cases 4xx upstream; 5xx falls through to the generic
    // 500 path, which now returns a STATIC message (the byte-identical defect
    // F5 closed in /api/bridge — err.message echoed the upstream 5xx detail).
    const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
    STATE.simulateImpl = async () => {
      throw new AnalyticsUpstreamError("upstream traceback frame 42", 502);
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body.error).toBe("Portfolio impact simulation failed.");
    expect(body.error).not.toContain("traceback");
    expect(captureSpy).toHaveBeenCalledWith(
      expect.any(Error),
      expect.objectContaining({
        tags: { route: "api/simulator", op: "simulateAddCandidate" },
      }),
    );
  });

  it("TC9 — generic Error (e.g. contract drift) → 500 STATIC, no leak (L-0055)", async () => {
    // parseResponse() throws a plain Error whose message embeds Python schema
    // field names on contract drift; that must NOT reach the allocator.
    STATE.simulateImpl = async () => {
      throw new Error(
        "Analytics response contract violation on /api/simulator: deltas.sharpe_delta: Expected number, received null",
      );
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body.error).toBe("Portfolio impact simulation failed.");
    expect(body.error).not.toContain("sharpe_delta");
    expect(body.error).not.toContain("contract violation");
  });

  it("TC9b — AnalyticsTimeoutError → 504 (M-0959)", async () => {
    STATE.simulateImpl = async () => {
      const { AnalyticsTimeoutError } = await import("@/lib/analytics-client");
      throw new AnalyticsTimeoutError("/api/simulator", 15000);
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(504);
    const body = await res.json();
    expect(body.error).toMatch(/taking longer/i);
  });

  it("TC10 — 404 when portfolio ownership check fails", async () => {
    STATE.portfolioFound = false;
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(404);
    const body = await res.json();
    expect(body.error).toBe("Portfolio not found");
  });
});
