import { describe, it, expect, vi, beforeEach, afterEach } from "vitest";
import { NextRequest, NextResponse } from "next/server";

/**
 * Tests for POST /api/simulator (G15-002).
 *
 * Mirrors the rate-limit / CSRF / auth / Zod / forwarding gauntlet pinned
 * for the `send-intro` and `bridge/outcome` routes. The forwarding cases
 * (TC7 / TC8) pin the AnalyticsUpstreamError contract: 4xx upstream must
 * stay 4xx, 5xx upstream must stay 5xx — not flattened to 500.
 *
 * TC4 (G15-046) asserts the desired behavior for ratelimit_misconfigured:
 * the route SHOULD convert the fail-CLOSED reason into a 503 so canary
 * alarms fire instead of looking like ordinary 429 throttling. The route
 * does not currently call isRateLimitMisconfigured(rl); we mark the test
 * as it.fails so the regression is visible and unblocks merge until the
 * fix lands in a follow-up PR.
 */

// route.ts (indirectly via analytics-client) and csrf import server-only.
vi.mock("server-only", () => ({}));

const STATE = vi.hoisted(() => ({
  authUser: {
    id: "00000000-0000-0000-0000-000000000001",
    email: "alloc@test.sec",
  } as { id: string; email: string } | null,
  // Discriminated CheckLimitResult shape; misconfigured is the
  // ratelimit_misconfigured fail-CLOSED variant.
  checkLimitResult: { success: true } as
    | { success: true }
    | { success: false; retryAfter: number; reason?: "ratelimit_misconfigured" },
  csrfShouldReject: false,
  portfolioFound: true,
  simulateImpl: (async () => ({
    status: "ok",
    candidate_id: "cand-1",
    candidate_name: "Test",
    portfolio_id: "00000000-0000-0000-0000-000000000010",
  })) as (
    portfolioId: string,
    candidateStrategyId: string,
    userId: string,
  ) => Promise<unknown>,
}));

vi.mock("@/lib/supabase/server", () => ({
  createClient: async () => ({
    auth: {
      getUser: async () => ({
        data: { user: STATE.authUser },
        error: null,
      }),
    },
    from: (table: string) => {
      if (table === "portfolios") {
        return {
          select: () => ({
            eq: () => ({
              eq: () => ({
                single: async () =>
                  STATE.portfolioFound
                    ? {
                        data: { id: "00000000-0000-0000-0000-000000000010" },
                        error: null,
                      }
                    : { data: null, error: { message: "not found" } },
              }),
            }),
          }),
        };
      }
      throw new Error(`unexpected from(${table})`);
    },
  }),
}));

vi.mock("@/lib/csrf", () => ({
  assertSameOrigin: () =>
    STATE.csrfShouldReject
      ? NextResponse.json({ error: "Origin not allowed" }, { status: 403 })
      : null,
}));

vi.mock("@/lib/ratelimit", () => ({
  simulatorLimiter: {},
  checkLimit: async () => STATE.checkLimitResult,
  isRateLimitMisconfigured: (
    rl: { success: boolean; reason?: string },
  ): boolean =>
    rl.success === false && rl.reason === "ratelimit_misconfigured",
}));

// Mock analytics-client so we control the upstream response. We re-export
// the real AnalyticsUpstreamError class so `err instanceof AnalyticsUpstreamError`
// inside the route resolves against the same constructor identity.
vi.mock("@/lib/analytics-client", async () => {
  class AnalyticsUpstreamError extends Error {
    readonly status: number;
    constructor(message: string, status: number) {
      super(message);
      this.name = "AnalyticsUpstreamError";
      this.status = status;
    }
  }
  return {
    AnalyticsUpstreamError,
    simulateAddCandidate: (
      portfolioId: string,
      candidateStrategyId: string,
      userId: string,
    ) => STATE.simulateImpl(portfolioId, candidateStrategyId, userId),
  };
});

// PR-3+4 H-1143 (audit-2026-05-07): SimulatorRequestSchema tightened
// portfolio_id from `.min(1)` to `.uuid()`. The pre-fix fixture
// "00000000-0000-0000-0000-000000000010" is NOT a valid v4 UUID per
// RFC 4122 (zod v4 enforces the version+variant nibbles), but every
// real prod portfolio_id is generated by gen_random_uuid() and IS
// compliant. Switch to a proper v4 UUID so the fixture matches what
// prod actually emits.
const PORTFOLIO_ID = "aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa";
const CANDIDATE_ID = "11111111-1111-4111-8111-111111111111";

function makeRequest(body: unknown, opts?: { rawBody?: string }): NextRequest {
  return new NextRequest("http://localhost:3000/api/simulator", {
    method: "POST",
    headers: {
      origin: "http://localhost:3000",
      "content-type": "application/json",
    },
    body: opts?.rawBody ?? JSON.stringify(body),
  });
}

beforeEach(() => {
  STATE.authUser = {
    id: "00000000-0000-0000-0000-000000000001",
    email: "alloc@test.sec",
  };
  STATE.checkLimitResult = { success: true };
  STATE.csrfShouldReject = false;
  STATE.portfolioFound = true;
  STATE.simulateImpl = async () => ({
    status: "ok",
    candidate_id: "cand-1",
    candidate_name: "Test",
    portfolio_id: PORTFOLIO_ID,
  });
});

afterEach(() => {
  vi.clearAllMocks();
});

describe("POST /api/simulator", () => {
  it("TC1 — 401 when no user", async () => {
    STATE.authUser = null;
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(401);
    const body = await res.json();
    expect(body.error).toBe("Unauthorized");
  });

  it("TC2 — 403 CSRF when origin allowlist fails", async () => {
    STATE.csrfShouldReject = true;
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(403);
    const body = await res.json();
    expect(body.error).toBe("Origin not allowed");
  });

  it("TC3 — 429 when checkLimit() denies (real throttle)", async () => {
    STATE.checkLimitResult = { success: false, retryAfter: 42 };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(429);
    expect(res.headers.get("Retry-After")).toBe("42");
    const body = await res.json();
    expect(body.error).toMatch(/Too many simulations/i);
    expect(body.retryAfter).toBe(42);
  });

  // TC4: G15-046 — ratelimit_misconfigured surfaces as 503 (fail-CLOSED on
  // limiter outage) so canary alarms catch the configuration outage rather
  // than treating users as throttled. Closed by the route narrowing on
  // isRateLimitMisconfigured(rl) before the 429 branch.
  it("TC4 — 503 when checkLimit() returns ratelimit_misconfigured (G15-046)", async () => {
    STATE.checkLimitResult = {
      success: false,
      retryAfter: 60,
      reason: "ratelimit_misconfigured",
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(503);
  });

  it("TC5 — 400 on Zod parse failure", async () => {
    const { POST } = await import("./route");
    // candidate_strategy_id missing — fails SimulatorRequestSchema.
    const res = await POST(
      makeRequest({ portfolio_id: PORTFOLIO_ID }),
    );
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toMatch(/required/i);
  });

  it("TC5b — 400 on invalid JSON body", async () => {
    const { POST } = await import("./route");
    const res = await POST(makeRequest(null, { rawBody: "{not json" }));
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toBe("Invalid JSON");
  });

  it("TC6 — happy path forwards body shape from analytics-client", async () => {
    let capturedArgs: { portfolio: string; candidate: string; user: string } | null =
      null;
    STATE.simulateImpl = async (portfolioId, candidateStrategyId, userId) => {
      capturedArgs = {
        portfolio: portfolioId,
        candidate: candidateStrategyId,
        user: userId,
      };
      return {
        status: "ok",
        candidate_id: candidateStrategyId,
        candidate_name: "Test",
        portfolio_id: portfolioId,
      };
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(200);
    const body = await res.json();
    expect(body).toMatchObject({
      status: "ok",
      candidate_id: CANDIDATE_ID,
      portfolio_id: PORTFOLIO_ID,
    });
    expect(capturedArgs).toEqual({
      portfolio: PORTFOLIO_ID,
      candidate: CANDIDATE_ID,
      user: "00000000-0000-0000-0000-000000000001",
    });
  });

  it("TC7 — 4xx AnalyticsUpstreamError forwarded as 4xx (NOT collapsed to 500)", async () => {
    const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
    STATE.simulateImpl = async () => {
      throw new AnalyticsUpstreamError("Already in portfolio", 400);
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(400);
    const body = await res.json();
    expect(body.error).toBe("Already in portfolio");
  });

  it("TC7b — 404 AnalyticsUpstreamError forwarded as 404", async () => {
    const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
    STATE.simulateImpl = async () => {
      throw new AnalyticsUpstreamError("Portfolio not found", 404);
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(404);
    const body = await res.json();
    expect(body.error).toBe("Portfolio not found");
  });

  it("TC8 — 5xx AnalyticsUpstreamError NOT specially forwarded → 500", async () => {
    // Route only special-cases 4xx upstream; 5xx falls through to the generic
    // 500 "message" path. This pins the existing contract; if we ever choose
    // to forward 5xx verbatim, this test will fail loudly.
    const { AnalyticsUpstreamError } = await import("@/lib/analytics-client");
    STATE.simulateImpl = async () => {
      throw new AnalyticsUpstreamError("upstream blew up", 502);
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body.error).toBe("upstream blew up");
  });

  it("TC9 — analytics-client throws unreachable → 500 with message", async () => {
    // The route catches generic Errors and emits 500 with err.message.
    // This covers the "ANALYTICS_SERVICE_URL not configured / not reachable"
    // path (the wrapper throws "Analytics service is not reachable.").
    STATE.simulateImpl = async () => {
      throw new Error("Analytics service is not reachable. Please ensure it is running.");
    };
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(500);
    const body = await res.json();
    expect(body.error).toMatch(/not reachable/i);
  });

  it("TC10 — 404 when portfolio ownership check fails", async () => {
    STATE.portfolioFound = false;
    const { POST } = await import("./route");
    const res = await POST(
      makeRequest({
        portfolio_id: PORTFOLIO_ID,
        candidate_strategy_id: CANDIDATE_ID,
      }),
    );
    expect(res.status).toBe(404);
    const body = await res.json();
    expect(body.error).toBe("Portfolio not found");
  });
});
