import type { WidgetMeta } from "./types";

// ---------------------------------------------------------------------------
// Widget Registry — all 39 widgets for the My Allocation dashboard
// ---------------------------------------------------------------------------

export const WIDGET_REGISTRY: Record<string, WidgetMeta> = {
  // ── Performance (10) ────────────────────────────────────────────────
  "equity-curve": {
    id: "equity-curve",
    name: "Equity Curve",
    category: "performance",
    icon: "▲",
    defaultW: 12,
    defaultH: 4,
    description: "Cumulative portfolio growth over time with composite + per-strategy lines.",
    status: "ready",
  },
  "drawdown-chart": {
    id: "drawdown-chart",
    name: "Drawdown Chart",
    category: "performance",
    icon: "▲",
    defaultW: 12,
    defaultH: 4,
    description: "Underwater chart showing peak-to-trough drawdowns over time.",
    status: "ready",
  },
  "monthly-returns": {
    id: "monthly-returns",
    name: "Monthly Returns",
    category: "performance",
    icon: "▲",
    defaultW: 4,
    defaultH: 3,
    description: "Calendar heatmap of monthly returns with color-coded cells.",
    status: "ready",
  },
  "annual-returns": {
    id: "annual-returns",
    name: "Annual Returns",
    category: "performance",
    icon: "▲",
    defaultW: 4,
    defaultH: 3,
    description: "Bar chart of annual returns by year.",
    status: "ready",
  },
  "cumulative-vs-benchmark": {
    id: "cumulative-vs-benchmark",
    name: "Cumulative vs Benchmark",
    category: "performance",
    icon: "▲",
    defaultW: 6,
    defaultH: 4,
    description: "Portfolio cumulative return overlaid with benchmark (BTC, ETH, S&P).",
    status: "ready",
  },
  "rolling-sharpe": {
    id: "rolling-sharpe",
    name: "Rolling Sharpe",
    category: "performance",
    icon: "▲",
    defaultW: 6,
    defaultH: 3,
    description: "Rolling 30/60/90-day Sharpe ratio over time.",
    status: "ready",
  },
  "rolling-volatility": {
    id: "rolling-volatility",
    name: "Rolling Volatility",
    category: "performance",
    icon: "▲",
    defaultW: 6,
    defaultH: 3,
    description: "Rolling annualized volatility window chart.",
    status: "ready",
  },
  "return-distribution": {
    id: "return-distribution",
    name: "Return Distribution",
    category: "performance",
    icon: "▲",
    defaultW: 4,
    defaultH: 3,
    description: "Histogram of daily returns with normal distribution overlay.",
    status: "ready",
  },
  "best-worst-periods": {
    id: "best-worst-periods",
    name: "Best / Worst Periods",
    category: "performance",
    icon: "▲",
    defaultW: 4,
    defaultH: 3,
    description: "Top 5 best and worst daily/weekly/monthly returns.",
    status: "ready",
  },
  "win-rate-profit-factor": {
    id: "win-rate-profit-factor",
    name: "Win Rate & Profit Factor",
    category: "performance",
    icon: "▲",
    defaultW: 4,
    defaultH: 3,
    description: "Win/loss ratio and profit factor per strategy.",
    status: "ready",
  },

  // ── Risk (6) ────────────────────────────────────────────────────────
  "correlation-matrix": {
    id: "correlation-matrix",
    name: "Correlation Matrix",
    category: "risk",
    icon: "◆",
    defaultW: 4,
    defaultH: 3,
    description: "Pairwise correlation heatmap between strategies.",
    status: "ready",
  },
  "correlation-over-time": {
    id: "correlation-over-time",
    name: "Correlation Over Time",
    category: "risk",
    icon: "◆",
    defaultW: 6,
    defaultH: 3,
    description: "Rolling pairwise correlation trends to spot regime changes.",
    status: "ready",
  },
  "var-expected-shortfall": {
    id: "var-expected-shortfall",
    name: "VaR & Expected Shortfall",
    category: "risk",
    icon: "◆",
    defaultW: 4,
    defaultH: 3,
    description: "Value at Risk (95%/99%) and Conditional VaR (Expected Shortfall).",
    status: "ready",
  },
  "risk-decomposition": {
    id: "risk-decomposition",
    name: "Risk Decomposition",
    category: "risk",
    icon: "◆",
    defaultW: 6,
    defaultH: 3,
    description: "Contribution of each strategy to total portfolio risk.",
    status: "ready",
  },
  "tail-risk": {
    id: "tail-risk",
    name: "Tail Risk",
    category: "risk",
    icon: "◆",
    defaultW: 4,
    defaultH: 3,
    description: "Skewness, kurtosis, and tail ratio metrics.",
    status: "ready",
  },
  "tracking-error": {
    id: "tracking-error",
    name: "Tracking Error",
    category: "risk",
    icon: "◆",
    defaultW: 4,
    defaultH: 3,
    description: "Standard deviation of active returns vs benchmark.",
    status: "ready",
  },

  // ── Allocation (5) ─────────────────────────────────────────────────
  "allocation-donut": {
    id: "allocation-donut",
    name: "Allocation Donut",
    category: "allocation",
    icon: "◉",
    defaultW: 4,
    defaultH: 3,
    description: "AUM split across strategies as a donut chart.",
    status: "ready",
  },
  "allocation-over-time": {
    id: "allocation-over-time",
    name: "Allocation Over Time",
    category: "allocation",
    icon: "◉",
    defaultW: 6,
    defaultH: 3,
    description: "Stacked area chart showing how weights evolved over time.",
    status: "ready",
  },
  "weight-drift-monitor": {
    id: "weight-drift-monitor",
    name: "Weight Drift Monitor",
    category: "allocation",
    icon: "◉",
    defaultW: 6,
    defaultH: 3,
    description: "Shows how actual weights have drifted from target allocations.",
    status: "ready",
  },
  "rebalance-suggestions": {
    id: "rebalance-suggestions",
    name: "Rebalance Suggestions",
    category: "allocation",
    icon: "◉",
    defaultW: 6,
    defaultH: 3,
    description: "Actionable rebalancing trades to return to target weights.",
    status: "ready",
  },
  "strategy-comparison": {
    id: "strategy-comparison",
    name: "Strategy Comparison",
    category: "allocation",
    icon: "◉",
    defaultW: 6,
    defaultH: 3,
    description: "Side-by-side metrics table for all strategies.",
    status: "ready",
  },

  // ── Attribution (3) ────────────────────────────────────────────────
  "attribution-waterfall": {
    id: "attribution-waterfall",
    name: "Attribution Waterfall",
    category: "attribution",
    icon: "▸",
    defaultW: 6,
    defaultH: 4,
    description: "Waterfall chart breaking total return into per-strategy contributions.",
    status: "ready",
  },
  "performance-by-period": {
    id: "performance-by-period",
    name: "Performance by Period",
    category: "attribution",
    icon: "▸",
    defaultW: 6,
    defaultH: 3,
    description: "Returns bucketed by day-of-week, month, or custom period.",
    status: "ready",
  },
  "alpha-beta-decomposition": {
    id: "alpha-beta-decomposition",
    name: "Alpha/Beta Decomposition",
    category: "attribution",
    icon: "▸",
    defaultW: 6,
    defaultH: 3,
    description: "Decompose returns into alpha (skill) and beta (market) components.",
    status: "ready",
  },

  // ── Positions (5) ──────────────────────────────────────────────────
  "positions-table": {
    id: "positions-table",
    name: "Positions Table",
    category: "positions",
    icon: "▦",
    // Full-width default: the Positions Table is a wide data table and
    // looks broken when it sits alone in a half-width row with empty
    // whitespace to its right. Design review FINDING-009.
    defaultW: 12,
    defaultH: 4,
    description: "Live positions with entry price, PnL, and weight.",
    status: "ready",
  },
  "trading-activity-log": {
    id: "trading-activity-log",
    name: "Trading Activity Log",
    category: "positions",
    icon: "▦",
    defaultW: 6,
    defaultH: 4,
    description: "Chronological trade log with filters.",
    status: "ready",
  },
  "trade-volume": {
    id: "trade-volume",
    name: "Trade Volume",
    category: "positions",
    icon: "▦",
    defaultW: 4,
    defaultH: 3,
    description: "Daily/weekly trade volume bars.",
    status: "ready",
  },
  "exposure-by-asset": {
    id: "exposure-by-asset",
    name: "Exposure by Asset",
    category: "positions",
    icon: "▦",
    defaultW: 4,
    defaultH: 3,
    description: "Net exposure breakdown by underlying asset.",
    status: "ready",
  },
  "net-exposure": {
    id: "net-exposure",
    name: "Net Exposure",
    category: "positions",
    icon: "▦",
    defaultW: 4,
    defaultH: 3,
    description: "Long vs short exposure over time.",
    status: "ready",
  },

  // ── Monitoring (4) ─────────────────────────────────────────────────
  "portfolio-alerts": {
    id: "portfolio-alerts",
    name: "Portfolio Alerts",
    category: "monitoring",
    icon: "●",
    defaultW: 6,
    defaultH: 3,
    description: "Active alerts for drawdown, volatility, or weight drift thresholds.",
    status: "ready",
  },
  "exchange-status": {
    id: "exchange-status",
    name: "Exchange Status",
    category: "monitoring",
    icon: "●",
    defaultW: 4,
    defaultH: 3,
    description: "Connection health for each linked exchange API key.",
    status: "ready",
  },
  "strategy-health": {
    id: "strategy-health",
    name: "Strategy Health",
    category: "monitoring",
    icon: "●",
    defaultW: 6,
    defaultH: 3,
    description: "Per-strategy uptime, data freshness, and anomaly flags.",
    status: "ready",
  },
  "data-freshness": {
    id: "data-freshness",
    name: "Data Freshness",
    category: "monitoring",
    icon: "●",
    defaultW: 4,
    defaultH: 3,
    description: "Last sync time per data source with staleness warnings.",
    status: "ready",
  },

  // ── Intelligence (3) ───────────────────────────────────────────────
  "morning-briefing": {
    id: "morning-briefing",
    name: "Morning Briefing",
    category: "intelligence",
    icon: "◈",
    defaultW: 6,
    defaultH: 4,
    description: "AI-generated daily summary of portfolio activity and market context.",
    status: "ready",
  },
  "regime-detector": {
    id: "regime-detector",
    name: "Regime Detector",
    category: "intelligence",
    icon: "◈",
    defaultW: 6,
    defaultH: 3,
    description: "Hidden Markov Model regime classification (risk-on/off/neutral).",
    status: "ready",
  },
  "concentration-risk": {
    id: "concentration-risk",
    name: "Concentration Risk",
    category: "intelligence",
    icon: "◈",
    defaultW: 4,
    defaultH: 3,
    description: "Herfindahl index and top-N concentration metrics.",
    status: "ready",
  },

  // ── Meta (3) ───────────────────────────────────────────────────────
  "custom-kpi-strip": {
    id: "custom-kpi-strip",
    name: "Custom KPI Strip",
    category: "meta",
    icon: "≡",
    defaultW: 12,
    defaultH: 2,
    description: "User-configurable row of key metrics.",
    status: "ready",
  },
  "notes-widget": {
    id: "notes-widget",
    name: "Notes",
    category: "meta",
    icon: "≡",
    defaultW: 4,
    defaultH: 3,
    description: "Free-form markdown notes pinned to the dashboard.",
    status: "ready",
  },
  "quick-actions": {
    id: "quick-actions",
    name: "Quick Actions",
    category: "meta",
    icon: "≡",
    defaultW: 4,
    defaultH: 2,
    description: "One-click shortcuts: rebalance, export, share, snapshot.",
    status: "ready",
  },
};

// ---------------------------------------------------------------------------
// Category metadata for the widget picker modal
// ---------------------------------------------------------------------------

export const WIDGET_CATEGORIES = [
  { id: "performance" as const, name: "Performance", icon: "▲" },
  { id: "risk" as const, name: "Risk", icon: "◆" },
  { id: "allocation" as const, name: "Allocation", icon: "◉" },
  { id: "attribution" as const, name: "Attribution", icon: "▸" },
  { id: "positions" as const, name: "Positions", icon: "▦" },
  { id: "monitoring" as const, name: "Monitoring", icon: "●" },
  { id: "intelligence" as const, name: "Intelligence", icon: "◈" },
  { id: "meta" as const, name: "Meta", icon: "≡" },
];
