-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260516170000_match_decisions_visibility_check_secdef_fix.sql
-- --------------------------------------------------------------------------
-- STEP 1: replace helper with fail-closed orphan-org branch
-- --------------------------------------------------------------------------
-- audit-2026-05-07 MED-3 — Before this migration, an org with zero members
-- (post-sanitize emptied state, or freshly-created un-onboarded state)
-- caused the helper to RETURN TRUE → ANY allocator could commit voluntary_add
-- / bridge_recommended against strategies in that org. This widened
-- visibility beyond the strategies_org_read RLS predicate. Fix: orphan-org
-- now returns FALSE; rare legitimate sanitize-orphan-recovery is handled
-- via manual admin override (separate runbook), not via a permanent
-- code-path that doubles as a probe-existence oracle.
CREATE OR REPLACE FUNCTION public._assert_strategy_visible_to_allocator(
  p_strategy_id UUID,
  p_allocator_id UUID
)
RETURNS BOOLEAN
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $fn$
DECLARE
  v_org_id UUID;
  v_is_member BOOLEAN;
BEGIN
  IF p_strategy_id IS NULL THEN
    -- voluntary_remove / voluntary_modify have NULL strategy_id by
    -- CHECK; treat as visible (the visibility gate is for strategy-
    -- bearing kinds only).
    RETURN TRUE;
  END IF;

  -- Look up the strategy's organization scope. If organization_id is
  -- NULL, the strategy is owner-scoped (no org gate) and globally
  -- visible while published — return TRUE.
  SELECT organization_id INTO v_org_id
    FROM strategies
   WHERE id = p_strategy_id;

  IF v_org_id IS NULL THEN
    RETURN TRUE;
  END IF;

  -- Strategy is org-scoped. Allocator must be in organization_members.
  -- audit-2026-05-07 MED-3: orphan-org (zero members) no longer
  -- returns TRUE. The prior fast-path silently flipped sanitize-orphan
  -- strategies to globally allocator-visible. Failing closed is safer;
  -- legitimate post-sanitize unblock is via manual admin override.
  SELECT EXISTS (
    SELECT 1 FROM organization_members
     WHERE organization_id = v_org_id
       AND user_id = p_allocator_id
  ) INTO v_is_member;

  RETURN COALESCE(v_is_member, FALSE);
END;
$fn$;
