-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260516160200_retention_crons_schema_drift_probe.sql
-- --------------------------------------------------------------------------
-- STEP 1: install the retention-column existence assertion helper
-- --------------------------------------------------------------------------
-- The helper inspects information_schema.columns and raises EXCEPTION
-- if any of the three columns the retention crons reference is missing.
-- Domain-specific ERRCODE so callers can distinguish from generic
-- 42703 errors.
CREATE OR REPLACE FUNCTION public._assert_retention_columns()
RETURNS VOID
LANGUAGE plpgsql
AS $fn$
DECLARE
  v_missing TEXT[] := ARRAY[]::TEXT[];
  v_pair TEXT;
BEGIN
  -- Each row is "schema.table.column" — concise for error messages.
  FOREACH v_pair IN ARRAY ARRAY[
    'public.api_keys.is_active',
    'public.profiles.email',
    'public.notification_dispatches.recipient_email',
    'public.notification_dispatches.notification_type',
    'public.notification_dispatches.status',
    'public.notification_dispatches.created_at'
  ] LOOP
    PERFORM 1 FROM information_schema.columns
     WHERE table_schema = split_part(v_pair, '.', 1)
       AND table_name   = split_part(v_pair, '.', 2)
       AND column_name  = split_part(v_pair, '.', 3);
    IF NOT FOUND THEN
      v_missing := v_missing || v_pair;
    END IF;
  END LOOP;

  IF array_length(v_missing, 1) > 0 THEN
    RAISE EXCEPTION
      '_assert_retention_columns: schema drift detected — column(s) referenced by retention crons are missing: %. audit-2026-05-07 H-0923.',
      array_to_string(v_missing, ', ')
      USING ERRCODE = 'undefined_column';
  END IF;
END;
$fn$;
