-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260530120000_admin_role_mutate.sql
-- --------------------------------------------------------------------------
-- STEP 1: admin_role_mutate SECURITY DEFINER RPC
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.admin_role_mutate(
  p_actor_id  UUID,
  p_target_id UUID,
  p_role      TEXT,
  p_action    TEXT
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_actor_is_admin   BOOLEAN;
  v_target_exists    BOOLEAN;
  v_role_is_admin    BOOLEAN := (p_role = 'admin');
  v_was_new_grant    BOOLEAN := FALSE;
  v_removed_rows     INT     := 0;
  v_was_is_admin     BOOLEAN := FALSE;
  v_is_admin_changed BOOLEAN := FALSE;
  v_surviving_admins INT;
  v_outcome          TEXT;
  v_holds_role       BOOLEAN;
  v_took_effect      BOOLEAN;
  v_roles            TEXT[];
BEGIN
  -- ── Parameter validation (22023 → 400; defensive — body is Zod-validated) ──
  IF p_actor_id IS NULL OR p_target_id IS NULL THEN
    RAISE EXCEPTION 'admin_role_mutate: p_actor_id and p_target_id are required'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;
  IF p_action NOT IN ('grant', 'revoke') THEN
    RAISE EXCEPTION 'admin_role_mutate: p_action must be grant|revoke, got %', p_action
      USING ERRCODE = 'invalid_parameter_value';
  END IF;
  -- Keep this CHECK list in lockstep with user_app_roles.role (migration 054)
  -- and APP_ROLES (src/lib/auth.ts).
  IF p_role NOT IN ('admin', 'allocator', 'quant_manager', 'analyst') THEN
    RAISE EXCEPTION 'admin_role_mutate: p_role % is not a known app role', p_role
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- ── Serialize every mutation on this target (closes the JS TOCTOU window).
  -- A xact-scoped advisory lock (auto-released at COMMIT/ROLLBACK) namespaced to
  -- this function so it never collides with another advisory-lock user. The
  -- last-admin count + the dual-store write below are now race-free against a
  -- concurrent grant/revoke on the same target. ──────────────────────────────
  PERFORM pg_advisory_xact_lock(hashtext('admin_role_mutate'), hashtext(p_target_id::text));

  -- ── Fresh actor authz — the SAME union isAdminUser uses (is_admin OR a
  -- user_app_roles 'admin' row). Re-checked inside the locked txn so an actor
  -- demoted after withRole('admin') ran is rejected here (defense-in-depth that
  -- also makes the JS fresh-client re-check redundant). ──────────────────────
  SELECT (
    EXISTS (SELECT 1 FROM profiles       WHERE id      = p_actor_id AND is_admin = TRUE)
    OR
    EXISTS (SELECT 1 FROM user_app_roles WHERE user_id = p_actor_id AND role    = 'admin')
  ) INTO v_actor_is_admin;
  IF NOT v_actor_is_admin THEN
    RAISE EXCEPTION 'admin_role_mutate: actor % is not an admin', p_actor_id
      USING ERRCODE = 'insufficient_privilege';  -- 42501 → 403
  END IF;

  -- ── Self-revoke of admin is forbidden — another admin must act. Matches the
  -- route's prior hard rail; hint lets the route pick the specific 403 message. ─
  IF p_action = 'revoke' AND v_role_is_admin AND p_actor_id = p_target_id THEN
    RAISE EXCEPTION 'admin_role_mutate: an admin cannot revoke their own admin role'
      USING ERRCODE = 'insufficient_privilege',  -- 42501 → 403
            HINT    = 'self_revoke_forbidden';
  END IF;

  -- ── Target must exist (mirror GET's 404 user_not_found contract). ──────────
  SELECT EXISTS (SELECT 1 FROM profiles WHERE id = p_target_id) INTO v_target_exists;
  IF NOT v_target_exists THEN
    RAISE EXCEPTION 'admin_role_mutate: target user % does not exist', p_target_id
      USING ERRCODE = 'no_data_found';  -- P0002 → 404
  END IF;

  -- Capture the primary-flag pre-state for the admin path (ghost-admin clear).
  IF v_role_is_admin THEN
    SELECT COALESCE(is_admin, FALSE) INTO v_was_is_admin FROM profiles WHERE id = p_target_id;
  END IF;

  IF p_action = 'grant' THEN
    -- Idempotent row insert. ROW_COUNT after ON CONFLICT DO NOTHING is 1 iff a
    -- row was actually inserted → that IS "was_new_grant" (no separate pre-read,
    -- and no TOCTOU on it — we hold the advisory lock).
    INSERT INTO user_app_roles (user_id, role, granted_by, granted_at)
    VALUES (p_target_id, p_role, p_actor_id, now())
    ON CONFLICT (user_id, role) DO NOTHING;
    GET DIAGNOSTICS v_removed_rows = ROW_COUNT;
    v_was_new_grant := (v_removed_rows = 1);

    -- Dual-store lockstep: an admin grant also asserts the primary flag, so a
    -- granted admin can never be a row-only admin. Non-admin grants leave
    -- is_admin alone (there is no profile flag for those roles).
    IF v_role_is_admin AND NOT v_was_is_admin THEN
      UPDATE profiles SET is_admin = TRUE WHERE id = p_target_id;
      v_is_admin_changed := TRUE;
    END IF;

    v_outcome := 'granted';

  ELSE  -- p_action = 'revoke'
    IF v_role_is_admin THEN
      -- Last-admin guard: count the DEDUP'd UNION of surviving admins across
      -- BOTH stores, excluding the target. UNION (not two summed counts) so a
      -- single survivor holding both signals counts once — the exact H-02 bug.
      SELECT COUNT(*) INTO v_surviving_admins FROM (
        SELECT id      AS uid FROM profiles       WHERE is_admin = TRUE  AND id      <> p_target_id
        UNION
        SELECT user_id AS uid FROM user_app_roles WHERE role     = 'admin' AND user_id <> p_target_id
      ) survivors;
      IF v_surviving_admins = 0 THEN
        RAISE EXCEPTION 'admin_role_mutate: refusing to revoke the last admin account'
          USING ERRCODE = 'check_violation',  -- 23514 → 409
                HINT    = 'would_orphan_last_admin';
      END IF;
    END IF;

    DELETE FROM user_app_roles WHERE user_id = p_target_id AND role = p_role;
    GET DIAGNOSTICS v_removed_rows = ROW_COUNT;

    -- Admin revoke also clears the primary flag — so a ghost-admin (is_admin
    -- TRUE, no row) is fully demoted even though the DELETE removed 0 rows.
    IF v_role_is_admin AND v_was_is_admin THEN
      UPDATE profiles SET is_admin = FALSE WHERE id = p_target_id;
      v_is_admin_changed := TRUE;
    END IF;

    -- No-op ⇔ nothing changed in EITHER store. For admin, clearing is_admin
    -- counts as a real revoke even with 0 rows removed.
    IF v_removed_rows = 0 AND NOT v_is_admin_changed THEN
      v_outcome := 'revoke_noop';  -- → 404 role_not_held (caller does NOT emit role.revoke)
    ELSE
      v_outcome := 'revoked';
    END IF;
  END IF;

  -- ── Took-effect verify: re-read inside the same txn (post-mutation reality). ─
  SELECT EXISTS (
    SELECT 1 FROM user_app_roles WHERE user_id = p_target_id AND role = p_role
  ) INTO v_holds_role;
  -- For admin the held-state must also reflect the primary flag.
  IF v_role_is_admin THEN
    v_holds_role := v_holds_role OR EXISTS (
      SELECT 1 FROM profiles WHERE id = p_target_id AND is_admin = TRUE
    );
  END IF;

  IF p_action = 'grant' THEN
    v_took_effect := v_holds_role;        -- after a grant the role should be held
  ELSIF v_outcome = 'revoked' THEN
    v_took_effect := NOT v_holds_role;    -- after a revoke the role should be gone
  ELSE
    v_took_effect := TRUE;                -- revoke_noop: nothing to take effect
  END IF;

  -- Post-mutation full role set — same shape the route's fetchUserRoles returned
  -- (user_app_roles only; the CHECK constraint already bounds role to AppRole).
  SELECT COALESCE(array_agg(role ORDER BY role), ARRAY[]::TEXT[])
    INTO v_roles
  FROM user_app_roles WHERE user_id = p_target_id;

  RETURN jsonb_build_object(
    'outcome',          v_outcome,
    'was_new_grant',    v_was_new_grant,
    'removed_rows',     v_removed_rows,
    'is_admin_changed', v_is_admin_changed,
    'holds_role',       v_holds_role,
    'took_effect',      v_took_effect,
    'roles',            to_jsonb(v_roles)
  );
END;
$$;
