-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260602173710_advance_sync_cursor_claim_token_fence.sql
CREATE OR REPLACE FUNCTION advance_sync_cursor(
  p_api_key_id      UUID,
  p_job_id          UUID,
  p_claim_token     UUID        DEFAULT NULL,
  p_last_fetched_ts TIMESTAMPTZ DEFAULT NULL,
  p_last_sync_at    TIMESTAMPTZ DEFAULT NULL,
  p_account_balance NUMERIC     DEFAULT NULL
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  IF p_api_key_id IS NULL THEN
    RAISE EXCEPTION 'advance_sync_cursor: p_api_key_id is required'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- NEW-C12-05 ownership fence. Only active when a token is supplied; the
  -- NULL arm preserves the legacy unconditional-write path (see header).
  IF p_claim_token IS NOT NULL THEN
    IF p_job_id IS NULL THEN
      RAISE EXCEPTION 'advance_sync_cursor: p_job_id is required when p_claim_token is supplied'
        USING ERRCODE = 'invalid_parameter_value';
    END IF;

    IF NOT EXISTS (
      SELECT 1
        FROM compute_jobs
       WHERE id = p_job_id
         AND status = 'running'
         AND claim_token = p_claim_token
    ) THEN
      -- Orphan: the watchdog reclaimed this job (status no longer 'running'
      -- or token rotated to W2). Drop the epilogue write rather than race the
      -- owner. Caller distinguishes FALSE (owned-check failed) from an
      -- exception (DB error) and logs the orphan-blocked signal.
      RETURN FALSE;
    END IF;
  END IF;

  -- Owned (or back-compat NULL arm): apply the monotonic-guarded write in a
  -- single atomic UPDATE. Each timestamp advances only when strictly newer
  -- (defence-in-depth that survives even when the fence is inert); the
  -- balance has no ordering so it is overwritten when supplied.
  UPDATE api_keys
     SET last_fetched_trade_timestamp = CASE
           WHEN p_last_fetched_ts IS NOT NULL
                AND (last_fetched_trade_timestamp IS NULL
                     OR last_fetched_trade_timestamp < p_last_fetched_ts)
             THEN p_last_fetched_ts
             ELSE last_fetched_trade_timestamp
           END,
         last_sync_at = CASE
           WHEN p_last_sync_at IS NOT NULL
                AND (last_sync_at IS NULL OR last_sync_at < p_last_sync_at)
             THEN p_last_sync_at
             ELSE last_sync_at
           END,
         account_balance_usdt = COALESCE(p_account_balance, account_balance_usdt)
   WHERE id = p_api_key_id;

  RETURN TRUE;
END;
$$;
