-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260529170100_circuit_breaker_db_clock_rpcs.sql
-- --------------------------------------------------------------------------
-- STEP 2: api_key_cooldown_remaining — remaining cooldown, single DB clock.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION api_key_cooldown_remaining(
  p_api_key_id       UUID,
  p_cooldown_seconds INTEGER
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_last_429_at TIMESTAMPTZ;
  v_remaining   NUMERIC;
BEGIN
  IF p_api_key_id IS NULL THEN
    RAISE EXCEPTION 'api_key_cooldown_remaining: p_api_key_id is required'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  IF p_cooldown_seconds IS NULL OR p_cooldown_seconds < 0 THEN
    RAISE EXCEPTION 'api_key_cooldown_remaining: p_cooldown_seconds must be >= 0, got %', p_cooldown_seconds
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  SELECT last_429_at
    INTO v_last_429_at
    FROM api_keys
    WHERE id = p_api_key_id;

  -- No stamp (or key gone) → no active cooldown.
  IF NOT FOUND OR v_last_429_at IS NULL THEN
    RETURN 0;
  END IF;

  -- Both now() and last_429_at are DB-clock values → no cross-container
  -- wall-clock skew. CEIL so we never under-report and release the breaker a
  -- fraction early.
  v_remaining := p_cooldown_seconds - EXTRACT(EPOCH FROM (now() - v_last_429_at));
  IF v_remaining <= 0 THEN
    RETURN 0;
  END IF;
  RETURN CEIL(v_remaining)::INTEGER;
END;
$$;
