-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260510180226_compute_jobs_audit_2026_05_07_g10b.sql
-- --------------------------------------------------------------------
-- P17: check_fan_in_ready — RAISE NOTICE on missing child
-- --------------------------------------------------------------------
-- Distinguish "child row missing" (orphan parent_job_ids reference)
-- from "parents not all done" (legitimate not-ready). Both still
-- return false to preserve the caller contract — NOTICE is non-rolling-
-- back diagnostic only — but the operator now sees a log line for the
-- orphan case rather than silent accumulation.
CREATE OR REPLACE FUNCTION check_fan_in_ready(
  p_child_job_id UUID
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_parent_ids    UUID[];
  v_unready_count INTEGER;
  v_row_found     BOOLEAN;
BEGIN
  SELECT parent_job_ids, true
    INTO v_parent_ids, v_row_found
    FROM compute_jobs
    WHERE id = p_child_job_id;

  IF NOT FOUND THEN
    -- Orphan reference. Surface a NOTICE so operators can detect
    -- accumulating drift without changing the legacy return value
    -- (false). (mig 109 P17 / G10.B.17)
    RAISE NOTICE 'check_fan_in_ready: child job % missing — possible orphan parent_job_ids reference', p_child_job_id;
    RETURN false;
  END IF;

  IF v_parent_ids IS NULL THEN
    RETURN false;
  END IF;

  IF array_length(v_parent_ids, 1) IS NULL OR array_length(v_parent_ids, 1) = 0 THEN
    -- No parents -> always ready (leaf job).
    RETURN true;
  END IF;

  SELECT count(*) INTO v_unready_count
    FROM compute_jobs
    WHERE id = ANY(v_parent_ids)
      AND status <> 'done';

  RETURN v_unready_count = 0;
END;
$$;
