-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260410225610_sec005_follow_ups.sql
-- --------------------------------------------------------------------------
-- STEP 3: hardened trigger function. Replaces the migration 028 version.
--
-- Changes vs migration 028:
--   - Short-circuit on no-op api_key_id updates (IS NOT DISTINCT FROM OLD).
--   - Schema-qualified `public.api_keys` so search_path manipulation cannot
--     redirect the EXISTS lookup.
--   - Hardened search_path to `pg_catalog, public`.
--   - `FOR SHARE` lock on the EXISTS row, blocking concurrent DELETE races.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION check_strategy_api_key_ownership()
RETURNS TRIGGER AS $$
BEGIN
  -- Skip the check when the strategy has no linked key (draft + CSV paths).
  IF NEW.api_key_id IS NULL THEN
    RETURN NEW;
  END IF;

  -- Short-circuit when an UPDATE doesn't actually change api_key_id. Saves
  -- a round-trip to api_keys on every form round-trip write, and prevents
  -- pointless trigger fires on bulk updates that touch other columns.
  IF TG_OP = 'UPDATE'
    AND NEW.api_key_id IS NOT DISTINCT FROM OLD.api_key_id
    AND NEW.user_id IS NOT DISTINCT FROM OLD.user_id
  THEN
    RETURN NEW;
  END IF;

  -- Assert the linked key belongs to the same user as the strategy.
  -- SECURITY DEFINER bypasses RLS so the EXISTS sees the raw ownership
  -- truth. Schema-qualified `public.api_keys` + restricted search_path
  -- prevent any session-level manipulation from redirecting the lookup.
  -- `FOR SHARE` locks the api_keys row for the duration of the transaction
  -- so a concurrent DELETE cannot race between check and commit.
  IF NOT EXISTS (
    SELECT 1
    FROM public.api_keys
    WHERE id = NEW.api_key_id
      AND user_id = NEW.user_id
    FOR SHARE
  ) THEN
    RAISE EXCEPTION
      'api_key_id % does not belong to user % (cross-tenant linkage blocked by migration 028/029)',
      NEW.api_key_id, NEW.user_id
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  RETURN NEW;
END;
$$ LANGUAGE plpgsql SECURITY DEFINER SET search_path = pg_catalog, public;
