-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260826120000_computation_error_curated_copy.sql
-- --------------------------------------------------------------------------
-- computation_error_copy — the ONLY value the status bridge may write to
-- strategy_analytics.computation_error.
-- --------------------------------------------------------------------------
-- Takes an ERROR KIND. Never an error, and never a string derived from one.
-- Its range is the three literals below, so no input can travel through it —
-- that is the guarantee, and it is structural rather than a convention callers
-- have to keep. See the file header for the full argument and for why the
-- three compute_jobs error kinds collapse to two honest sentences plus a
-- cautious default.
--
-- NOT STRICT, deliberately: a NULL kind must resolve to the default sentence,
-- not to NULL. A NULL here would blank the column over a live failure, which is
-- the silent-failure mode the whole surface exists to avoid. (Measured: no
-- failed_final writer at HEAD can produce a NULL kind — this is the belt for a
-- future one.)
CREATE OR REPLACE FUNCTION computation_error_copy(p_error_kind TEXT)
RETURNS TEXT
LANGUAGE sql
IMMUTABLE
SET search_path = pg_catalog
AS $copy$
  SELECT CASE p_error_kind
    -- 'permanent' terminalises on the FIRST failure (mark_compute_job_failed:
    -- `IF p_error_kind = 'permanent' THEN v_new_status := 'failed_final'`), so
    -- no automatic retry has happened and none is coming. Promising a retry
    -- here would be the thing that is false.
    WHEN 'permanent' THEN
      'Analytics could not complete for this strategy, and retrying alone will not resolve it. Contact support if you need this strategy computed.'
    -- 'transient' and 'unknown' SHARE an arm, and the sameness is the honest
    -- part. Neither reaches 'failed_final' except through
    -- `v_attempts >= v_max_attempts`, so the one true statement about both is
    -- that the automatic retries were used up. Splitting them would spend two
    -- sentences implying a difference the user cannot act on.
    WHEN 'transient' THEN
      'Analytics could not complete after several automatic retries. Retry the sync, or contact support if it keeps failing.'
    WHEN 'unknown' THEN
      'Analytics could not complete after several automatic retries. Retry the sync, or contact support if it keeps failing.'
    -- Anything else: NULL, or a kind added after this migration. Says only what
    -- is true of every failure and claims nothing about retries.
    ELSE
      'Analytics could not complete for this strategy. Retry the sync, or contact support if this persists.'
  END
$copy$;
