-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260510173116_strategies_fingerprint_compute_similarity.sql
-- ==========================================================================
-- STEP 2 — compute_similarity cosine function (FINGERPRINT-02)
-- ==========================================================================
-- v0 plain plpgsql cosine over the 46-dim concatenated component vector
-- (4 + 4 + 4 + 10 + 24). IMMUTABLE PARALLEL SAFE so the planner can fold
-- it into queries safely. Returns 0.0 on NULL or shape mismatch — never
-- raises (defense-in-depth for the public-facing similarity ranker).
CREATE OR REPLACE FUNCTION compute_similarity(a JSONB, b JSONB)
RETURNS NUMERIC
LANGUAGE plpgsql
IMMUTABLE PARALLEL SAFE
SET search_path = public, pg_temp
AS $$
DECLARE
  v_a_vec NUMERIC[];
  v_b_vec NUMERIC[];
  v_dot   NUMERIC := 0;
  v_norm_a NUMERIC := 0;
  v_norm_b NUMERIC := 0;
  i INT;
BEGIN
  IF a IS NULL OR b IS NULL THEN RETURN 0.0; END IF;
  IF (a->>'version')::INT IS DISTINCT FROM 1 THEN RETURN 0.0; END IF;
  IF (b->>'version')::INT IS DISTINCT FROM 1 THEN RETURN 0.0; END IF;

  -- Build 46-dim vector by concatenation of 5 components (4+4+4+10+24).
  WITH parts AS (
    SELECT
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(a->'trade_size_buckets')        AS e) AS a1,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(a->'hold_duration_buckets')     AS e) AS a2,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(a->'asset_class_mix')           AS e) AS a3,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(a->'instrument_concentration')  AS e) AS a4,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(a->'temporal_pattern')          AS e) AS a5,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(b->'trade_size_buckets')        AS e) AS b1,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(b->'hold_duration_buckets')     AS e) AS b2,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(b->'asset_class_mix')           AS e) AS b3,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(b->'instrument_concentration')  AS e) AS b4,
      ARRAY(SELECT (e)::NUMERIC FROM jsonb_array_elements_text(b->'temporal_pattern')          AS e) AS b5
  )
  SELECT a1 || a2 || a3 || a4 || a5, b1 || b2 || b3 || b4 || b5
    INTO v_a_vec, v_b_vec
    FROM parts;

  IF v_a_vec IS NULL OR v_b_vec IS NULL THEN RETURN 0.0; END IF;
  IF array_length(v_a_vec, 1) <> 46 OR array_length(v_b_vec, 1) <> 46 THEN RETURN 0.0; END IF;

  FOR i IN 1..46 LOOP
    v_dot    := v_dot    + v_a_vec[i] * v_b_vec[i];
    v_norm_a := v_norm_a + v_a_vec[i] * v_a_vec[i];
    v_norm_b := v_norm_b + v_b_vec[i] * v_b_vec[i];
  END LOOP;

  IF v_norm_a = 0 OR v_norm_b = 0 THEN RETURN 0.0; END IF;

  RETURN GREATEST(0.0, LEAST(1.0, v_dot / (sqrt(v_norm_a) * sqrt(v_norm_b))))::NUMERIC(5,4);
EXCEPTION
  WHEN OTHERS THEN
    RETURN 0.0;
END;
$$;
