-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260826130000_create_wizard_strategy_for_key.sql
-- ────────────────── 1. the writer
CREATE OR REPLACE FUNCTION public.create_wizard_strategy_for_key(
  p_user_id UUID,
  p_api_key_id UUID,
  p_placeholder_name TEXT,
  p_wizard_session_id UUID
)
RETURNS TABLE(strategy_id UUID, api_key_id UUID)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
SET lock_timeout = '3s'
AS $fn$
DECLARE
  v_jwt_role TEXT;
  v_exchange TEXT;
  v_strategy_id UUID;
BEGIN
  -- CANARY_162_05_PROSE_ONLY — see header (vii). This token lives in a comment
  -- and nowhere else in this body; the gate's arm D requires it to be GONE from
  -- the comment-stripped definition, which is what proves the stripper ran.

  -- ── gate 1: service_role only. Fail-closed wrapper carried from
  -- 20260515113753 and from the twin at 20260814120000: a malformed
  -- request.jwt.claims makes auth.role() RAISE rather than return NULL, and
  -- NULL then fails the IS DISTINCT FROM test and is REFUSED.
  BEGIN
    v_jwt_role := auth.role();
  EXCEPTION WHEN OTHERS THEN
    v_jwt_role := NULL;
  END;

  IF v_jwt_role IS DISTINCT FROM 'service_role' THEN
    RAISE EXCEPTION 'create_wizard_strategy_for_key: caller role (%) may not write wizard drafts',
      COALESCE(v_jwt_role, '<none>')
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  -- ── gate 2: auth.uid() is NULL under service_role, so p_user_id is the ONLY
  -- carrier of the owning identity and a NULL would make the ownership
  -- assertion below compare against nothing. Refuse it explicitly.
  IF p_user_id IS NULL OR p_api_key_id IS NULL THEN
    RAISE EXCEPTION 'create_wizard_strategy_for_key: p_user_id and p_api_key_id must not be NULL'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- ── the idempotency fence, copied from create_wizard_strategy's discipline
  -- but keyed on the KEY rather than on the wizard session, and that difference
  -- is the point. The population this path serves LOST its localStorage session
  -- token (that is how the key was orphaned in the first place), so a
  -- session-keyed fence would let every retry mint another draft over the same
  -- key. A transaction-scoped advisory lock is auto-released on commit/rollback
  -- and is not subject to lock_timeout. DISTINCT 'wizreuse:' lock space so the
  -- 'wizdraft:' and 'wizcomposite:' fences are untouched.
  PERFORM pg_advisory_xact_lock(
    hashtext('wizreuse:' || p_user_id::text || ':' || p_api_key_id::text)
  );

  -- ── gate 3: THE OWNERSHIP ASSERTION. This is the in-database half of the
  -- T-162-05-A mitigation; the route's session-uid `.eq("user_id", …)` filter on
  -- the admin client and its user-scoped RLS re-read are the other two layers.
  -- Cross-tenant reuse requires all three to fail at once.
  --
  -- ⭐ `disconnected_at IS NULL` IS PART OF THE ASSERTION, NOT A NICETY.
  -- api_keys rows are RETAINED on disconnect (20260422101911) and every cron
  -- dispatcher deliberately SKIPS a soft-disconnected key, so a draft minted
  -- over one would be a strategy that silently never syncs — the exact defect
  -- the venue-identity fence's mirrored predicate exists to prevent.
  --
  -- ⭐ AND THE VENUE COMES OUT OF THE ROW, NOT OFF THE WIRE. create_wizard_strategy
  -- takes p_exchange from the caller because it is minting the api_keys row and
  -- has nowhere else to get it. Here the row already exists and carries the
  -- venue this server observed a successful read-only authentication at, so this
  -- function has NO venue parameter at all and cannot be handed a forged one.
  -- That is a strictly narrower surface than the twin's, by construction.
  SELECT k.exchange
    INTO v_exchange
    FROM api_keys k
   WHERE k.id = p_api_key_id
     AND k.user_id = p_user_id
     AND k.disconnected_at IS NULL;

  IF NOT FOUND THEN
    -- ⛔ ONE ANSWER FOR "not yours", "does not exist" and "disconnected",
    -- deliberately: three distinguishable refusals would be an ownership oracle
    -- for anyone holding the service key, and the route maps this SQLSTATE to a
    -- single refusal for the same reason.
    RAISE EXCEPTION 'create_wizard_strategy_for_key: no live api_keys row for this owner'
      USING ERRCODE = 'no_data_found';
  END IF;

  -- ── replay: an existing wizard draft over this key IS the answer. Returned
  -- before the connected check below, because a draft is a strategy and would
  -- otherwise be refused as "already connected" on the second call.
  SELECT s.id
    INTO v_strategy_id
    FROM strategies s
   WHERE s.user_id = p_user_id
     AND s.api_key_id = p_api_key_id
     AND s.source = 'wizard'
     AND s.status = 'draft'
   ORDER BY s.created_at ASC
   LIMIT 1;

  IF v_strategy_id IS NOT NULL THEN
    RETURN QUERY SELECT v_strategy_id, p_api_key_id;
    RETURN;
  END IF;

  -- ── gate 4: the CONNECTED refusal. Something already uses this key, so it is
  -- not an orphan and minting a second strategy over it would duplicate the
  -- user's own account across two strategies — the defect WIZCONT-02's fence
  -- exists to prevent, arriving through a different door.
  --
  -- ⭐ `strategy_keys` IS CHECKED TOO, AND THE ROUTE'S TWO-READ RESOLVER CANNOT
  -- SEE IT. A composite member key is linked through `strategy_keys`, while
  -- `strategies.api_key_id` stays NULL on the composite draft — so the route's
  -- `orphaned` measurement (both strategies reads empty) reports a live
  -- composite member as an orphan. That is a pre-existing property of that
  -- resolver, and it is why this assertion is here rather than only there: this
  -- is the last line before the INSERT.
  --
  -- ⛔ NEITHER EXISTS IS SCOPED TO p_user_id, deliberately. The key is already
  -- proven to belong to p_user_id above, so a row referencing it from any owner
  -- is either the same tenant's or a data fault — and in both cases the honest
  -- answer is "something holds this key", not "nothing does".
  IF EXISTS (SELECT 1 FROM strategies s WHERE s.api_key_id = p_api_key_id)
     OR EXISTS (SELECT 1 FROM strategy_keys sk WHERE sk.api_key_id = p_api_key_id)
  THEN
    RAISE EXCEPTION 'create_wizard_strategy_for_key: api key % is already held by a strategy', p_api_key_id
      USING ERRCODE = 'object_in_use';
  END IF;

  -- ── the write. Mirrors create_wizard_strategy's `strategies` INSERT
  -- column-for-column; the api_keys INSERT that sits above it there has no
  -- counterpart here and must never gain one (header ⛔ (i)).
  INSERT INTO strategies (
    user_id, api_key_id, name, status, source,
    strategy_types, subtypes, markets, supported_exchanges,
    wizard_session_id
  )
  VALUES (
    p_user_id, p_api_key_id,
    COALESCE(NULLIF(btrim(p_placeholder_name), ''), 'Untitled strategy'),
    'draft', 'wizard',
    '{}', '{}', '{}', ARRAY[v_exchange],
    p_wizard_session_id
  )
  RETURNING id INTO v_strategy_id;

  RETURN QUERY SELECT v_strategy_id, p_api_key_id;
END;
$fn$;
