-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260827120000_strategy_shares_generation_model.sql
-- --------------------------------------------------------------------------
-- STEP 3: create_strategy_share(p_strategy_id) — atomic mint-or-reuse
-- --------------------------------------------------------------------------
-- ONE statement: insert the counter row, or reactivate the existing one. The
-- caller gets back the CURRENT generation and derives the token from it in
-- Node, so:
--   * strategy never shared -> row at generation 1 -> a fresh link;
--   * strategy already live -> the SAME generation -> the SAME link (SHARE-01
--     reuse: Copy Link is idempotent and never breaks the recipient's url);
--   * strategy revoked      -> revoked_at cleared, generation UNCHANGED at the
--     already-advanced value -> a link that differs from every revoked one.
--
-- Why an RPC rather than a client-side upsert (RESEARCH assumption A4): the
-- state machine — "never touch created_by or created_at on reactivation, never
-- touch generation on mint" — lives in ONE place instead of being re-derived
-- correctly by every future call site. `created_by` is sourced from auth.uid()
-- INSIDE the body and is never a parameter, so a forged owner is impossible.
--
-- SECURITY INVOKER (stated explicitly, not left to the default): this runs AS
-- THE CALLER, so `strategy_shares_owner` gates it — including the CR-01
-- owner-coherence EXISTS clause. A caller cannot mint for a strategy they do
-- not own through this RPC either; the WITH CHECK raises and the function's
-- implicit subtransaction rolls back. STABLE would be wrong here (this writes);
-- VOLATILE is correct and is the omitted default.
--
-- ON CONFLICT + RLS: on the DO UPDATE path Postgres evaluates the policy's
-- USING against the existing row and its WITH CHECK against the updated row.
-- A conflicting row belonging to another tenant therefore ERRORS rather than
-- being silently updated — no cross-tenant write, and the route surfaces a
-- generic failure rather than an existence oracle.
CREATE OR REPLACE FUNCTION public.create_strategy_share(p_strategy_id UUID)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_generation INTEGER;
BEGIN
  IF p_strategy_id IS NULL THEN
    RAISE EXCEPTION 'create_strategy_share: p_strategy_id must not be NULL'
      USING ERRCODE = 'null_value_not_allowed';
  END IF;

  -- Atomic reactivate-or-insert. ⛔ generation is deliberately ABSENT from the
  -- DO UPDATE SET list: reactivation must NOT rewind the counter, or every
  -- previously revoked link would come back to life. created_by/created_at are
  -- likewise never rewritten — the row keeps its original provenance.
  INSERT INTO public.strategy_shares (strategy_id, created_by)
  VALUES (p_strategy_id, auth.uid())
  ON CONFLICT (strategy_id) DO UPDATE
    SET revoked_at = NULL
  RETURNING strategy_shares.generation INTO v_generation;

  RETURN v_generation;
END;
$$;
