-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260622120000_scenario_shares_and_read_rpc.sql
-- --------------------------------------------------------------------------
-- STEP 2b: create_scenario_share(p_scenario_id, p_token_hash) — ATOMIC mint
-- --------------------------------------------------------------------------
-- WR-02 ATOMICITY: the generate route previously did a pre-revoke UPDATE and a
-- separate INSERT as two non-atomic statements. If the pre-revoke succeeded but
-- the INSERT failed (transient 5xx, a 23505 race against the partial unique
-- index), the scenario was left with NO active share even though one existed a
-- moment earlier — the prior link was dead with no replacement. This function
-- folds revoke-then-insert into ONE transaction: a PL/pgSQL function runs in a
-- single (sub)transaction, so any error inside it rolls back BOTH writes. The
-- "one active share per scenario" invariant is therefore never violated by a
-- partial write — either the new share replaces the old atomically, or nothing
-- changes.
--
-- SECURITY INVOKER (the default; stated explicitly): unlike get_shared_scenario
-- (the anon read path, DEFINER), this runs AS THE CALLER so RLS still gates it.
-- The scenario_shares_owner policy enforces created_by = auth.uid() AND the
-- CR-01 owner-coherence EXISTS clause, so a caller cannot mint a share for a
-- scenario they do not own through this RPC either — the WITH CHECK rejects the
-- INSERT (raising, which rolls the function back). created_by is sourced from
-- auth.uid() INSIDE the function, never a parameter, so a forged created_by is
-- impossible.
--
-- search_path = public, pg_temp matches the read-path canon. STABLE is wrong
-- here (this writes) — VOLATILE (the default) is correct and omitted.
CREATE FUNCTION public.create_scenario_share(
  p_scenario_id UUID,
  p_token_hash  TEXT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_share_id UUID;
BEGIN
  -- Revoke any prior active share for this scenario. RLS scopes this to the
  -- caller's own rows (created_by = auth.uid()); a scenario the caller does not
  -- own matches 0 rows. This and the INSERT below are in ONE transaction.
  UPDATE scenario_shares
     SET revoked_at = now()
   WHERE scenario_id = p_scenario_id
     AND revoked_at IS NULL;

  -- Insert the new active share. created_by is auth.uid() (never a param), so
  -- the RLS WITH CHECK (created_by = auth.uid() AND the caller owns the
  -- scenario) gates it; a non-owned scenario raises here and rolls back the
  -- revoke above — the prior link is NOT left dead with no replacement.
  INSERT INTO scenario_shares (scenario_id, created_by, token_hash)
  VALUES (p_scenario_id, auth.uid(), p_token_hash)
  RETURNING id INTO v_share_id;

  RETURN v_share_id;
END;
$$;
