-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260514045627_cutover_strategy_metrics_keys_atomic.sql
-- --------------------------------------------------------------------------
-- STEP 1: Create the new atomic cutover RPC. Order matters: this CREATE
--         OR REPLACE lands BEFORE the DROP of the unsafe predecessor so
--         there is no gap where the schema has zero cutover function.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.cutover_strategy_metrics_keys_atomic(
  p_strategy_id UUID
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $func$
DECLARE
  v_snapshot         JSONB;
  v_payload          JSONB := '{}'::jsonb;
  v_kind             text;
  v_moved            int := 0;
  v_row_count        int;
  -- P2046 allowlist — matches Python HEAVY_KINDS verbatim. Keep in sync.
  -- The list is INTERNAL to the function body; callers cannot widen it.
  v_allowlist        text[] := ARRAY[
    'daily_returns_grid',
    'rolling_sortino_3m','rolling_sortino_6m','rolling_sortino_12m',
    'rolling_volatility_3m','rolling_volatility_6m','rolling_volatility_12m',
    'rolling_alpha','rolling_beta',
    'exposure_series','turnover_series','log_returns_series'
  ];
BEGIN
  -- P2047 — read metrics_json INSIDE the function body under FOR UPDATE so
  -- analytics_runner's concurrent write cannot land between the snapshot and
  -- the strip step. The row lock acquired here is held until COMMIT.
  SELECT metrics_json INTO v_snapshot
    FROM strategy_analytics
   WHERE strategy_id = p_strategy_id
   FOR UPDATE;
  IF v_snapshot IS NULL THEN
    RAISE EXCEPTION 'cutover_strategy_metrics_keys_atomic: strategy_id % not found', p_strategy_id
      USING ERRCODE = 'P0002';
  END IF;

  -- P2046 — project only the allowlisted heavy keys present in the snapshot.
  -- Any caller-side compromise that injected non-heavy keys would have
  -- failed at the function boundary because the new signature has no
  -- caller-supplied key set; defense-in-depth keeps the projection step
  -- here too so the body alone enforces the invariant.
  FOREACH v_kind IN ARRAY v_allowlist LOOP
    IF v_snapshot ? v_kind THEN
      v_payload := v_payload || jsonb_build_object(v_kind, v_snapshot -> v_kind);
      v_moved := v_moved + 1;
    END IF;
  END LOOP;

  IF v_moved = 0 THEN
    -- No heavy kinds present — nothing to do. Return a visible signal so
    -- the caller can log "nothing-to-do" distinctly from "moved N".
    RETURN jsonb_build_object('moved', 0);
  END IF;

  -- Sibling upsert. Same shape as migration 087's
  -- upsert_strategy_analytics_series_batch.
  INSERT INTO strategy_analytics_series (strategy_id, kind, payload, computed_at)
  SELECT p_strategy_id, key, value, now()
    FROM jsonb_each(v_payload)
   ON CONFLICT (strategy_id, kind) DO UPDATE
      SET payload     = EXCLUDED.payload,
          computed_at = EXCLUDED.computed_at;

  -- Strip — ONLY the allowlist-intersect of the snapshot (v_payload).
  -- ARBITRARY keys in metrics_json (sharpe, cagr, etc.) are preserved
  -- because they are NOT in v_payload. This is defense-in-depth: even
  -- if a non-allowlist key were somehow injected during the projection
  -- step (impossible given the FOREACH ... IF v_snapshot ? v_kind guard
  -- above), it could not survive past this UPDATE because we strip the
  -- keys of v_payload, not the keys of p_kinds.
  UPDATE strategy_analytics
     SET metrics_json = metrics_json - ARRAY(SELECT jsonb_object_keys(v_payload))
   WHERE strategy_id = p_strategy_id;
  GET DIAGNOSTICS v_row_count = ROW_COUNT;
  IF v_row_count <> 1 THEN
    RAISE EXCEPTION 'cutover_strategy_metrics_keys_atomic: UPDATE affected % rows (expected 1)', v_row_count
      USING ERRCODE = 'P0001';
  END IF;

  RETURN jsonb_build_object('moved', v_moved);
END;
$func$;
