-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260602183000_b5b_api_key_delete_atomicity.sql
-- ==========================================================================
-- 2. delete_api_key_if_unreferenced — atomic orphan-key revoke (M-0347)
-- ==========================================================================
-- Single-statement check+delete shared by the user-driven draft DELETE route
-- (authenticated) and the service-role cleanup-wizard-drafts cron. Dual-mode
-- owner gate:
--   * authenticated caller  → auth.uid() is the user id → may delete only
--     their OWN unreferenced key (user_id = auth.uid()).
--   * service caller        → auth.uid() IS NULL AND role <> 'anon' → the cron
--     orphan sweep may delete ANY unreferenced key. An authenticated request
--     always carries a JWT `sub` (auth.uid() non-null), so it can only ever hit
--     the owner arm; anon is REVOKEd AND blocked at the gate (role='anon') as
--     defense-in-depth against a future grant regression.
-- The NOT EXISTS makes the reference check + delete atomic so a concurrent
-- wizard re-attaching the key cannot have its strategy's key revoked.
CREATE OR REPLACE FUNCTION public.delete_api_key_if_unreferenced(
  p_api_key_id uuid
)
RETURNS integer
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET lock_timeout = '3s'
AS $$
DECLARE
  v_deleted integer := 0;
BEGIN
  DELETE FROM public.api_keys
   WHERE id = p_api_key_id
     -- Dual-mode owner gate (M-0347): the caller owns the key, OR the caller is
     -- a trusted non-end-user service context. auth.uid() IS NULL identifies a
     -- no-`sub` JWT (service_role, whether its claims are populated or bare).
     -- The `auth.role() IS DISTINCT FROM 'anon'` clause is defense-in-depth
     -- (rls-auditor MED-8): even if a future migration regressed EXECUTE to
     -- anon, an anon caller (role='anon', auth.uid() NULL) still could NOT reach
     -- the cross-user arm. It is TRUE for both claimed ('service_role') and bare
     -- (NULL role) service callers, so the cleanup-wizard-drafts cron is
     -- unaffected. The primary gate remains the REVOKE FROM anon below.
     AND (
       user_id = auth.uid()
       OR (auth.uid() IS NULL AND auth.role() IS DISTINCT FROM 'anon')
     )
     AND NOT EXISTS (
       SELECT 1 FROM public.strategies WHERE api_key_id = p_api_key_id
     );
  GET DIAGNOSTICS v_deleted = ROW_COUNT;
  RETURN v_deleted;
END;
$$;
