-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260710160000_api_keys_published_composite_delete_guard.sql
-- 1. The guard function (parity with enforce_strategy_keys_owner_coherence):
--    SECURITY DEFINER + baked search_path so a published-membership read is not
--    subject to search_path hijack, and fires for service-role writers too.
CREATE OR REPLACE FUNCTION public.enforce_api_keys_published_composite_integrity()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public', 'pg_catalog'
AS $function$
BEGIN
  -- M-3: a PUBLISHED composite must never be silently holed by a member-key
  -- delete. RAISE only when OLD.id is a strategy_keys member of a published
  -- strategy — draft/pending_review/archived members and single-key links (which
  -- go through strategies.api_key_id, not strategy_keys) never match.
  IF EXISTS (
    SELECT 1
      FROM public.strategy_keys sk
      JOIN public.strategies s ON s.id = sk.strategy_id
     WHERE sk.api_key_id = OLD.id
       AND s.status = 'published'
  ) THEN
    -- Least-disclosure (ADR-0020): this fn is SECURITY DEFINER and reads
    -- strategy_keys / strategies past their owner-only RLS, so the client-facing
    -- error MUST NOT echo any owner id or leak the existence of another tenant's
    -- strategy — that would turn a failed DELETE into an ownership/existence
    -- oracle. The message is a single constant literal (no interpolation); the
    -- foreign_key_violation ERRCODE gives callers a stable arm.
    RAISE EXCEPTION 'api_keys: cannot delete a key that is a member of a published composite — detach the key or archive the strategy first'
      USING ERRCODE = 'foreign_key_violation';
  END IF;
  RETURN OLD;
END;
$function$;
