-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260420073003_allocator_holdings.sql
-- --------------------------------------------------------------------------
-- f5: Owner-coherence trigger
-- --------------------------------------------------------------------------
-- Couples allocator_id to api_keys.user_id at write time so a future admin
-- reassignment of api_keys.user_id cannot silently fork history under the
-- new owner while old rows persist under the old allocator_id. The unique
-- index (allocator_id, venue, symbol, asof) would otherwise allow two
-- competing truths to coexist under two allocator_id keys.
--
-- SECURITY DEFINER + pinned search_path: the trigger must read api_keys
-- authoritatively (bypassing RLS) to compare NEW.allocator_id against the
-- key's owner. The api_keys RLS policies would filter out the check from
-- inside a service-role write block, so SECURITY DEFINER elevates the
-- function owner's access rights regardless of caller.
CREATE OR REPLACE FUNCTION enforce_allocator_holdings_owner_coherence()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_expected_owner UUID;
BEGIN
  SELECT user_id INTO v_expected_owner
    FROM api_keys
    WHERE id = NEW.api_key_id;
  IF v_expected_owner IS NULL THEN
    RAISE EXCEPTION
      'allocator_holdings.api_key_id (%) does not reference an existing api_keys row',
      NEW.api_key_id;
  END IF;
  IF NEW.allocator_id IS DISTINCT FROM v_expected_owner THEN
    RAISE EXCEPTION
      'allocator_holdings.allocator_id (%) must match api_keys.user_id (%) for api_key_id %',
      NEW.allocator_id, v_expected_owner, NEW.api_key_id;
  END IF;
  RETURN NEW;
END;
$$;
