-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260624120000_csv_daily_returns_per_key_axis.sql
-- 9b. Owner-coherence trigger — parity with allocator_holdings
--     (enforce_allocator_holdings_owner_coherence). DB-enforced defense-in-depth on the
--     tenant-isolation column: a per-key row's denormalized allocator_id MUST equal the
--     owning api_keys.user_id, so a buggy writer or a future api_keys.user_id reassignment
--     can never fork a per-key series under a stale allocator_id. The WHEN clause fires the
--     trigger ONLY for per-key rows (api_key_id IS NOT NULL) — the high-frequency strategy
--     CSV path pays zero trigger overhead.
CREATE OR REPLACE FUNCTION public.enforce_csv_daily_returns_owner_coherence()
  RETURNS trigger
  LANGUAGE plpgsql
  SECURITY DEFINER
  SET search_path TO 'public', 'pg_catalog'
AS $function$
DECLARE
  v_expected_owner UUID;
BEGIN
  -- Defensive (the trigger WHEN clause already gates on this): strategy rows are exempt.
  IF NEW.api_key_id IS NULL THEN
    RETURN NEW;
  END IF;
  SELECT user_id INTO v_expected_owner
    FROM api_keys
    WHERE id = NEW.api_key_id;
  IF v_expected_owner IS NULL THEN
    RAISE EXCEPTION
      'csv_daily_returns.api_key_id (%) does not reference an existing api_keys row',
      NEW.api_key_id;
  END IF;
  IF NEW.allocator_id IS DISTINCT FROM v_expected_owner THEN
    RAISE EXCEPTION
      'csv_daily_returns.allocator_id (%) must match api_keys.user_id (%) for api_key_id %',
      NEW.allocator_id, v_expected_owner, NEW.api_key_id;
  END IF;
  RETURN NEW;
END;
$function$;
