-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260717233529_allocator_equity_derived_surface.sql
-- (d) In-flight dedup: NO new index. The generic
--     compute_jobs_one_inflight_per_kind_allocator (20260418194206:151, partial
--     unique on (allocator_id, kind) for in-flight statuses) already covers the
--     new allocator-scoped derive_allocator_equity kind. The generic
--     compute_jobs_one_inflight_per_kind_api_key (20260420073003:288, partial
--     unique on (api_key_id, kind) for in-flight statuses) already covers the
--     STEP-4 fan-out's derive_broker_dailies jobs. Both are kind-agnostic in
--     their WHERE clause, so they dedup the new work with zero new indexes — do
--     NOT create duplicates.

-- --------------------------------------------------------------------------
-- STEP 4 — recurring key-mode fan-out. Closes the P115-flagged enqueue gap:
-- allocator per-key derive_broker_dailies was one-shot-at-best (only the
-- approval-gated scripts/phase35_backfill_enqueue ever enqueued it key-scoped);
-- new keys never got a series and existing series never refreshed.
--
-- Mirrors enqueue_refresh_allocator_equity_for_all (20260420213754:314-361):
-- advisory-lock skip, per-key loop, per-key unique_violation swallow. Enqueues
-- kind 'derive_broker_dailies' via the api_key-scoped enqueue_compute_job mode
-- (p_api_key_id set, all other targets NULL — the coherence api_key arm).
--
-- Eligibility predicate — BYTE-MATCHES eligible_key_predicate
-- (allocator_equity_derive.py:187-203) and the phase35 backfill dispatch filter
-- (scripts/phase35_backfill_enqueue.py:79-91), which are documented ROLE-AGNOSTIC
-- (every active connected exchange key). Do NOT invent a different ownership
-- filter:
--     is_active = true
--     AND sync_status IS DISTINCT FROM 'revoked'   -- NULL/anything-but-revoked passes
--     AND disconnected_at IS NULL
-- A credential-revoked / soft-disconnected key keeps is_active=true (rows persist
-- for audit) but is NOT eligible — deriving for it would pin the D3 gate to the
-- honest-empty baseline forever.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION enqueue_derive_broker_dailies_for_allocator_keys()
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_key   RECORD;
  v_today TEXT := to_char(now() AT TIME ZONE 'UTC', 'YYYY-MM-DD');
BEGIN
  -- Advisory lock so concurrent cron fires do not stomp on each other.
  IF NOT pg_try_advisory_lock(hashtext('derive_broker_dailies_key_fanout')) THEN
    RAISE NOTICE 'enqueue_derive_broker_dailies_for_allocator_keys: another run holds the lock; skipping';
    RETURN;
  END IF;

  BEGIN
    FOR v_key IN
      SELECT ak.id AS api_key_id
      FROM api_keys ak
      WHERE ak.is_active = TRUE
        AND ak.sync_status IS DISTINCT FROM 'revoked'
        AND ak.disconnected_at IS NULL
    LOOP
      BEGIN
        PERFORM enqueue_compute_job(
          p_strategy_id     := NULL,
          p_kind            := 'derive_broker_dailies',
          p_idempotency_key := 'derive-dailies-' || v_key.api_key_id::text || '-' || v_today,
          p_api_key_id      := v_key.api_key_id
        );
      EXCEPTION WHEN unique_violation THEN
        NULL; -- already in-flight for this key (per (api_key_id, kind) index); benign
      END;
    END LOOP;
  EXCEPTION WHEN OTHERS THEN
    PERFORM pg_advisory_unlock(hashtext('derive_broker_dailies_key_fanout'));
    RAISE;
  END;

  PERFORM pg_advisory_unlock(hashtext('derive_broker_dailies_key_fanout'));
END;
$$;
