-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260911130000_ledger_fanout_grantees_and_dormancy.sql
-- --------------------------------------------------------------------------
-- STEP 1: the single-key fan-out
-- --------------------------------------------------------------------------
-- Re-based on supabase/schema/functions/enqueue_ledger_refresh_for_strategies.sql
-- (source migration 20260907130000). The four edits enumerated in the RE-BASE
-- DISCIPLINE section above and nothing else; every other line of the body is
-- that snapshot's, byte for byte.
CREATE OR REPLACE FUNCTION public.enqueue_ledger_refresh_for_strategies()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $fanout$
DECLARE
  v_enabled  BOOLEAN;
  v_row      RECORD;
  v_job_id   UUID;
  v_existing INTEGER;
  v_enqueued INTEGER := 0;
  -- ---- the dormancy instrument's locals (164.7 WR-10) --------------------
  -- FOUR, for a dormant branch with THREE causes whose single NOTICE cannot tell
  -- two of them apart. v_found is the row count of the activation read and stays
  -- NULL until that read has actually COMPLETED — ⛔ NULL therefore means NEVER
  -- MEASURED, which is NOT the healthy row-present-and-FALSE case and must never
  -- be folded into it; the cause branch below is written NULL-safely for exactly
  -- that reason. v_read_failed is set by the handler after it has nulled the
  -- flag. v_sqlstate carries the failing read's SQLSTATE OUT of the handler,
  -- which is the only place it is defined — 42P01 (the table is gone), 42501
  -- (the privilege was revoked) and a planner fault are three causes with three
  -- different remediations, and the WARNING that already names it is read by
  -- nobody (APPGUC-WARNING-UNINSTRUMENTED-01, this file's own header). v_cause is
  -- the string the instrument row carries. The cause table is in this file's
  -- header, under WR-10.
  v_found       INTEGER := NULL;
  v_read_failed BOOLEAN := FALSE;
  v_sqlstate    TEXT;
  v_cause       TEXT;
BEGIN
  -- ---- Lock B (D-08, 164.7 D-01): the fail-closed activation switch ------
  -- FIRST statement in the body, deliberately — unchanged from the form this
  -- replaces, and the placement is the point: nothing this function does can
  -- happen before the switch has been read.
  --
  -- WHAT CHANGED. The switch was a database setting in the `app.` namespace;
  -- an operator on this platform is refused 42501 when setting one (MEASURED on
  -- PROD 2026-09-05), so the runbook's activation step could not be performed.
  -- It now reads public.system_flags, which this project has been operating
  -- since April. The column is BOOLEAN NOT NULL, so the old comment's list of
  -- near-misses — '1', 'on', 'TRUE', 'true ' with a trailing space — is no longer
  -- a class that must be REJECTED by an exact comparison; it is a class that
  -- cannot be REPRESENTED. That is the improvement, and it is why no normaliser
  -- and no cast appears anywhere below.
  --
  -- FAIL-CLOSED ON EVERY PATH, which is what the wrapping buys:
  --   * read raises (table dropped, permission denied, planner fault) -> the
  --     handler leaves v_enabled NULL -> dormant;
  --   * NO ROW for this key -> SELECT INTO without STRICT assigns NULL ->
  --     dormant. ⛔ This is the DELIBERATE INVERSE of the missing-row branch in
  --     src/app/api/admin/match/send-intro/route.ts, which treats a missing row
  --     as ENABLED. That is right for a kill switch defaulting ON and wrong
  --     here: this is a dormant-by-default activation switch, so its absent
  --     state must be its closed state. Only that route's error branch and its
  --     enabled=false branch transfer.
  --   * row present and FALSE -> dormant.
  --
  -- ⛔ THE COMPARISON IS NULL-SAFE AND MUST STAY SO. With v_enabled NULL both
  -- `v_enabled <> TRUE` and `NOT v_enabled` evaluate to NULL, the IF is not
  -- taken, and the body falls THROUGH to the fan-out — i.e. those two spellings
  -- open the flag on precisely the failure path this guard exists for.
  --
  -- ⚠️ NOTHING but the assignment goes in the handler. A probe or a second read
  -- inside an EXCEPTION block is the shape lint rule R1 flags in the gate corpus;
  -- keeping it clean at the source is what stops a gate copying the bad shape.
  --
  -- Resetting the row is still the incident-pressure kill switch: the next tick
  -- returns 0 with no schedule operation, no deploy and no migration. It is an
  -- UPDATE an admin session or the service role can already make.
  BEGIN
    SELECT sf.enabled INTO v_enabled
      FROM public.system_flags sf
     WHERE sf.key = 'ledger_refresh_enabled';
    -- The row count of the read that just ran. It is the ONLY thing separating
    -- "there is no such row" from "the row is there and says FALSE" — both leave
    -- the flag with a value that is not TRUE, and both raise the same NOTICE
    -- below. Unreachable when the read RAISED, which is why the handler records
    -- its own cause instead of relying on this.
    GET DIAGNOSTICS v_found = ROW_COUNT;
  EXCEPTION WHEN OTHERS THEN
    RAISE WARNING 'enqueue_ledger_refresh_for_strategies: activation flag read failed (SQLSTATE %); treating as dormant', SQLSTATE;
    v_enabled := NULL;
    -- ⚠️ The note above says NOTHING BUT ASSIGNMENTS go in this handler. Both of
    -- these ARE assignments, and both are deliberately not a probe, a read or a
    -- write: lint rule R1-exception-handler-probe forbids DML and SELECT INTO
    -- here, and an INSERT in a handler is exactly the shape that rule exists to
    -- keep out of the gate corpus. The cause is RECORDED here and WRITTEN below,
    -- on the dormant path, where a write is legal.
    --
    -- ⛔ THE SQLSTATE IS CAPTURED HERE OR NOWHERE — it is defined only inside an
    -- exception handler. The WARNING above already formats it, and this file's
    -- header MEASURES that WARNING as having no consumer: pg_cron keeps no
    -- WARNING output and no prober arm reads the server log. Computing a value
    -- that separates "the table was dropped" from "the privilege was revoked"
    -- from "the planner faulted" and then discarding it leaves all three causes
    -- reporting the same thing, which is the shape this phase exists to remove.
    v_read_failed := TRUE;
    v_sqlstate    := SQLSTATE;
  END;
  IF v_enabled IS DISTINCT FROM TRUE THEN
    RAISE NOTICE 'enqueue_ledger_refresh_for_strategies: dormant (system_flags.ledger_refresh_enabled is not TRUE); enqueued 0';
    -- ---- the dormancy instrument (WR-10, APPGUC-WARNING-UNINSTRUMENTED-01) --
    -- ⛔ IT GOES AFTER THE NOTICE AND NEVER BETWEEN THE GUARD AND IT. Those two
    -- lines are ADJACENT inside one gate-arm `find` string in both ledger gates;
    -- a statement inserted between them makes that find match ZERO times, and
    -- the mutation runner reports occurrence-mismatch — the mutation not
    -- applied, so the arm not tested.
    --
    -- The healthy dormant cause — the row is present and says FALSE — writes
    -- NOTHING, deliberately. It is already legible from the flag row itself, and
    -- no purge of the heartbeat table exists (MEASURED at HEAD), so a row per
    -- function per tick would accrue for the whole pre-activation period to
    -- restate a fact one SELECT already gives. The two causes below are the ones
    -- that are INVISIBLE today: a read that RAISED, and a row that is absent or
    -- unreadable by this definer while the platform believes itself live.
    IF v_read_failed THEN
      v_cause := 'flag_read_failed';
    -- ⛔ `IS DISTINCT FROM 1`, NEVER `= 0`. Control reaches here only when the
    -- read did NOT raise, so v_found holds the count that read produced — unless
    -- the count was never TAKEN, in which case it is still NULL. Under `= 0` a
    -- NULL makes the predicate NULL, the branch is not taken, control falls to
    -- the ELSE, the cause is nulled and NO ROW IS WRITTEN: an UNMEASURED read
    -- would be filed as the healthy row-present-and-FALSE case, silently. That
    -- is the named failure mode of the invariant this whole phase is restoring,
    -- and until check 7b was added the apply-time block COULD NOT catch it:
    -- check 7 asserts only that the instrument INSERT is PRESENT, so deleting
    -- the row-count read above yielded a migration that verified itself green on
    -- the auto-apply-to-PROD route. The NULL-safe form files an unmeasured read
    -- with the other INVISIBLE cause, where it is counted and loud, instead of
    -- with the silent one.
    --
    -- ⭐ AND THE DETECTOR IS BACK, at the apply rather than in the gate. The
    -- NULL-safe form is what made the deletion invisible to the GATES too — the
    -- row now writes under it, so arm M1 no longer reddens (see the A/B below,
    -- which measures exactly that). Check 7b holds needle (5) over the
    -- row-count read itself and REFUSES THE APPLY when the line is gone, which
    -- is the one layer the deletion cannot route around. The trade the M-3 fix
    -- made is therefore paid back rather than merely recorded.
    --
    -- ⭐ A/B MEASURED 2026-09-11 on real pg-lanes, because "it would be silent"
    -- is the kind of claim this repo does not take on argument. Delete the
    -- row-count read one line up and run test_ledger_refresh_fanout.sql: with
    -- this NULL-safe form the instrument still writes its row and the gate is
    -- GREEN at exit 0 (15/15 arms), while with `= 0` in its place the SAME
    -- deletion makes arm M1 report "wrote 0 instrument row(s) ... expected
    -- exactly 1" and the lane exits 3. The gate is therefore NOT blind to the
    -- deletion — it is the apply-time block that is — and the difference this
    -- line buys is that the DECLINE keeps reaching a counted row instead of
    -- going quiet the moment the count stops being taken.
    --
    -- ⚠️ RECORDED, not closed: the label then reads "invisible or absent"
    -- for a state that is really "never measured". Naming it separately would
    -- add a fourth cause no gate arm can reach, and an unfalsifiable branch is
    -- the worse trade — the `sqlstate` key below is NULL on this path and the
    -- row-count read is one line up, which is what tells the two apart on
    -- inspection.
    ELSIF v_found IS DISTINCT FROM 1 THEN
      v_cause := 'flag_row_invisible_or_absent';
    ELSE
      v_cause := NULL;
    END IF;
    IF v_cause IS NOT NULL THEN
      -- ⛔ THE SQLSTATE GOES IN `metadata`, NEVER IN `error`. Both ledger gates'
      -- M2 arms count rows whose `error` is EXACTLY the cause string; appending a
      -- diagnostic there breaks that equality and the arm reddens for a reason
      -- unrelated to what it tests. `metadata` carries NO EQUALITY assertion,
      -- which is what makes it the column a new diagnostic can join without
      -- renegotiating a gate. It is NULL on the invisible-or-absent path, by
      -- construction: there was no exception, so there was no SQLSTATE to read.
      --
      -- ⚠️ AMENDED 2026-09-12 — `metadata` now carries a PRESENCE assertion, and
      -- the distinction from an EQUALITY one is the whole reason it could be
      -- added without renegotiating anything. Both gates' M2 arms narrow their
      -- count to rows whose `metadata->>'sqlstate'` IS NOT NULL. Deleting the
      -- key pair below therefore makes M2 count 0 and redden by name, where
      -- before it was read by nothing: check 7's needle is the INSERT's own
      -- statement shape and SURVIVES the deletion intact, so a tidy-up of this
      -- jsonb_build_object call silently collapsed 42P01, 42501 and a planner
      -- fault back into one undifferentiated cause with every gate green. No
      -- VALUE is pinned — an equality on a SQLSTATE would make the arm depend on
      -- which failure the gate happens to provoke, which is the mistake the
      -- paragraph above refuses for `error`.
      --
      -- ⛔ THE WRITE IS BEST-EFFORT; THE DORMANT RETURN IS THE CONTRACT — a
      -- DECISION, recorded here because the file argues the handler's shape at
      -- length above and was silent at the one place the argument also applies.
      -- Control reaches the flag_read_failed branch BECAUSE a read raised
      -- (42P01, 42501 or a planner fault), and two of those three plausibly
      -- reach this INSERT as well. Unwrapped, the tick on which the instrument
      -- matters MOST is the tick on which this function RAISES: the row rolls
      -- back, the diagnostic is lost anyway, and a fail-closed dormant no-op on
      -- a function slated for a schedule becomes a hard error — an hourly cron
      -- that starts erroring is an incident, which is the exact thing arm L of
      -- both gates exists to refuse one layer up. So the write is wrapped and
      -- the dormancy survives it.
      --
      -- ⭐ A/B MEASURED 2026-09-12 on real pg-lanes, in the one state this whole
      -- decision is about: the activation read raising 42P01 (system_flags
      -- renamed away) AND the instrument's own table gone (cron_runs dropped).
      -- WITH the wrap the function emitted the WARNING below and RETURNED 0.
      -- With the wrap removed and nothing else changed, the SAME probe reported
      -- `the fan-out RAISED (SQLSTATE 42P01)`. The decision is therefore a
      -- measured difference in behaviour, not a preference.
      --
      -- ⚠️ THE WARNING IS NOT THE DETECTOR AND IS NOT CLAIMED AS ONE — this
      -- file's header MEASURES a WARNING as having no consumer. What detects a
      -- silently-failing instrument is both gates' M1/M2 arms, which count the
      -- row inside their own transaction and redden at 0.
      --
      -- ⚠️ R1-exception-handler-probe is not imported by this shape: that rule
      -- governs the GATE corpus (scripts/lint-sql-gates.mjs, CORPUS_DIR =
      -- supabase/tests) and not migration bodies, and this handler holds neither
      -- a probe nor a SELECT INTO — only the RAISE the rule exists to preserve.
      --
      -- ⛔ FORCE ROW LEVEL SECURITY on public.cron_runs IS THE CLAUSE THAT
      -- BREAKS THIS WRITE. The definer is exempt from row security on this table
      -- by OWNERSHIP ALONE (see check 3's derivation: the table carries no FORCE
      -- clause at baseline.sql:9864, and neither policy admits this role), and
      -- FORCE is the one clause under which owning a table stops being an
      -- exemption. Add it at STEP 2b — which is where a future hardener will be
      -- standing — and every dormant-with-cause tick loses its row. Before the
      -- wrap below that was a RAISE; with it, it is a WARNING and a missing row,
      -- which both gates' M1/M2 arms report by name.
      BEGIN
        INSERT INTO public.cron_runs (cron_name, status, completed_at, error, metadata)
        VALUES ('ledger_refresh_fanout', 'error', now(), v_cause,
                jsonb_build_object('function', 'enqueue_ledger_refresh_for_strategies',
                                   'cause', v_cause,
                                   'sqlstate', v_sqlstate));
      EXCEPTION WHEN OTHERS THEN
        RAISE WARNING 'enqueue_ledger_refresh_for_strategies: dormancy instrument write failed (SQLSTATE %); the dormant cause was %', SQLSTATE, v_cause;
      END;
    END IF;
    RETURN 0;
  END IF;

  -- ---- concurrency: one fan-out at a time -------------------------------
  IF NOT pg_try_advisory_lock(hashtext('ledger_refresh_fanout')) THEN
    RAISE NOTICE 'enqueue_ledger_refresh_for_strategies: another run holds the lock; skipping';
    RETURN 0;
  END IF;

  BEGIN
    FOR v_row IN
      WITH candidates AS (
        SELECT
          lrs.strategy_id,
          lrs.last_return_date,
          -- Per-venue partition for the cap. A non-composite row in this view
          -- has exactly one element in `exchanges` (its venue is reached only
          -- through strategies.api_key_id), and the view's WHERE clause makes an
          -- empty array impossible, so element 1 is the venue. No venue literal
          -- is declared here or anywhere else in this file (D-05).
          row_number() OVER (
            PARTITION BY lrs.exchanges[1]
            ORDER BY lrs.last_return_date ASC NULLS FIRST, lrs.strategy_id
          ) AS venue_rank
        FROM public.ledger_refresh_staleness lrs
        JOIN public.strategies s
          ON s.id = lrs.strategy_id
        -- ⛔ LEFT, not INNER, and this is load-bearing. See the header section
        -- "Why the api_keys join is LEFT": under INNER, a composite is dropped by
        -- the join and never reaches the exclusion conjunct below, which would
        -- make that conjunct unfalsifiable.
        LEFT JOIN public.api_keys ak
          ON ak.id = s.api_key_id
        WHERE lrs.is_stale
          -- D-01: composites are excluded, DELIBERATELY and by name. ⛔ This
          -- conjunct is the ONLY exclusion — it is NOT redundant. Every
          -- key-eligibility conjunct above is NULL-TOLERANT, so a composite
          -- (all-NULL `ak.*` under the LEFT join) passes all of them and is
          -- excluded HERE, nowhere else. Deleting it admits every composite.
          -- See the "D-01" section of this file's header. Do not tidy it away.
          AND lrs.is_composite = FALSE
          -- Lifecycle: mirrors ALLOWED_STRATEGY_STATUSES (routers/cron.py:148)
          -- MINUS 'draft'. A draft strategy has no factsheet to refresh, so the
          -- narrower pair is correct here; it is the same pair
          -- enqueue_poll_positions_for_all_strategies already uses
          -- (20260412094449:233-245), so the two recurring strategy fan-outs
          -- agree on what "live enough to re-run" means.
          AND s.status IN ('published', 'pending_review')
          -- Key eligibility — the role-agnostic eligible-key predicate, written
          -- NULL-TOLERANTLY on purpose (header: "Why the api_keys join is LEFT").
          -- These two are already NULL-true.
          AND ak.sync_status IS DISTINCT FROM 'revoked'
          AND ak.disconnected_at IS NULL
          -- This one is not, so it is coalesced. A row with no key at all is not
          -- excluded HERE — it is excluded above, by name, as a composite.
          AND COALESCE(ak.is_active, TRUE)
          -- Attempt cooldown (D-09) — the BINDING bound. Keyed on the prior
          -- ATTEMPT, not the prior success, so a permanently-failing strategy
          -- costs ~1 job/day instead of 24. Both chain hops count: the tail
          -- follows the head automatically, so an analytics job inside the window
          -- means this strategy was already refreshed inside the window.
          AND NOT EXISTS (
                SELECT 1
                  FROM public.compute_jobs cj
                 WHERE cj.strategy_id = lrs.strategy_id
                   AND cj.kind IN ('derive_broker_dailies', 'compute_analytics_from_csv')
                   AND cj.created_at > now() - INTERVAL '20 hours'
              )
          -- In-flight guard. Belt-and-braces over enqueue_compute_job's own
          -- optimistic in-flight lookup and over the partial unique index: this
          -- one also covers a strategy busy with a DIFFERENT kind, which the
          -- per-(strategy,kind) index does not.
          --
          -- ⚠️ 'failed_retry' is INCLUDED deliberately, and this set is therefore
          -- WIDER than the three-status set the RPC's dedupe (20260716090000:259-261)
          -- and the compute_jobs_one_inflight_per_kind_strategy index both use.
          -- `CLAIMABLE_STATUSES = ("pending", "failed_retry")` (job_worker.py:200)
          -- — a failed_retry row is scheduled to be claimed again, so it is
          -- in-flight in every sense that matters here. Neither the RPC nor the
          -- index would stop a second derive landing beside it, and two
          -- concurrent derives for one strategy is exactly what the venue that
          -- serialises on a single shared terminal registry cannot absorb.
          AND NOT EXISTS (
                SELECT 1
                  FROM public.compute_jobs cj2
                 WHERE cj2.strategy_id = lrs.strategy_id
                   AND cj2.status IN ('pending', 'running', 'done_pending_children', 'failed_retry')
              )
      )
      -- ---- the two integers (D-09, CORRECTED). Derivation, in order: ------
      --  (a) One refreshed strategy costs up to 1500 s of worker time, NOT
      --      900 s: derive_broker_dailies (900 s) auto-chains to
      --      compute_analytics_from_csv (600 s) on the same
      --      sequentially-dispatching worker (job_worker.py:488-504, :526).
      --  (b) ⛔ THE BINDING CONSTRAINT IS THE 20-HOUR ATTEMPT COOLDOWN ABOVE,
      --      NOT THIS LIMIT. The cooldown plus the in-flight conjunct cap the
      --      outstanding backlog at the COHORT SIZE, whatever the tick rate.
      --  (c) This LIMIT is a burst / smoothing cap only. It is not what keeps
      --      the worker from saturating; (b) is.
      --  (d) ⛔ The LIMIT must stay STRICTLY GREATER than the per-venue cap, or
      --      the behavioural gate's arm G stops discriminating the cap from the
      --      limit and the cap's own neutering goes green.
      -- Full narrative, including why "n × 900 s < 3600 s ⇒ n = 4" is retracted
      -- on BOTH the cost and the model, is in this file's D-09 header section.
      SELECT c.strategy_id
        FROM candidates c
       WHERE c.venue_rank <= 2
       ORDER BY c.last_return_date ASC NULLS FIRST, c.strategy_id
       LIMIT 4
    LOOP
      BEGIN
        -- ⛔ COUNT INSERTIONS, NOT CALLS. _enqueue_compute_job_internal
        -- (20260716090000:229-300) RETURNS the id of an existing in-flight job
        -- when it finds one (:259-261) and inserts ON CONFLICT DO NOTHING
        -- (:276) — so it never raises, a per-row `unique_violation` handler can
        -- never fire, and a naive `counter := counter + 1` per iteration would
        -- report the number of CALLS. The founder reads this integer back at
        -- activation (docs/runbooks/ledger-refresh-go-live.md), so it must mean
        -- what it says. Same idiom as enqueue_poll_positions_for_all_strategies
        -- (20260412094449:249-268).
        --
        -- ⚠️ [161.1-REVIEW IN-01] What this pre-count actually is, stated
        -- honestly so the next reader does not over-trust it: it is a
        -- RACE-WINDOW BACKSTOP, not the mechanism. The mechanism is the
        -- in-flight conjunct in the candidate CTE above, which excludes any
        -- strategy holding a job in ('pending','running','done_pending_children',
        -- 'failed_retry') for ANY kind — a strict superset of the three statuses
        -- and the one kind queried here. So on the normal path v_existing is 0
        -- for every candidate, and this SELECT changes nothing.
        --
        -- It is still not dead code. The advisory lock serialises fan-out TICKS,
        -- not the API: an externally-committed enqueue for this strategy can
        -- land between the CTE's snapshot and this iteration's fresh READ
        -- COMMITTED snapshot, and then the RPC returns that row's id rather than
        -- inserting. Only in that window does v_existing go non-zero. It can
        -- therefore only UNDERCOUNT, which is the fail-safe direction for a
        -- number a human reads back as "jobs created".
        --
        -- ⛔ No test drives this non-zero deterministically — the window needs a
        -- concurrent committed writer. Do not read a green suite as evidence
        -- that this branch has ever fired.
        SELECT count(*) INTO v_existing
          FROM public.compute_jobs
         WHERE strategy_id = v_row.strategy_id
           AND kind = 'derive_broker_dailies'
           AND status IN ('pending', 'running', 'done_pending_children');

        -- ⛔ p_strategy_id ALONE. enqueue_compute_job enforces exactly-one-of
        -- {p_strategy_id, p_allocator_id, p_api_key_id} and raises 22023
        -- otherwise (20260515210300:330-332; measured on PROD during the A7
        -- tracer). Strategy-mode is also the only mode that stamps
        -- strategy_analytics — see the D-07 header section.
        --
        -- ⚠️ The 'source' value is a CONTRACT, not a label: the non-destructive
        -- failure guard in analytics-service/services/job_worker.py reads it back
        -- off this job row and skips the publish-state downgrade when it matches.
        -- If the two spellings drift, the fan-out still enqueues and the guard
        -- still compiles, and the only symptom is that the next failed refresh
        -- silently un-publishes a funded account. Plan 05 gate 8 pins them.
        v_job_id := enqueue_compute_job(
          p_strategy_id := v_row.strategy_id,
          p_kind        := 'derive_broker_dailies',
          p_metadata    := jsonb_build_object(
                             'source', 'ledger-refresh',
                             'enqueued_at', now()
                           )
        );

        IF v_existing = 0 AND v_job_id IS NOT NULL THEN
          v_enqueued := v_enqueued + 1;
        END IF;
      EXCEPTION WHEN OTHERS THEN
        -- ⛔ Deliberately NOT `WHEN unique_violation`: that condition cannot fire
        -- here (see the counter comment above), and an exception block that
        -- cannot fire is indistinguishable from one that is protecting
        -- something — the next reader preserves it and reasons from it.
        -- Catching OTHERS keeps one poisoned row from aborting the whole tick.
        -- The SQLSTATE is carried; no identifier is (T-161.1-10).
        RAISE WARNING 'enqueue_ledger_refresh_for_strategies: one candidate failed to enqueue (SQLSTATE %); continuing', SQLSTATE;
      END;
    END LOOP;
  EXCEPTION WHEN OTHERS THEN
    -- Release before re-raising, or the session holds the lock until it ends and
    -- every later tick on that session skips. This arm is the part authors drop.
    PERFORM pg_advisory_unlock(hashtext('ledger_refresh_fanout'));
    RAISE;
  END;

  PERFORM pg_advisory_unlock(hashtext('ledger_refresh_fanout'));

  RAISE NOTICE 'enqueue_ledger_refresh_for_strategies: enqueued % refresh job(s) this tick', v_enqueued;
  RETURN v_enqueued;
END;
$fanout$;
