-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260422101911_api_keys_disconnected_at.sql
-- ---------------------------------------------------------------------------
-- STEP 4: worker dispatch — filter disconnected_at IS NULL
-- ---------------------------------------------------------------------------
-- enqueue_poll_allocator_positions_for_all_keys was defined in migration
-- 066 (lines 613–697). Re-create with the one-line filter added.
--
-- Advisory lock + f6 jitter key derivation + unique_violation swallow are
-- preserved verbatim — only the FROM api_keys WHERE clause changes.

CREATE OR REPLACE FUNCTION public.enqueue_poll_allocator_positions_for_all_keys()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_api_key_id      UUID;
  v_enqueued        INTEGER := 0;
  v_job_id          UUID;
  v_jitter          INTERVAL;
  v_run_at          TIMESTAMPTZ;
  v_idempotency_key TEXT;
BEGIN
  IF NOT pg_try_advisory_lock(hashtext('daily_allocator_polling')) THEN
    RETURN 0;
  END IF;

  FOR v_api_key_id IN
    SELECT id FROM api_keys
    WHERE is_active = true
      AND sync_status IS DISTINCT FROM 'revoked'
      AND disconnected_at IS NULL  -- migration 075: skip soft-disconnected
  LOOP
    BEGIN
      v_jitter := (random() * interval '600 seconds');
      v_run_at := now() + v_jitter;
      v_idempotency_key := 'daily-alloc-'
        || to_char(v_run_at AT TIME ZONE 'UTC', 'YYYY-MM-DD')
        || '-' || v_api_key_id::text;
      v_job_id := enqueue_compute_job(
        p_strategy_id     := NULL,
        p_kind            := 'poll_allocator_positions',
        p_api_key_id      := v_api_key_id,
        p_idempotency_key := v_idempotency_key,
        p_run_at          := v_run_at
      );
      v_enqueued := v_enqueued + 1;
    EXCEPTION WHEN unique_violation THEN
      NULL;
    END;
  END LOOP;

  PERFORM pg_advisory_unlock(hashtext('daily_allocator_polling'));
  RETURN v_enqueued;
END;
$$;
