-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260412094449_compute_jobs_admin_and_defer.sql
-- --------------------------------------------------------------------------
-- STEP 4: enqueue_poll_positions_for_all_strategies RPC
-- --------------------------------------------------------------------------
-- Daily fanout helper called by the Railway worker's 24h enqueue loop.
-- Loops strategies that are (a) published or in-review (i.e. not drafts),
-- (b) have a non-null api_key_id, and (c) have had at least one successful
-- sync_trades job in the last 30 days (indicating the key still works).
-- For each qualifying strategy, calls enqueue_compute_job which is
-- idempotent via the partial unique index — a second call within the same
-- day returns the existing in-flight row.
--
-- Returns the number of rows actually enqueued (excludes duplicates that
-- returned existing in-flight jobs). Called exclusively by the worker;
-- REVOKE from all non-service roles.
--
-- The multi-worker race (two workers running the daily loop concurrently)
-- is handled at the worker layer via pg_try_advisory_lock('daily_position_polling').
-- This function is safe to call multiple times — the idempotency of
-- enqueue_compute_job guarantees no duplicate jobs — but advisory locking
-- at the call site saves the unnecessary work.
CREATE OR REPLACE FUNCTION enqueue_poll_positions_for_all_strategies()
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_strategy_id UUID;
  v_exchange TEXT;
  v_enqueued INTEGER := 0;
  v_job_id UUID;
  v_existing_count INTEGER;
BEGIN
  FOR v_strategy_id, v_exchange IN
    SELECT DISTINCT s.id, ak.exchange
      FROM strategies s
      JOIN api_keys ak ON ak.id = s.api_key_id
      WHERE s.api_key_id IS NOT NULL
        AND s.status IN ('published', 'pending_review')
        AND EXISTS (
          SELECT 1 FROM compute_jobs cj
            WHERE cj.strategy_id = s.id
              AND cj.kind = 'sync_trades'
              AND cj.status = 'done'
              AND cj.updated_at > (now() - interval '30 days')
        )
  LOOP
    -- Count pre-existing in-flight poll_positions jobs for this strategy
    -- BEFORE the enqueue call, so we can detect whether enqueue_compute_job
    -- returned an existing id (no new row) vs created a new one.
    SELECT count(*) INTO v_existing_count
      FROM compute_jobs
      WHERE strategy_id = v_strategy_id
        AND kind = 'poll_positions'
        AND status IN ('pending', 'running', 'done_pending_children');

    v_job_id := enqueue_compute_job(
      v_strategy_id,
      'poll_positions',
      'daily-poll-' || to_char(now(), 'YYYY-MM-DD') || '-' || v_strategy_id::text,
      '{}'::UUID[],
      v_exchange,
      jsonb_build_object('enqueued_by', 'daily_loop', 'enqueued_at', now())
    );

    IF v_existing_count = 0 AND v_job_id IS NOT NULL THEN
      v_enqueued := v_enqueued + 1;
    END IF;
  END LOOP;

  RETURN v_enqueued;
END;
$$;
