-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260418074935_bridge_outcome_cron.sql
-- --------------------------------------------------------------------------
-- STEP 3: helper — extract_estimated
-- --------------------------------------------------------------------------
-- Returns the estimated delta (in bps) and days elapsed for the partial
-- in-window period between anchor and the most recent entry in the series.
-- Only returns a row when days_elapsed is between 1 and 29 inclusive.
-- Realized windows (30/90/180d) take over via extract_delta beyond day 29.
CREATE OR REPLACE FUNCTION public.extract_estimated(
  series JSONB,
  anchor DATE
) RETURNS TABLE(bps NUMERIC, days INT)
LANGUAGE plpgsql
STABLE
AS $$
DECLARE
  last_entry RECORD;
  last_date DATE;
  last_value NUMERIC;
  anchor_value NUMERIC;
  days_elapsed INT;
BEGIN
  IF series IS NULL OR jsonb_array_length(series) = 0 THEN
    RETURN;
  END IF;

  anchor_value := public.extract_equity_at(series, anchor);
  IF anchor_value IS NULL THEN
    RETURN;
  END IF;

  -- Most recent entry in the series
  SELECT
    (entry->>'date')::DATE AS d,
    (entry->>'value')::NUMERIC AS v
  INTO last_entry
  FROM jsonb_array_elements(series) AS entry
  ORDER BY (entry->>'date')::DATE DESC
  LIMIT 1;

  last_date := last_entry.d;
  last_value := last_entry.v;
  days_elapsed := (last_date - anchor);

  -- Only return an estimate when we have between 1 and 29 days of data since
  -- anchor. Realized windows (30/90/180) take over via extract_delta.
  IF days_elapsed < 1 OR days_elapsed > 29 THEN
    RETURN;
  END IF;

  IF last_value IS NULL OR last_value = 0 THEN
    RETURN;
  END IF;

  bps := ((last_value / anchor_value) - 1) * 10000;
  days := days_elapsed;
  RETURN NEXT;
END;
$$;
