-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260819120000_csv_finalize_atomic_fold.sql
-- ==========================================================================
-- STEP 1 — the folded function
-- ==========================================================================
CREATE FUNCTION public.finalize_csv_strategy_with_returns(
  p_user_id           UUID,
  p_wizard_session_id UUID,
  p_fmt               TEXT,
  p_strategy_name     TEXT,
  p_rows              JSONB,
  p_terminal_status   TEXT DEFAULT 'pending_review'
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_auth_uid     UUID := auth.uid();
  v_strategy_id  UUID;
BEGIN
  -- CONTRIB-02 guard (T-110-02, D-08): restrict the terminal status;
  -- 'published' is unreachable from any finalize caller. FIRST statement so it
  -- RAISEs before any write (parent: 20260728120000:215-219, verbatim; only
  -- the function name in the message changed).
  IF p_terminal_status NOT IN ('pending_review', 'private') THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns: p_terminal_status % is not allowed (expected pending_review or private)',
      p_terminal_status
      USING ERRCODE = '22023';
  END IF;

  -- Caller-identity guards (parent: 20260728120000:225-234). The route layer
  -- calls with the authenticated user's id; we assert it matches the JWT so a
  -- SECURITY DEFINER RPC can't be abused via service_role to write rows under
  -- another user. persist's identical pair (20260522111839:127-136) is folded
  -- into this single copy. The message literal below is pinned by
  -- supabase/tests/test_csv_finalize_auth_guard.sql Part A — change both
  -- together or not at all.
  IF v_auth_uid IS NULL THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns called without an auth session'
      USING ERRCODE = '42501';
  END IF;

  IF v_auth_uid <> p_user_id THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns: p_user_id (%) does not match auth.uid (%)',
      p_user_id, v_auth_uid
      USING ERRCODE = '42501';
  END IF;

  -- Format whitelist (parent: 20260728120000:237-240, verbatim).
  IF p_fmt NOT IN ('daily_returns','daily_nav','trades') THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns: invalid fmt %', p_fmt
      USING ERRCODE = '22023';
  END IF;

  -- Strategy-name guards (parent: 20260728120000:248-256, verbatim): 1-80
  -- chars, two raises with distinguishing substrings so tests can pin each
  -- separately from the fmt guard.
  IF p_strategy_name IS NULL OR length(p_strategy_name) = 0 THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns: p_strategy_name is required'
      USING ERRCODE = '22023';
  END IF;

  IF length(p_strategy_name) > 80 THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns: p_strategy_name exceeds 80 characters'
      USING ERRCODE = '22023';
  END IF;

  -- Rows type guard (parent: 20260522111839:153-155, verbatim): p_rows MUST
  -- be an array before jsonb_array_length is called on it.
  IF jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns: p_rows must be a JSONB array, got %', jsonb_typeof(p_rows)
      USING ERRCODE = '22023';
  END IF;

  -- Row-count cap (parent: 20260522111839:160-162, verbatim): the route
  -- validator also enforces <=5000 upstream; this is defense-in-depth so a
  -- direct RPC caller cannot insert an unbounded series.
  IF jsonb_array_length(p_rows) > 5000 THEN
    RAISE EXCEPTION 'finalize_csv_strategy_with_returns: p_rows exceeds 5000 rows (got %)', jsonb_array_length(p_rows)
      USING ERRCODE = '22023';
  END IF;

  -- NOTE the parents' empty-array raise is deliberately ABSENT here: an empty
  -- array is the legitimate fmt='trades' no-series case (route.ts:521's skip,
  -- moved into this body as the length gate on the dailies INSERT below).

  -- Insert the strategies row (parent: 20260728120000:278-288, column list
  -- EXACT). source='csv' marks the ingestion path; status=p_terminal_status
  -- ('pending_review' manager flow, 'private' CONTRIB-02 contribution flow).
  -- wizard_session_id is WRITTEN here (Phase 140.4 / SEAMRIM-03): this single
  -- column write is what makes the partial index
  -- strategies_user_wizard_session_source_uniq bite. A double submit raises
  -- 23505 on this INSERT, and because this body has no handler clause the
  -- raise aborts the function: NOTHING below (or above) survives.
  INSERT INTO strategies (
    user_id, name, status, source,
    strategy_types, subtypes, markets, supported_exchanges,
    wizard_session_id
  )
  VALUES (
    p_user_id, p_strategy_name, p_terminal_status, 'csv',
    '{}', '{}', '{}', '{}'::text[],
    p_wizard_session_id
  )
  RETURNING id INTO v_strategy_id;

  -- Insert the verification row (parent: 20260728120000:299-305, verbatim).
  -- FK ordering note preserved from the parent (:295-298): PostgreSQL allows
  -- the strategy_verifications.strategy_id FK to reference the just-inserted
  -- strategy because both inserts run in the same transaction (the SECURITY
  -- DEFINER function body is implicitly transactional). The FK check happens
  -- at COMMIT, not at the second INSERT.
  INSERT INTO strategy_verifications (
    strategy_id, wizard_session_id, status, trust_tier, flow_type, source,
    errors, correlation_id
  ) VALUES (
    v_strategy_id, p_wizard_session_id, 'validated', 'csv_uploaded', 'csv', 'csv',
    NULL, NULL
  );

  -- The dailies write (parent: 20260522111839:173-181, ADAPTED per the header
  -- delta list): length-gated (trades no-series case), plain INSERT (a fresh
  -- strategy id cannot conflict; duplicate dates are a route-boundary 400),
  -- and written against the 20260624120000 shape — naming exactly
  -- (strategy_id, date, daily_return) leaves api_key_id/allocator_id NULL,
  -- which satisfies the csv_daily_returns_source_xor CHECK; the
  -- owner-coherence trigger is gated WHEN api_key_id IS NOT NULL and never
  -- fires for these rows. A malformed element (date or daily_return cast
  -- failure) raises here and rolls back ALL THREE inserts — that rollback IS
  -- the SC#2 mechanism.
  IF jsonb_array_length(p_rows) > 0 THEN
    INSERT INTO csv_daily_returns (strategy_id, date, daily_return)
    SELECT
      v_strategy_id,
      (elem->>'date')::DATE,
      (elem->>'daily_return')::DOUBLE PRECISION
    FROM jsonb_array_elements(p_rows) elem;
  END IF;

  RETURN v_strategy_id;
END;
$$;
