-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260501055202_strategy_verifications.sql
-- ==========================================================================
-- STEP 5: finalize_csv_strategy RPC (sibling per D-02; SECURITY DEFINER)
-- ==========================================================================
-- RPC param resolution note (Phase 15 WARNING fix from checker iteration 1):
-- No overload exists for finalize_csv_strategy; PostgREST resolves by named
-- argument matching, NOT by positional argument order. The order of
-- (p_user_id, p_wizard_session_id, p_fmt, p_strategy_name) below is
-- documentation only — at call time, the Next.js route in plan 15-05
-- passes a JSON object whose keys match these parameter names, and
-- PostgREST routes by key. Reordering the SQL signature would NOT break
-- existing callers; renaming any parameter WOULD. Do not rename.
--
-- Cross-AI revision 2026-04-30: parameter is `p_strategy_name`. The user
-- types the name on the Upload step; the route forwards it; this RPC
-- writes it to strategies.name.
--
-- Pattern: copy the structure of create_wizard_strategy at
-- supabase/migrations/20260411103316_wizard_source_column.sql:118-186 (atomic two-table
-- insert with SECURITY DEFINER + manual auth.uid() guard) but adapt for the
-- CSV path: no api_keys insert; instead an immediate strategy_verifications
-- insert at status='validated', trust_tier='csv_uploaded'.
CREATE OR REPLACE FUNCTION public.finalize_csv_strategy(
  p_user_id            UUID,
  p_wizard_session_id  UUID,
  p_fmt                TEXT,
  p_strategy_name      TEXT
)
RETURNS UUID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_auth_uid     UUID := auth.uid();
  v_strategy_id  UUID;
BEGIN
  -- Caller-identity guard (mirrors create_wizard_strategy:140-153):
  -- the route layer calls with the authenticated user's id; we assert
  -- it matches the JWT so a SECURITY DEFINER RPC can't be abused via
  -- service_role to write rows under another user.
  IF v_auth_uid IS NULL THEN
    RAISE EXCEPTION 'finalize_csv_strategy called without an auth session'
      USING ERRCODE = '42501';
  END IF;

  IF v_auth_uid <> p_user_id THEN
    RAISE EXCEPTION 'finalize_csv_strategy: p_user_id (%) does not match auth.uid (%)',
      p_user_id, v_auth_uid
      USING ERRCODE = '42501';
  END IF;

  -- Format whitelist (mirrors the analytics service envelope contract).
  IF p_fmt NOT IN ('daily_returns','daily_nav','trades') THEN
    RAISE EXCEPTION 'finalize_csv_strategy: invalid fmt %', p_fmt
      USING ERRCODE = '22023';
  END IF;

  -- Strategy-name guard — the user typed it on the Upload step. We
  -- enforce 1–80 chars matching the UI-SPEC contract; the route layer
  -- also validates, but defense-in-depth lives here so a service-role
  -- caller cannot bypass the limit. Empty / oversize / NULL all reject
  -- under SQLSTATE 22023 with a distinguishing message substring so
  -- plan 15-06 tests can pin the guard separately from the fmt guard.
  IF p_strategy_name IS NULL OR length(p_strategy_name) = 0 THEN
    RAISE EXCEPTION 'finalize_csv_strategy: p_strategy_name is required'
      USING ERRCODE = '22023';
  END IF;

  IF length(p_strategy_name) > 80 THEN
    RAISE EXCEPTION 'finalize_csv_strategy: p_strategy_name exceeds 80 characters'
      USING ERRCODE = '22023';
  END IF;

  -- Insert the strategies row. source='csv' marks the row's ingestion
  -- path; status='pending_review' matches finalize_wizard_strategy's
  -- post-promotion state so downstream queries (strategy_grid,
  -- /strategies/[id]) treat CSV strategies the same as API strategies
  -- once they reach this terminal state. supported_exchanges is empty
  -- because CSV strategies have no broker linkage. strategy_types /
  -- subtypes / markets default empty per Phase 15 v0; Phase 17 metadata
  -- step (deferred) will populate.
  INSERT INTO strategies (
    user_id, name, status, source,
    strategy_types, subtypes, markets, supported_exchanges
  )
  VALUES (
    p_user_id, p_strategy_name, 'pending_review', 'csv',
    '{}', '{}', '{}', '{}'::text[]
  )
  RETURNING id INTO v_strategy_id;

  -- Insert the verification row at status='validated', trust_tier='csv_uploaded'.
  -- Phase 16 / OBSERV-06 will populate correlation_id; we leave NULL.
  -- FK ordering note: PostgreSQL allows the strategy_verifications.strategy_id
  -- FK to reference the just-inserted strategy because both inserts run in
  -- the same transaction (the SECURITY DEFINER function body is implicitly
  -- transactional). The FK check happens at COMMIT, not at the second INSERT.
  INSERT INTO strategy_verifications (
    strategy_id, wizard_session_id, status, trust_tier, flow_type, source,
    errors, correlation_id
  ) VALUES (
    v_strategy_id, p_wizard_session_id, 'validated', 'csv_uploaded', 'csv', 'csv',
    NULL, NULL
  );

  RETURN v_strategy_id;
END;
$$;
