-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260412094449_compute_jobs_admin_and_defer.sql
-- --------------------------------------------------------------------------
-- STEP 5: get_admin_compute_jobs RPC
-- --------------------------------------------------------------------------
-- Admin-gated read path over compute_jobs_admin. Gates on profiles.is_admin
-- (NOT profiles.role — role is manager|allocator|both per 001:12, is_admin
-- is the actual admin flag per 011:19 + src/lib/admin.ts::isAdminUser).
--
-- Returns un-redacted last_error (unlike get_user_compute_jobs which NULLs
-- it). The admin UI needs raw error strings to debug failing jobs.
--
-- Non-admin callers get an empty result set (not an exception, matching
-- the get_user_compute_jobs shape for the no-auth case). The calling API
-- route must also perform an isAdminUser check before invoking this — the
-- RPC gate is defense in depth.
CREATE OR REPLACE FUNCTION get_admin_compute_jobs(
  p_limit  INTEGER DEFAULT 50,
  p_offset INTEGER DEFAULT 0,
  p_status TEXT    DEFAULT NULL,
  p_kind   TEXT    DEFAULT NULL,
  p_exchange TEXT  DEFAULT NULL
)
RETURNS TABLE(
  id               UUID,
  strategy_id      UUID,
  portfolio_id     UUID,
  kind             TEXT,
  status           TEXT,
  attempts         INTEGER,
  max_attempts     INTEGER,
  next_attempt_at  TIMESTAMPTZ,
  claimed_at       TIMESTAMPTZ,
  claimed_by       TEXT,
  last_error       TEXT,
  error_kind       TEXT,
  idempotency_key  TEXT,
  exchange         TEXT,
  trade_count      INTEGER,
  created_at       TIMESTAMPTZ,
  updated_at       TIMESTAMPTZ,
  metadata         JSONB,
  strategy_name    TEXT,
  portfolio_name   TEXT,
  user_email       TEXT
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
STABLE
AS $$
DECLARE
  v_is_admin BOOLEAN;
  v_effective_limit INTEGER;
  v_effective_offset INTEGER;
BEGIN
  -- Admin gate: EXISTS check on profiles.is_admin, matches migration 011
  -- pattern verbatim.
  SELECT COALESCE(
    (SELECT is_admin FROM profiles WHERE id = auth.uid() LIMIT 1),
    false
  ) INTO v_is_admin;

  IF NOT v_is_admin THEN
    RETURN;
  END IF;

  -- Clamp limit + offset to safe ranges.
  v_effective_limit := GREATEST(1, LEAST(COALESCE(p_limit, 50), 500));
  v_effective_offset := GREATEST(0, COALESCE(p_offset, 0));

  RETURN QUERY
  SELECT
    v.id, v.strategy_id, v.portfolio_id, v.kind, v.status,
    v.attempts, v.max_attempts, v.next_attempt_at,
    v.claimed_at, v.claimed_by,
    v.last_error, v.error_kind, v.idempotency_key,
    v.exchange, v.trade_count, v.created_at, v.updated_at, v.metadata,
    v.strategy_name, v.portfolio_name, v.user_email
  FROM compute_jobs_admin v
  WHERE (p_status IS NULL OR v.status = p_status)
    AND (p_kind IS NULL OR v.kind = p_kind)
    AND (p_exchange IS NULL OR v.exchange = p_exchange)
  ORDER BY v.created_at DESC
  LIMIT v_effective_limit
  OFFSET v_effective_offset;
END;
$$;
