-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260622120000_scenario_shares_and_read_rpc.sql
-- --------------------------------------------------------------------------
-- STEP 2: get_shared_scenario(p_token_hash) — the leak-scoped read RPC
-- --------------------------------------------------------------------------
-- Returns ONLY name/draft/schema_version + the addedStrategies[].id-scoped
-- PUBLISHED strategy series. EXPLICIT 4-column list (never SELECT *). Never
-- joins api_keys / portfolios / portfolio_strategies; never resolves holdings
-- refs ("holding:..."). The UUID-shape filter drops holdings refs and poison.
CREATE FUNCTION public.get_shared_scenario(p_token_hash TEXT)
RETURNS TABLE (
  name           TEXT,
  draft          JSONB,
  schema_version INT,
  series         JSONB           -- [{ "strategy_id": uuid, "daily_returns": [...] }]
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_temp     -- read-path canon (mig 87 H-B), NOT pg_catalog
AS $$
DECLARE
  v_scenario  scenarios%ROWTYPE;
  v_added_ids UUID[];
BEGIN
  -- Defensive input guard: a NULL/empty hash can never match.
  IF p_token_hash IS NULL OR length(p_token_hash) = 0 THEN
    RETURN;
  END IF;

  -- Gate: active (non-revoked) share only. Not found → RETURN (0 rows) → the
  -- page notFound()s. An unknown, a revoked, and a cross-tenant token all take
  -- this same exit — no oracle distinguishing "revoked" from "never existed".
  SELECT s.* INTO v_scenario
    FROM scenario_shares sh
    JOIN scenarios s ON s.id = sh.scenario_id
   WHERE sh.token_hash = p_token_hash
     AND sh.revoked_at IS NULL;
  IF NOT FOUND THEN
    RETURN;
  END IF;

  -- Extract ONLY the added-strategy UUIDs from the draft snapshot. Holdings
  -- refs ("holding:{venue}:{symbol}:{type}") are deliberately NOT resolved —
  -- they are the allocator's LIVE BOOK. The UUID-shape filter keeps only
  -- strategies.id-shaped values and drops poison/holdings/unknown ref classes.
  SELECT array_agg((elem->>'id')::uuid)
    INTO v_added_ids
    FROM jsonb_array_elements(COALESCE(v_scenario.draft->'addedStrategies', '[]'::jsonb)) elem
   WHERE (elem->>'id') ~ '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$';

  RETURN QUERY
  SELECT v_scenario.name,
         v_scenario.draft,
         v_scenario.schema_version,
         COALESCE(
           (SELECT jsonb_agg(jsonb_build_object(
                     'strategy_id', sa.strategy_id,
                     'daily_returns', sa.daily_returns))
              FROM strategy_analytics sa
              JOIN strategies st ON st.id = sa.strategy_id
             WHERE sa.strategy_id = ANY(COALESCE(v_added_ids, '{}'::uuid[]))
               AND st.status = 'published'),   -- published-only; never owned-but-unpublished
           '[]'::jsonb);
END;
$$;
