-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260409003234_recommendations_rpc.sql
-- Migration 019: recommendations SECURITY DEFINER RPCs
--
-- Replaces the admin-client-from-the-page pattern in
-- src/app/(dashboard)/recommendations/page.tsx with SECURITY DEFINER
-- functions that enforce the allocator scope in SQL, not TypeScript.
--
-- Why: the current page uses createAdminClient() to bypass RLS on
-- match_batches + match_candidates and then filters by allocator_id /
-- batch.id. That's safe today -- but a future PR introducing shared
-- batches or a debug param could leak another allocator's
-- recommendations. Moving the scope check into SQL means the front-end
-- can't accidentally bypass it.
--
-- Two functions ship in this migration:
--
--   1. get_allocator_latest_batch_meta(p_allocator_id) -- returns one
--      row (or zero rows) with the latest match_batch id + computed_at +
--      candidate_count. The page uses this to distinguish "no batch yet"
--      from "batch with no ranked candidates".
--
--   2. get_allocator_recommendations(p_allocator_id) -- returns up to 3
--      ranked candidates for the latest batch, joined with strategy,
--      analytics, and discovery category metadata.
--
-- Both functions enforce the same access gate: auth.uid() must match
-- p_allocator_id OR profiles.is_admin must be true for the caller.
-- Non-matching callers get an empty result set, not an error.
--
-- Access: EXECUTE granted to authenticated only. REVOKE FROM PUBLIC and
-- anon so unauthenticated callers get a permission denied.
--
-- Pattern: mirrors latest_cron_success() from migration 013.
--
-- Post-merge manual verification (repeat for both RPCs):
--
--   1. As authenticated user matching the allocator_id:
--        SELECT * FROM get_allocator_recommendations('<your-user-id>'::uuid);
--        SELECT * FROM get_allocator_latest_batch_meta('<your-user-id>'::uuid);
--      Expected: returns up to 3 rows / 1 row.
--
--   2. As a different authenticated user (not the allocator, not admin):
--        SELECT * FROM get_allocator_recommendations('<other-user-id>'::uuid);
--        SELECT * FROM get_allocator_latest_batch_meta('<other-user-id>'::uuid);
--      Expected: returns 0 rows (not an error).
--
--   3. As admin:
--        SELECT * FROM get_allocator_recommendations('<any-user-id>'::uuid);
--        SELECT * FROM get_allocator_latest_batch_meta('<any-user-id>'::uuid);
--      Expected: returns up to 3 rows / 1 row for any allocator.
--
--   4. Unauthenticated (anon):
--      The GRANT is to authenticated only, so anon cannot even call the
--      functions (permission denied from REVOKE FROM anon).

------------------------------------------------------------------
-- 1. get_allocator_latest_batch_meta
------------------------------------------------------------------
CREATE OR REPLACE FUNCTION get_allocator_latest_batch_meta(p_allocator_id UUID)
RETURNS TABLE (
  batch_id UUID,
  computed_at TIMESTAMPTZ,
  candidate_count INT
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin BOOLEAN;
BEGIN
  IF auth.uid() IS NULL THEN
    RETURN;
  END IF;

  IF auth.uid() <> p_allocator_id THEN
    SELECT COALESCE(p.is_admin, false) INTO v_is_admin
    FROM profiles p
    WHERE p.id = auth.uid();
    IF NOT COALESCE(v_is_admin, false) THEN
      RETURN;
    END IF;
  END IF;

  RETURN QUERY
  SELECT
    mb.id AS batch_id,
    mb.computed_at,
    mb.candidate_count
  FROM match_batches mb
  WHERE mb.allocator_id = p_allocator_id
  ORDER BY mb.computed_at DESC
  LIMIT 1;
END;
$$;
