-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260409003234_recommendations_rpc.sql
------------------------------------------------------------------
-- 2. get_allocator_recommendations
------------------------------------------------------------------

CREATE OR REPLACE FUNCTION get_allocator_recommendations(p_allocator_id UUID)
RETURNS TABLE (
  id UUID,
  strategy_id UUID,
  rank INT,
  score NUMERIC,
  reasons TEXT[],
  strategy_name TEXT,
  strategy_description TEXT,
  discovery_category_slug TEXT,
  cagr NUMERIC,
  sharpe NUMERIC,
  max_drawdown NUMERIC,
  analytics_computed_at TIMESTAMPTZ
)
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_is_admin BOOLEAN;
  v_batch_id UUID;
BEGIN
  -- Require authenticated caller.
  IF auth.uid() IS NULL THEN
    RETURN;
  END IF;

  -- Allow: caller is the allocator, OR caller is an admin.
  IF auth.uid() <> p_allocator_id THEN
    SELECT COALESCE(p.is_admin, false) INTO v_is_admin
    FROM profiles p
    WHERE p.id = auth.uid();
    IF NOT COALESCE(v_is_admin, false) THEN
      RETURN;
    END IF;
  END IF;

  -- Find the latest match_batch for this allocator.
  SELECT mb.id INTO v_batch_id
  FROM match_batches mb
  WHERE mb.allocator_id = p_allocator_id
  ORDER BY mb.computed_at DESC
  LIMIT 1;

  IF v_batch_id IS NULL THEN
    RETURN;
  END IF;

  -- Return the top 3 candidates joined with strategy + analytics data.
  -- strategy_analytics columns are declared DECIMAL in 001_initial_schema,
  -- which is an alias for NUMERIC so they implicitly match the return
  -- table. Cast rank to INT explicitly for type safety against future
  -- schema drift.
  RETURN QUERY
  SELECT
    mc.id,
    mc.strategy_id,
    mc.rank::INT,
    mc.score,
    mc.reasons,
    s.name AS strategy_name,
    s.description AS strategy_description,
    dc.slug AS discovery_category_slug,
    sa.cagr,
    sa.sharpe,
    sa.max_drawdown,
    sa.computed_at AS analytics_computed_at
  FROM match_candidates mc
  JOIN strategies s ON s.id = mc.strategy_id
  LEFT JOIN discovery_categories dc ON dc.id = s.category_id
  LEFT JOIN strategy_analytics sa ON sa.strategy_id = s.id
  WHERE mc.batch_id = v_batch_id
    AND mc.rank IS NOT NULL
  ORDER BY mc.rank ASC
  LIMIT 3;
END;
$$;
