-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260719140000_get_published_trust_signals.sql
-- ==========================================================================
-- STEP 1: get_published_trust_signals — the public trust-signal primitive
-- ==========================================================================
-- Column-scoped by RETURNS TABLE: the ONLY columns that can leave the function
-- are (strategy_id, trust_tier, status). All source columns are alias-qualified
-- (sv. / s.) so the OUT-parameter names never shadow a source column.
CREATE OR REPLACE FUNCTION public.get_published_trust_signals(p_strategy_ids uuid[])
RETURNS TABLE (strategy_id uuid, trust_tier text, status text)
LANGUAGE sql
SECURITY DEFINER
SET search_path = public, pg_temp
STABLE
AS $$
  SELECT DISTINCT ON (sv.strategy_id)
         sv.strategy_id,
         sv.trust_tier,
         sv.status
    FROM public.strategy_verifications sv
    JOIN public.strategies s ON s.id = sv.strategy_id
   WHERE s.status = 'published'
     AND sv.strategy_id = ANY(p_strategy_ids)
   ORDER BY sv.strategy_id, sv.created_at DESC;
$$;
