-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260716131000_guard_strategies_publish_transition.sql
-- SECURITY INVOKER (default): current_user at trigger time reflects the effective
-- role of the statement that fired it — 'authenticated' for a direct end-user
-- write, the function owner for a SECURITY DEFINER RPC body, 'service_role' for
-- the admin route's service client. Only the first is blocked.
CREATE OR REPLACE FUNCTION public.guard_strategies_publish_transition()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
BEGIN
  -- Only guard the transition INTO 'published'. On UPDATE, an already-published
  -- row being edited (OLD.status = 'published') is untouched, so owners/admins
  -- can still update other columns on a published strategy. On INSERT there is
  -- no OLD row, so any inserted 'published' row is a fresh transition.
  IF NEW.status = 'published'
     AND (TG_OP = 'INSERT' OR OLD.status IS DISTINCT FROM 'published') THEN
    IF current_user = 'authenticated' THEN
      RAISE EXCEPTION
        'Direct publish of strategy % blocked. Strategies reach status=published '
        'only through the admin review route.', NEW.id
        USING ERRCODE = 'insufficient_privilege';
    END IF;
  END IF;
  RETURN NEW;
END;
$$;
