-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260409212457_fix_organization_rls_recursion.sql
-- 026_fix_organization_rls_recursion.sql
--
-- Fix infinite recursion in organization RLS policies that surfaced during QA
-- on 2026-04-09. Migration 006 wrote the org membership lookup as an inline
-- subquery against `organization_members` inside its own RLS policies. That
-- recurses forever: every nested SELECT re-triggers the same policy. The
-- cascade hits `strategies_org_read`, which joins `organization_members`, so
-- every strategies SELECT fails with:
--
--   ERROR: infinite recursion detected in policy for relation "organization_members"
--
-- The bug was latent since migration 006 because the CI tests never hit the
-- authenticated strategies fetch path (no Crypto SMA browse test while logged
-- in as the demo allocator). Shipped demo data surfaced it immediately.
--
-- Fix: wrap the membership lookup in SECURITY DEFINER helper functions that
-- bypass RLS on `organization_members` for the lookup itself. This is the
-- standard Postgres pattern for breaking RLS recursion (see Supabase docs on
-- "avoiding infinite recursion in RLS policies").

-- ---------------------------------------------------------------
-- SECURITY DEFINER helpers
-- ---------------------------------------------------------------

CREATE OR REPLACE FUNCTION public.is_org_member(org_id UUID)
RETURNS BOOLEAN
LANGUAGE SQL
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.organization_members
    WHERE organization_id = org_id
      AND user_id = auth.uid()
  );
$$;
