-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260825120000_ledger_refresh_staleness_view.sql
-- --------------------------------------------------------------------------
-- STEP 1: the fail-toward-stale date parser
-- --------------------------------------------------------------------------
-- `returns_series` is JSONB written by the analytics runners; a corrupted or
-- hand-edited element must never break the view for every other reader
-- (T-161.1-04). The view pattern-filters elements before calling this, but a
-- regex is NOT sufficient on its own and the difference is not theoretical:
-- '2026-02-31' matches a four-two-two digit pattern exactly and still raises
-- (SQLSTATE 22008, measured). Only a guarded cast actually delivers "a garbage
-- element must not raise".
--
-- Returning NULL on a bad element drops it from the `max()`, which can only make
-- a row look STALER, never fresher. The two trapped conditions are named
-- explicitly rather than `WHEN others` so this can never swallow a query cancel,
-- an out-of-memory, or a permission error.
--
-- No caller-supplied trust surface: SECURITY INVOKER (the default), reads no
-- table, and is revoked from every non-service role.
CREATE OR REPLACE FUNCTION public.ledger_refresh_parse_series_date(p_text TEXT)
RETURNS DATE
LANGUAGE plpgsql
-- STABLE, not IMMUTABLE: `text::date` is DateStyle-dependent, so this is not a
-- pure function of its input and cannot honestly promise immutability. Today the
-- sole caller pre-filters with ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ and ISO-8601 parses
-- YMD regardless of DateStyle, so nothing is broken — but the function is
-- GRANT EXECUTE-ed to service_role, and a future second caller or an expression
-- index built on it would inherit an unsound promise. STABLE still permits
-- everything the current per-row LATERAL does.
STABLE
STRICT
SET search_path = public, pg_catalog
AS $$
BEGIN
  RETURN p_text::date;
EXCEPTION
  WHEN invalid_datetime_format OR datetime_field_overflow THEN
    RETURN NULL;
END;
$$;
