-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260421154030_compute_bridge_outcome_deltas_holding_branch.sql
-- --------------------------------------------------------------------------
-- STEP 2: Helper — parse_holding_ref
-- --------------------------------------------------------------------------
-- Splits "holding:{venue}:{symbol}:{holding_type}" into a typed row.
-- Strips the "holding:" prefix (8 chars; substring starts at position 9).
-- Returns EMPTY (no RETURN NEXT) when:
--   - p_ref IS NULL
--   - p_ref does not start with 'holding:'
--   - the remainder does not split into exactly 3 colon-delimited parts
-- RETURNS NEXT only on valid 3-part holding refs.
CREATE OR REPLACE FUNCTION public.parse_holding_ref(
  p_ref TEXT
) RETURNS TABLE(venue TEXT, symbol TEXT, holding_type TEXT)
LANGUAGE plpgsql
IMMUTABLE
PARALLEL SAFE
AS $$
DECLARE
  v_parts TEXT[];
BEGIN
  -- Reject NULL or missing prefix
  IF p_ref IS NULL OR p_ref NOT LIKE 'holding:%' THEN
    RETURN;
  END IF;

  -- Strip 'holding:' prefix (8 chars) and split on ':'
  v_parts := string_to_array(substring(p_ref FROM 9), ':');

  -- Require exactly 3 parts: venue, symbol, holding_type
  IF array_length(v_parts, 1) != 3 THEN
    RETURN;
  END IF;

  venue        := v_parts[1];
  symbol       := v_parts[2];
  holding_type := v_parts[3];
  RETURN NEXT;
END;
$$;
