-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260522111839_csv_daily_returns.sql
-- NOTE: No INSERT/UPDATE/DELETE policy for authenticated — the
-- persist_csv_daily_returns RPC (STEP 3) writes rows via definer-rights,
-- which bypasses RLS while enforcing auth.uid() = p_user_id + strategy
-- ownership manually.

-- ==========================================================================
-- STEP 3: persist_csv_daily_returns definer-rights RPC
--
-- Called from the Next.js csv-finalize route after applyCsvMetadataUpdate.
-- p_rows is a JSONB array of {date: 'YYYY-MM-DD', daily_return: number}.
-- Returns the count of rows upserted.
--
-- ERRCODE map (canonical interface for downstream TS code):
--   22023 — p_rows not an array, or empty, or > 5000 rows
--   42501 — caller not authenticated, or p_user_id mismatch, or strategy not
--           accessible (probe-oracle closed: missing OR not-owned both → 42501)
--   23505 — UNIQUE (strategy_id, date) violation (guarded upstream by route
--           validator's duplicate-date check)
-- ==========================================================================
CREATE OR REPLACE FUNCTION public.persist_csv_daily_returns(
  p_user_id     UUID,
  p_strategy_id UUID,
  p_rows        JSONB
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_auth_uid  UUID    := auth.uid();
  v_owner_id  UUID;
  v_row_count INTEGER;
BEGIN
  -- Guard 1: caller must have a session.
  IF v_auth_uid IS NULL THEN
    RAISE EXCEPTION 'persist_csv_daily_returns called without an auth session' USING ERRCODE = '42501';
  END IF;

  -- Guard 2: p_user_id must equal auth.uid() — defence-in-depth so a
  -- compromised route can't act on another user's behalf even if the RPC
  -- contract is misused.
  IF v_auth_uid <> p_user_id THEN
    RAISE EXCEPTION 'persist_csv_daily_returns: p_user_id (%) does not match auth.uid (%)', p_user_id, v_auth_uid USING ERRCODE = '42501';
  END IF;

  -- Guard 3 — probe-oracle close (PR #272 mitigation, T-19.1-01):
  -- Collapse missing-strategy and wrong-owner into a single 42501. The two
  -- states must be indistinguishable to authenticated callers — otherwise
  -- they can enumerate which strategy_id UUIDs exist by reading the error
  -- code or message distinction. Legitimate callers only ever pass their
  -- own freshly-created strategy_id, so the collapse is information-free
  -- for them.
  SELECT user_id INTO v_owner_id
    FROM public.strategies WHERE id = p_strategy_id;
  IF v_owner_id IS NULL OR v_owner_id <> p_user_id THEN
    RAISE EXCEPTION 'persist_csv_daily_returns: strategy % not accessible', p_strategy_id USING ERRCODE = '42501';
  END IF;

  -- Type guard (PR #272, T-19.1-06): p_rows MUST be an array before we
  -- call jsonb_array_length on it.
  IF jsonb_typeof(p_rows) <> 'array' THEN
    RAISE EXCEPTION 'persist_csv_daily_returns: p_rows must be a JSONB array, got %', jsonb_typeof(p_rows) USING ERRCODE = '22023';
  END IF;

  -- Row-count cap: prevents a single call from inserting an unbounded
  -- series. The route validator also enforces ≤5000 upstream, so this is
  -- defence-in-depth.
  IF jsonb_array_length(p_rows) > 5000 THEN
    RAISE EXCEPTION 'persist_csv_daily_returns: p_rows exceeds 5000 rows (got %)', jsonb_array_length(p_rows) USING ERRCODE = '22023';
  END IF;

  -- Empty-array guard: an empty p_rows is almost certainly a bug at the
  -- caller (the route validator should have rejected it).
  IF jsonb_array_length(p_rows) = 0 THEN
    RAISE EXCEPTION 'persist_csv_daily_returns: p_rows is empty' USING ERRCODE = '22023';
  END IF;

  -- Set-based upsert. ON CONFLICT (strategy_id, date) makes the RPC
  -- idempotent — re-running with the same payload writes the same rows
  -- (with refreshed updated_at).
  INSERT INTO public.csv_daily_returns (strategy_id, date, daily_return)
  SELECT
    p_strategy_id,
    (elem->>'date')::DATE,
    (elem->>'daily_return')::DOUBLE PRECISION
  FROM jsonb_array_elements(p_rows) elem
  ON CONFLICT (strategy_id, date) DO UPDATE
    SET daily_return = EXCLUDED.daily_return,
        updated_at   = now();

  GET DIAGNOSTICS v_row_count = ROW_COUNT;
  RETURN v_row_count;
END;
$$;
