-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260527152800_phase19_soak_daily.sql
-- ----------------------------------------------------------------------------
-- STEP 3 — phase19_soak_status extended with daily-rollup observability
-- ----------------------------------------------------------------------------
-- Additive JSON shape: existing fields (flag_value, vr_is_view,
-- legacy_write_count, since, checked_at) preserved verbatim so
-- scripts/verify-no-legacy-writes.sh continues to parse correctly. New
-- fields (daily_rows, max_error_rate, breach_count) are read by the
-- extended phase-19-stability.yml gate near ship time.
CREATE OR REPLACE FUNCTION public.phase19_soak_status(p_since timestamptz DEFAULT now())
RETURNS jsonb
LANGUAGE plpgsql
STABLE
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_flag             TEXT;
  v_is_view          BOOLEAN;
  v_legacy_writes    BIGINT  := 0;
  v_daily_rows       INTEGER := 0;
  v_max_error_rate   NUMERIC := 0;
  v_breach_count     INTEGER := 0;
BEGIN
  SELECT value INTO v_flag
    FROM feature_flags
   WHERE flag_key = 'process_key_unified_backbone';

  SELECT EXISTS(
    SELECT 1 FROM information_schema.views
     WHERE table_schema = 'public' AND table_name = 'verification_requests'
  ) INTO v_is_view;

  -- Pre-view-shim: count direct writes to the legacy base table.
  -- Post-view-shim: gate is retired and value is meaningless, so report 0.
  IF NOT v_is_view THEN
    SELECT count(*) INTO v_legacy_writes
      FROM verification_requests
     WHERE created_at > p_since
        OR (completed_at IS NOT NULL AND completed_at > p_since);
  END IF;

  -- Daily rollup state — count rows with date >= p_since's date so a soak
  -- that started mid-day still picks up day 1's row written by the cron.
  SELECT count(*),
         COALESCE(max(error_rate), 0),
         count(*) FILTER (WHERE error_rate >= 0.005)
    INTO v_daily_rows, v_max_error_rate, v_breach_count
    FROM public.phase19_soak_daily
   WHERE date_utc >= (p_since AT TIME ZONE 'UTC')::date;

  RETURN jsonb_build_object(
    'flag_value',         COALESCE(v_flag, 'unset'),
    'vr_is_view',         v_is_view,
    'legacy_write_count', v_legacy_writes,
    'daily_rows',         v_daily_rows,
    'max_error_rate',     v_max_error_rate,
    'breach_count',       v_breach_count,
    'since',              p_since,
    'checked_at',         now()
  );
END;
$$;
