-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260527152800_phase19_soak_daily.sql
-- ----------------------------------------------------------------------------
-- STEP 2 — phase19_soak_record_day(...) upsert RPC (SECDEF, service_role only)
-- ----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.phase19_soak_record_day(
  p_date_utc     DATE,
  p_day_index    SMALLINT,
  p_error_rate   NUMERIC,
  p_total_events INTEGER,
  p_error_events INTEGER,
  p_notes        TEXT DEFAULT NULL
)
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_is_service_role BOOLEAN := FALSE;
  v_caller_role TEXT;
BEGIN
  -- Defense in depth: service_role only. SECDEF bypasses RLS, so this gate
  -- is what prevents a future ACL relaxation from letting a compromised
  -- authenticated session forge daily rollup rows.
  --
  -- Use auth.role() (reads JWT claim) NOT current_user — current_user inside
  -- a SECURITY DEFINER body equals the function owner (typically postgres),
  -- not the caller. Wrap in BEGIN/EXCEPTION mirroring 20260515113910 so a
  -- direct-psql call (no JWT context) raises a clean error instead of crashing.
  BEGIN
    v_caller_role := auth.role();
    v_is_service_role := (v_caller_role = 'service_role');
  EXCEPTION WHEN OTHERS THEN
    v_is_service_role := FALSE;
    v_caller_role := 'unknown';
  END;

  IF NOT v_is_service_role THEN
    RAISE EXCEPTION 'phase19_soak_record_day: only service_role may write rollup rows (auth.role()=%)', v_caller_role
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  INSERT INTO public.phase19_soak_daily (
    date_utc, day_index, error_rate, total_events, error_events, notes, recorded_at
  ) VALUES (
    p_date_utc, p_day_index, p_error_rate, p_total_events, p_error_events, p_notes, now()
  )
  ON CONFLICT (date_utc) DO UPDATE SET
    day_index    = EXCLUDED.day_index,
    error_rate   = EXCLUDED.error_rate,
    total_events = EXCLUDED.total_events,
    error_events = EXCLUDED.error_events,
    notes        = EXCLUDED.notes,
    recorded_at  = now();

  RETURN jsonb_build_object(
    'ok',         true,
    'date_utc',   p_date_utc,
    'day_index',  p_day_index,
    'error_rate', p_error_rate
  );
END;
$$;
