-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260412125724_positions.sql
-- --------------------------------------------------------------------------
-- STEP 4: updated_at trigger
-- --------------------------------------------------------------------------
-- Same pattern as compute_jobs (migration 032 step 6).
CREATE OR REPLACE FUNCTION positions_set_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
