-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260529150000_lock_profile_privileged_columns.sql
-- ──────────────────────────────────── 2. DEFENSE-IN-DEPTH: correct (INVOKER) trigger
CREATE OR REPLACE FUNCTION prevent_profile_privileged_change()
RETURNS TRIGGER
LANGUAGE plpgsql
-- SECURITY INVOKER (the default — stated explicitly) is load-bearing: under
-- SECURITY DEFINER, current_user would be this function's owner and the
-- privileged-caller check would always pass (the exact bug that made
-- prevent_profile_role_change a no-op). As INVOKER, current_user is the role the
-- request runs under (authenticated / anon / service_role / postgres).
SECURITY INVOKER
SET search_path = public, pg_catalog
AS $$
BEGIN
  -- Privileged callers may write these columns: service_role (admin support
  -- routes, the role-revoke flow, the analytics worker), and postgres /
  -- supabase_admin (the handle_new_user signup trigger, migrations, backfills).
  IF current_user IN ('postgres', 'service_role', 'supabase_admin') THEN
    RETURN NEW;
  END IF;

  IF TG_OP = 'INSERT' THEN
    -- A non-privileged self-INSERT (should be impossible now — INSERT is
    -- revoked — but backstops a re-grant) must not seed an elevated profile.
    IF NEW.is_admin IS TRUE OR NEW.tenant_id IS NOT NULL THEN
      RAISE EXCEPTION
        'profiles: a client cannot create a row with elevated is_admin / tenant_id; use a service-role path.'
        USING ERRCODE = 'insufficient_privilege';
    END IF;
    RETURN NEW;
  END IF;

  -- UPDATE: block any change to a privileged column (backstops a column re-grant).
  IF NEW.is_admin         IS DISTINCT FROM OLD.is_admin
     OR NEW.role          IS DISTINCT FROM OLD.role
     OR NEW.tenant_id     IS DISTINCT FROM OLD.tenant_id
     OR NEW.allocator_status IS DISTINCT FROM OLD.allocator_status
     OR NEW.manager_status   IS DISTINCT FROM OLD.manager_status
     OR NEW.partner_tag   IS DISTINCT FROM OLD.partner_tag
  THEN
    RAISE EXCEPTION
      'profiles privileged columns (is_admin, role, tenant_id, allocator_status, manager_status, partner_tag) cannot be changed from the client; use an admin / service-role path.'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  RETURN NEW;
END;
$$;
