-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260510181748_positions_atomic_rebuild_rpc.sql
-- --------------------------------------------------------------------
-- positions.duration_seconds — owned by migration 114 (PR #139)
-- --------------------------------------------------------------------
-- Specialist red-team finding (PR #140 follow-up): the previous draft
-- duplicated the `ADD COLUMN IF NOT EXISTS duration_seconds BIGINT NULL`
-- here as defense-in-depth. That created an invisible-type-drift
-- hazard: if any future migration changed the column type with the
-- same `IF NOT EXISTS` pattern, the `IF NOT EXISTS` skips silently
-- and the type drift goes undetected. Migration 114 already owns
-- this column and asserts `is_nullable='YES'` in its self-verifying
-- DO block — duplicating the ADD here without duplicating the
-- type-assertion would weaken the contract.
--
-- Resolution: 114 owns ADD COLUMN; 113 omits duration_seconds from
-- the INSERT projection. Both migrations stay commutative because
-- the Python writer always emits the JSONB key, and the RPC simply
-- doesn't reference it until a follow-up CREATE OR REPLACE FUNCTION
-- migration adds it. This is the safe ordering: schema evolves in
-- 114, RPC stays conservative until both apply.

-- --------------------------------------------------------------------
-- reconstruct_positions_atomic
-- --------------------------------------------------------------------
CREATE OR REPLACE FUNCTION reconstruct_positions_atomic(
  p_strategy_id UUID,
  p_positions   JSONB
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_inserted INTEGER;
BEGIN
  IF p_strategy_id IS NULL THEN
    RAISE EXCEPTION 'reconstruct_positions_atomic: p_strategy_id must not be NULL'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- Per-strategy advisory lock: serializes concurrent rebuilds for the
  -- same strategy without blocking unrelated strategies. Released at
  -- COMMIT (xact-scoped). Mirrors the sync_trades hardening pattern.
  PERFORM pg_advisory_xact_lock(hashtext(p_strategy_id::text));

  -- Step 1 — wipe existing positions for this strategy. Inside the same
  -- transaction as the INSERT below, so a failure rolls both back.
  DELETE FROM positions WHERE strategy_id = p_strategy_id;

  -- Step 2 — bulk insert from the JSONB payload. Column list MUST match
  -- the Python writer in position_reconstruction.py. If the payload is
  -- NULL or empty, the SELECT yields zero rows and the INSERT is a no-op
  -- (a strategy with all positions purged is a valid state).
  IF p_positions IS NOT NULL AND jsonb_typeof(p_positions) = 'array' THEN
    INSERT INTO positions (
      strategy_id,
      symbol,
      side,
      status,
      entry_price_avg,
      exit_price_avg,
      size_base,
      size_peak,
      realized_pnl,
      fee_total,
      roi,
      duration_days,
      opened_at,
      closed_at,
      fill_count,
      funding_pnl
    )
    SELECT
      (elem->>'strategy_id')::UUID,
      elem->>'symbol',
      elem->>'side',
      elem->>'status',
      (elem->>'entry_price_avg')::NUMERIC,
      NULLIF(elem->>'exit_price_avg', '')::NUMERIC,
      (elem->>'size_base')::NUMERIC,
      (elem->>'size_peak')::NUMERIC,
      NULLIF(elem->>'realized_pnl', '')::NUMERIC,
      NULLIF(elem->>'fee_total', '')::NUMERIC,
      NULLIF(elem->>'roi', '')::NUMERIC,
      NULLIF(elem->>'duration_days', '')::NUMERIC,
      (elem->>'opened_at')::TIMESTAMPTZ,
      NULLIF(elem->>'closed_at', '')::TIMESTAMPTZ,
      COALESCE((elem->>'fill_count')::INTEGER, 0),
      COALESCE((elem->>'funding_pnl')::NUMERIC, 0)
    FROM jsonb_array_elements(p_positions) AS elem;
    -- NOTE: duration_seconds intentionally omitted from this projection
    -- — the Python writer (position_reconstruction.py) emits the key in
    -- the JSONB payload but the RPC ignores it until migration 114
    -- (PR #139) adds the column AND a follow-up RPC revision lands.
    -- See the header block above for the safe-ordering rationale.

    GET DIAGNOSTICS v_inserted = ROW_COUNT;
  ELSE
    v_inserted := 0;
  END IF;

  RAISE NOTICE 'reconstruct_positions_atomic: strategy=% inserted=%', p_strategy_id, v_inserted;
END;
$$;
