-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260602183000_b5b_api_key_delete_atomicity.sql
-- ==========================================================================
-- 3. replace_allocator_equity_snapshots — same per-allocator advisory lock
--    (H-1186 worker half)
-- ==========================================================================
-- ⚠️ This function was LAST defined by migration 20260529160000 (CL9 /
-- NEW-C01-11), NOT 20260527102050 (E4). CL9 added the 7th column
-- `pre_terminus_balance_unknown` to the INSERT + jsonb_to_recordset. This
-- CREATE OR REPLACE re-applies the CL9 body VERBATIM (all 7 columns) and adds
-- ONLY the per-allocator advisory lock + function-scoped lock_timeout. Dropping
-- the CL9 column here would silently revert NEW-C01-11 and re-expose the
-- OKX-terminus garbage equity curve — the exact silent-data-loss class this
-- migration closes. The DO block below asserts the column persists.
--
-- The advisory lock keys on hashtext('alloc:' || p_allocator_id) — the SAME
-- key delete_allocator_api_key uses (auth.uid() == p_allocator_id for one
-- allocator) so the worker's sole-key replace serializes with a concurrent
-- last-key cascade. Signature, SECURITY DEFINER, search_path, WR-05 depth,
-- scoping, and grants are otherwise unchanged from CL9.
CREATE OR REPLACE FUNCTION replace_allocator_equity_snapshots(
  p_allocator_id UUID,
  p_rows         JSONB,    -- array of {asof, value_usd, breakdown, source, pre_terminus_balance_unknown}
  p_depth_months INTEGER   -- per WR-05: applied only to source='exchange_primary' rows
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
SET lock_timeout = '3s'
AS $$
DECLARE
  v_inserted INTEGER;
BEGIN
  -- H-1186: serialize against delete_allocator_api_key on the same per-allocator
  -- key so a concurrent last-key cascade cannot interleave with this replace.
  PERFORM pg_advisory_xact_lock(hashtext('alloc:' || p_allocator_id::text));

  -- 1. Purge — strictly scoped to this allocator.
  DELETE FROM public.allocator_equity_snapshots
    WHERE allocator_id = p_allocator_id;

  -- 2. Insert the freshly replayed rows. jsonb_to_recordset projects the
  --    array; reconstructed_at uses the column DEFAULT (now()). The CASE on
  --    source mirrors persist_equity_snapshots' WR-05 per-row depth rule.
  --    CL9: pre_terminus_balance_unknown is projected too; COALESCE to false
  --    keeps a pre-deploy worker (payload omits the field) NOT-NULL-safe.
  WITH ins AS (
    INSERT INTO public.allocator_equity_snapshots (
      allocator_id, asof, value_usd, breakdown, source, history_depth_months,
      pre_terminus_balance_unknown
    )
    SELECT
      p_allocator_id,
      r.asof,
      r.value_usd,
      r.breakdown,
      r.source,
      CASE WHEN r.source = 'exchange_primary' THEN p_depth_months ELSE NULL END,
      COALESCE(r.pre_terminus_balance_unknown, false)
    FROM jsonb_to_recordset(COALESCE(p_rows, '[]'::jsonb)) AS r(
      asof                          DATE,
      value_usd                     NUMERIC,
      breakdown                     JSONB,
      source                        TEXT,
      pre_terminus_balance_unknown  BOOLEAN
    )
    ON CONFLICT (allocator_id, asof) DO NOTHING
    RETURNING 1
  )
  SELECT count(*) INTO v_inserted FROM ins;

  RETURN v_inserted;
END;
$$;
