-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260515113853_retention_crons_safe.sql
-- --------------------------------------------------------------------------
-- STEP 1: retention_delete_guard trigger function + attachments
-- --------------------------------------------------------------------------
-- Counts deleted rows in a transition table and raises if the count
-- exceeds 100,000 — comfortably above any plausible single-night batch
-- (audit_log volume is sub-1k/day even at fill peak per ADR-0024 §3),
-- well below the "someone forgot the WHERE" wipe scenario.
CREATE OR REPLACE FUNCTION public.retention_delete_guard()
RETURNS TRIGGER
LANGUAGE plpgsql
AS $fn$
DECLARE
  v_deleted_count BIGINT;
BEGIN
  SELECT COUNT(*) INTO v_deleted_count FROM old_table;
  IF v_deleted_count > 100000 THEN
    RAISE EXCEPTION
      'retention_delete_guard: DELETE on % affected % rows, exceeding the 100,000-row safety ceiling. This indicates an unbounded DELETE (missing WHERE) — aborting. audit-2026-05-07 P917.',
      TG_TABLE_NAME, v_deleted_count
      USING ERRCODE = 'raise_exception';
  END IF;
  RETURN NULL;
END;
$fn$;
