-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260806130000_seed_weight_snapshot_secdef.sql
-- ==========================================================================
-- 2. seed_weight_snapshots_for_portfolio() -> SECURITY DEFINER
-- ==========================================================================
-- Re-based on 20260416125431_rebalance_drift_check_and_trigger.sql:135-150.
-- Same defect class (see header (d), third rejected alternative): latent today
-- only because the portfolio_strategies FK prevents a child row from pre-dating
-- its parent, so the fan-out SELECT currently returns zero rows on the ordinary
-- path. Fixed here so the class is closed, not just the instance that reddened.

CREATE OR REPLACE FUNCTION public.seed_weight_snapshots_for_portfolio()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  INSERT INTO weight_snapshots (
    portfolio_id, strategy_id, snapshot_date, target_weight, actual_weight
  )
  SELECT NEW.id, ps.strategy_id, CURRENT_DATE, NULL, NULL
  FROM portfolio_strategies ps
  WHERE ps.portfolio_id = NEW.id
  ON CONFLICT (portfolio_id, strategy_id, snapshot_date) DO NOTHING;
  RETURN NEW;
END;
$$;
