-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260416125431_rebalance_drift_check_and_trigger.sql
-- portfolio-level trigger: fans out over every child row at the moment
-- the portfolio is inserted. Usually this is a no-op (portfolio_strategies
-- rows haven't been inserted yet), but it gives us correctness on the
-- unusual path where a bulk INSERT INTO portfolios ... with existing links
-- happens (e.g., a seed script, a migration, a restore). The per-child
-- trigger above handles the common wizard flow.
CREATE OR REPLACE FUNCTION seed_weight_snapshots_for_portfolio()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
BEGIN
  INSERT INTO weight_snapshots (
    portfolio_id, strategy_id, snapshot_date, target_weight, actual_weight
  )
  SELECT NEW.id, ps.strategy_id, CURRENT_DATE, NULL, NULL
  FROM portfolio_strategies ps
  WHERE ps.portfolio_id = NEW.id
  ON CONFLICT (portfolio_id, strategy_id, snapshot_date) DO NOTHING;
  RETURN NEW;
END;
$$;
