-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260419140916_match_decisions_original_strategy.sql
------------------------------------------------------------------
-- 3. CREATE OR REPLACE send_intro_with_decision RPC
--    with the new p_original_strategy_id parameter (position 3).
--
--    Signature change is BREAKING: old callers will hit
--    "too few arguments" — this is the DESIRED fail-loud behavior
--    so the admin route + this RPC agree atomically.
------------------------------------------------------------------
CREATE OR REPLACE FUNCTION send_intro_with_decision(
  p_allocator_id UUID,
  p_strategy_id UUID,
  p_original_strategy_id UUID,   -- NEW: position 3 for call-site clarity
  p_candidate_id UUID,
  p_admin_note TEXT,
  p_decided_by UUID
) RETURNS TABLE (
  contact_request_id UUID,
  match_decision_id UUID,
  was_already_sent BOOLEAN
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_existing_cr_id UUID;
  v_new_cr_id UUID;
  v_decision_id UUID;
  v_was_already_sent BOOLEAN := false;
BEGIN
  -- Check if contact_requests already has a row for this pair.
  -- (Idempotent match: allocator_id + strategy_id + "sent_as_intro".)
  SELECT id INTO v_existing_cr_id
  FROM contact_requests
  WHERE allocator_id = p_allocator_id AND strategy_id = p_strategy_id;

  IF v_existing_cr_id IS NOT NULL THEN
    v_was_already_sent := true;
    v_new_cr_id := v_existing_cr_id;
  ELSE
    INSERT INTO contact_requests (allocator_id, strategy_id, status, message)
    VALUES (p_allocator_id, p_strategy_id, 'pending', p_admin_note)
    RETURNING id INTO v_new_cr_id;
  END IF;

  -- Insert decision (idempotent via uniq_match_dec_sent_per_pair).
  -- NEW: persist p_original_strategy_id into the new column (NULL-allowed
  -- at this migration level; migration 065 tightens to NOT NULL).
  INSERT INTO match_decisions (
    allocator_id, strategy_id, original_strategy_id, candidate_id, decision,
    founder_note, contact_request_id, decided_by
  ) VALUES (
    p_allocator_id, p_strategy_id, p_original_strategy_id, p_candidate_id, 'sent_as_intro',
    p_admin_note, v_new_cr_id, p_decided_by
  )
  ON CONFLICT (allocator_id, strategy_id) WHERE decision = 'sent_as_intro' DO NOTHING
  RETURNING id INTO v_decision_id;

  -- If we hit ON CONFLICT, fetch the existing decision id.
  IF v_decision_id IS NULL THEN
    SELECT id INTO v_decision_id
    FROM match_decisions
    WHERE allocator_id = p_allocator_id
      AND strategy_id = p_strategy_id
      AND decision = 'sent_as_intro';
  END IF;

  RETURN QUERY SELECT v_new_cr_id, v_decision_id, v_was_already_sent;
END;
$$;
