-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260420073003_allocator_holdings.sql
-- --------------------------------------------------------------------------
-- updated_at trigger — local helper per migration 059 Step 3 shape.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_allocator_holdings_updated_at()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;
