-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260925120000_api_keys_account_identity.sql
-- ─────── 3. the owner RPC for (2). Shape mirrors disconnect_allocator_api_key.
CREATE FUNCTION public.set_departed_key_history_inclusion(
  p_api_key_id uuid,
  p_inclusion  text
)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO public, pg_catalog
AS $$
DECLARE
  v_uid          uuid := auth.uid();
  v_owner        uuid;
  v_disconnected timestamptz;
  v_sync_status  text;
  v_previous     text;
  v_job          uuid;
  v_job_status   text;
  v_claimed_at   timestamptz;
BEGIN
  IF v_uid IS NULL THEN
    RAISE EXCEPTION 'not_authenticated'
      USING ERRCODE = '42501';
  END IF;

  -- Scoped to the caller, so another user's row is never even locked.
  SELECT user_id, disconnected_at, sync_status, history_inclusion
    INTO v_owner, v_disconnected, v_sync_status, v_previous
    FROM public.api_keys
   WHERE id = p_api_key_id
     AND user_id = v_uid
     FOR UPDATE;

  IF v_owner IS NULL OR v_owner <> v_uid THEN
    RAISE EXCEPTION 'set_departed_key_history_inclusion: caller does not own api_key %', p_api_key_id
      USING ERRCODE = '42501';  -- insufficient_privilege
  END IF;

  -- NULL resets to the default rule; anything else outside the two choices is
  -- refused rather than stored.
  IF p_inclusion IS NOT NULL AND p_inclusion NOT IN ('include', 'exclude') THEN
    RAISE EXCEPTION 'HISTORY_INCLUSION_INVALID'
      USING ERRCODE = '22023',
            DETAIL  = 'p_inclusion must be ''include'', ''exclude'' or NULL (the default rule).';
  END IF;

  -- Only a departed key has an end day, so only a departed key has a choice.
  IF v_disconnected IS NULL AND v_sync_status IS DISTINCT FROM 'revoked' THEN
    RAISE EXCEPTION 'KEY_NOT_DEPARTED'
      USING ERRCODE = '55000',
            DETAIL  = 'Only a disconnected or revoked key''s history can be included or excluded; a live key always counts.';
  END IF;

  -- A recompose that is already RUNNING has read (or may have read) the old
  -- value, and enqueue_compute_job would fold this request into it: its
  -- in-flight dedup AND the partial unique index
  -- compute_jobs_one_inflight_per_kind_allocator both cover pending, running
  -- and done_pending_children, so no second job for (allocator, kind) can be
  -- queued behind a running one. MEASURED 2026-09-26 over the 9-arg
  -- enqueue_compute_job (20260515210300) and the 10-arg
  -- _enqueue_compute_job_internal (20260924230827): p_idempotency_key is not
  -- part of the dedup, p_run_at only sets next_attempt_at, and a fan-in child
  -- (p_parent_job_ids) starts done_pending_children, which the same index
  -- covers. Refusing by name, with nothing written, is therefore the option
  -- that stays inside that contract for every other caller; the owner retries
  -- once the running compose ends.
  --
  -- Step 1. Lock EVERY claimable or in-flight row for the caller's recompose.
  -- Both claim functions take candidates with status IN ('pending',
  -- 'failed_retry') through FOR UPDATE SKIP LOCKED, so a row locked here cannot
  -- be claimed (and so cannot read the old value) before this transaction
  -- commits. PERFORM, not SELECT INTO: a failed_retry row lies outside the
  -- partial unique index and can coexist with a pending one, and a SELECT INTO
  -- stops at the first row, locking only that one.
  PERFORM 1
     FROM public.compute_jobs
    WHERE allocator_id = v_uid
      AND kind = 'derive_allocator_equity'
      AND status IN ('pending', 'failed_retry', 'running', 'done_pending_children')
      FOR UPDATE;

  -- Step 2. A running recompose is refused before anything is written. The
  -- DETAIL carries how long it has run, so a busy recompose can be told from a
  -- stuck one. The reclaim wording tracks analytics-service/main_worker.py:
  -- watchdog_tick passes p_stale_threshold '10 minutes' to
  -- reset_stalled_compute_jobs, which measures claimed_at, and
  -- WATCHDOG_PER_KIND_OVERRIDES has no derive_allocator_equity entry. The
  -- watchdog runs inside the worker process, so the reclaim happens only while
  -- a worker is up. Change the HINT if either constant moves.
  SELECT status, claimed_at INTO v_job_status, v_claimed_at
    FROM public.compute_jobs
   WHERE allocator_id = v_uid
     AND kind = 'derive_allocator_equity'
     AND status = 'running'
   LIMIT 1;

  IF v_job_status = 'running' THEN
    RAISE EXCEPTION 'HISTORY_RECOMPOSE_IN_PROGRESS'
      USING ERRCODE = '55006',
            DETAIL  = format('A recompose of your equity history has been running for %s. Try again when it finishes; nothing was changed.',
                             CASE WHEN v_claimed_at IS NULL THEN 'an unknown time'
                                  ELSE floor(extract(epoch FROM now() - v_claimed_at) / 60)::int || ' minute(s)' END),
            HINT    = 'If it does not finish, a running worker reclaims a recompose that has run for more than 10 minutes and queues it again. Retry after that.';
  END IF;

  UPDATE public.api_keys
     SET history_inclusion = p_inclusion
   WHERE id = p_api_key_id
     AND user_id = v_uid;

  -- Recompose the caller's curve, never by queuing a pending TWIN of a
  -- failed_retry recompose. enqueue_compute_job's in-flight dedup and the
  -- partial unique index compute_jobs_one_inflight_per_kind_allocator both
  -- ignore failed_retry, so an enqueue beside a failed_retry row inserts a
  -- second, pending row for the same allocator. MEASURED on the pg-lane
  -- 2026-09-26: a due failed_retry derive_allocator_equity row beside a pending
  -- one makes claim_compute_jobs and both claim_compute_jobs_with_priority
  -- overloads raise 23505 on that index (the worker-spin class of 2026-04-28).
  -- So when a failed_retry row is the caller's ONLY recompose row, it is
  -- REUSED: it is already locked by step 1, and moving next_attempt_at to now()
  -- is all the claim functions need to take it (status IN ('pending',
  -- 'failed_retry') AND next_attempt_at <= now()); they clear its last_error
  -- and error_kind themselves. attempts is left alone, so the toggle grants no
  -- retry budget: a row one attempt short of max_attempts ends failed_final if
  -- it fails again, and the next toggle then enqueues a fresh job. The job
  -- reads history_inclusion when it runs, so it picks up the new value.
  -- When a pending or done_pending_children row also exists (a pairing this
  -- RPC did not create), the failed_retry row is NOT moved forward, because
  -- ranking it first is exactly the 23505 shape; the enqueue's dedup hands
  -- back the in-flight row instead and inserts nothing.
  SELECT cj.id INTO v_job
    FROM public.compute_jobs cj
   WHERE cj.allocator_id = v_uid
     AND cj.kind = 'derive_allocator_equity'
     AND cj.status = 'failed_retry'
     AND NOT EXISTS (
           SELECT 1
             FROM public.compute_jobs o
            WHERE o.allocator_id = v_uid
              AND o.kind = 'derive_allocator_equity'
              AND o.status IN ('pending', 'done_pending_children'))
   ORDER BY cj.next_attempt_at, cj.id
   LIMIT 1;

  IF v_job IS NOT NULL THEN
    UPDATE public.compute_jobs
       SET next_attempt_at = now()
     WHERE id = v_job;
  ELSE
    -- Allocator-scoped, so enqueue_compute_job's own gate requires
    -- p_allocator_id = auth.uid(), and its in-flight dedup hands back the
    -- pending job locked above, so a burst of toggles is one job.
    v_job := enqueue_compute_job(
      p_strategy_id  := NULL,
      p_kind         := 'derive_allocator_equity',
      p_allocator_id := v_uid
    );
  END IF;

  -- Step 3. Lock and re-check the job the enqueue returned (a reused
  -- failed_retry row is already locked by step 1 and passes). Step 1 cannot see
  -- a job that another transaction enqueued, and a worker claimed, after
  -- step 1 ran; the dedup would then hand back that RUNNING job, which read
  -- the old value. The row returned here is either this transaction's own
  -- uncommitted insert (invisible to every claimer) or an existing row that is
  -- now locked (skipped by every claimer), so once this check passes no
  -- worker can start the job before the new value commits. If a claimer holds
  -- the row, this waits, re-reads the row as READ COMMITTED does, sees
  -- running, and refuses; the refusal rolls the UPDATE above back.
  -- REASONED, NOT MEASURED: steps 1 and 3 close races between TWO backends,
  -- and the SQL gate corpus runs one session, so neither window has been
  -- exercised. Step 3's refusal is gated (arm HIST-running) only in the
  -- single-session shape where the job is already running.
  SELECT status, claimed_at INTO v_job_status, v_claimed_at
    FROM public.compute_jobs
   WHERE id = v_job
     FOR UPDATE;

  IF v_job_status = 'running' THEN
    RAISE EXCEPTION 'HISTORY_RECOMPOSE_IN_PROGRESS'
      USING ERRCODE = '55006',
            DETAIL  = format('A recompose of your equity history has been running for %s. Try again when it finishes; nothing was changed.',
                             CASE WHEN v_claimed_at IS NULL THEN 'an unknown time'
                                  ELSE floor(extract(epoch FROM now() - v_claimed_at) / 60)::int || ' minute(s)' END),
            HINT    = 'If it does not finish, a running worker reclaims a recompose that has run for more than 10 minutes and queues it again. Retry after that.';
  END IF;

  RAISE NOTICE 'set_departed_key_history_inclusion: recompose job % queued for the caller', v_job;

  RETURN v_previous IS DISTINCT FROM p_inclusion;
END;
$$;
