-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260712130000_set_compute_job_progress.sql
CREATE OR REPLACE FUNCTION set_compute_job_progress(
  p_job_id      UUID,
  p_claim_token UUID,
  p_progress    JSONB
) RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  -- Fenced JSONB merge: `||` replaces ONLY the member_progress /
  -- member_progress_at keys and preserves every other metadata key
  -- (source, correlation_id, unified_backbone_at_claim). member_progress_at
  -- is stamped SERVER-SIDE via now() so the 95-03 stall heartbeat cannot be
  -- back-dated by a lagging worker clock.
  UPDATE compute_jobs
     SET metadata = COALESCE(metadata, '{}'::jsonb)
                 || jsonb_build_object(
                      'member_progress',    p_progress,
                      'member_progress_at', to_jsonb(now())
                    )
   WHERE id = p_job_id
     AND claim_token IS NOT DISTINCT FROM p_claim_token
     AND claim_token IS NOT NULL
     AND status = 'running';
  RETURN FOUND;
END;
$$;
