-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260430055512_stamp_first_bridge_surfaced.sql
-- ----------------------------------------------------------------------
-- RPC: stamp_first_bridge_surfaced(p_user_id UUID)
-- Returns JSONB: {"stamped": true|false, "stamped_at": "<iso8601>"}.
--
-- Semantics:
--   - First call per user: writes `first_bridge_surfaced_at = now()`,
--     returns `{stamped: true, stamped_at: <just-written>}`.
--   - Subsequent calls: no-op, return `{stamped: false, stamped_at:
--     <existing>}`.
--   - Defensive: if the user_id doesn't exist (FK violation upstream),
--     return `{stamped: false, stamped_at: null}` rather than raising —
--     analytics MUST NOT crash a host request.
-- ----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.stamp_first_bridge_surfaced(p_user_id UUID)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_meta JSONB;
  v_existing TIMESTAMPTZ;
  v_existing_text TEXT;
  v_new_stamp TEXT;
BEGIN
  -- Lock the auth.users row so concurrent callers serialize. This is
  -- the atomic primitive that retires the WR-02 race.
  SELECT raw_user_meta_data
    INTO v_meta
    FROM auth.users
    WHERE id = p_user_id
    FOR UPDATE;

  IF NOT FOUND THEN
    -- Defensive: caller passed a user_id that doesn't exist. No-op
    -- rather than raising — analytics must not crash the host request.
    RETURN jsonb_build_object('stamped', false, 'stamped_at', NULL);
  END IF;

  -- Defensive: handle the NULL-initial-state case (mirrors migration 084).
  v_meta := COALESCE(v_meta, '{}'::JSONB);
  v_existing_text := NULLIF(v_meta->>'first_bridge_surfaced_at', '');
  v_existing := v_existing_text::TIMESTAMPTZ;

  -- Idempotent: only stamp on the FIRST call per user. Subsequent calls
  -- return the existing stamp with stamped=false so the TS caller can
  -- pass the persisted value as the PostHog property if some downstream
  -- path ever needs it.
  IF v_existing IS NOT NULL THEN
    RETURN jsonb_build_object(
      'stamped', false,
      'stamped_at', v_existing_text
    );
  END IF;

  -- First call per user — compute the stamp once, persist it, and return
  -- it as the canonical value. Format mirrors migration 084's `to_char`
  -- shape so the test pin (ISO_MS_RE) matches.
  v_new_stamp := to_char(now() AT TIME ZONE 'UTC',
                         'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"');

  UPDATE auth.users
     SET raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::JSONB)
                              || jsonb_build_object(
                                   'first_bridge_surfaced_at', v_new_stamp
                                 )
   WHERE id = p_user_id;

  RETURN jsonb_build_object(
    'stamped', true,
    'stamped_at', v_new_stamp
  );
END;
$$;
