-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260529170100_circuit_breaker_db_clock_rpcs.sql
-- --------------------------------------------------------------------------
-- STEP 1: stamp_api_key_429 — stamp last_429_at = now() on the DB clock.
-- --------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION stamp_api_key_429(
  p_api_key_id UUID
)
RETURNS VOID
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
BEGIN
  IF p_api_key_id IS NULL THEN
    RAISE EXCEPTION 'stamp_api_key_429: p_api_key_id is required'
      USING ERRCODE = 'invalid_parameter_value';
  END IF;

  -- Defense-in-depth ownership gate, mirroring the sibling user-facing stamp
  -- update_api_key_rate_limit (mig 111). _assert_owner is a NO-OP under the
  -- service role (auth.uid() IS NULL → returns early), so the worker — the
  -- sole intended caller — pays nothing. Its only effect is to block a
  -- cross-tenant write (stamping ANY user's last_429_at to force-trip their
  -- breaker / DoS their syncs) should EXECUTE ever be re-granted to
  -- authenticated by a future migration. Without it the cross-tenant write
  -- path would be gated by the REVOKE alone — a single line, in a table with
  -- a documented history of REVOKEs silently no-opping (mig 027).
  PERFORM _assert_owner('api_keys'::regclass, p_api_key_id, 'stamp_api_key_429');

  -- Always stamp the latest 429 from the DB clock. A missing row (key
  -- deleted between claim and stamp) is a no-op: the breaker stamp is
  -- best-effort and must never convert a 429 into a hard error that would
  -- fail the job.
  UPDATE api_keys
     SET last_429_at = now()
   WHERE id = p_api_key_id;
END;
$$;
