-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260426193121_first_api_key_added_trigger.sql
-- ----------------------------------------------------------------------
-- Trigger function: stamp_first_api_key_added
-- Fires AFTER INSERT FOR EACH ROW on api_keys. Idempotently sets
-- first_api_key_added_at on auth.users.raw_user_meta_data — only the
-- FIRST INSERT per user actually writes; subsequent rows no-op.
-- ----------------------------------------------------------------------
CREATE OR REPLACE FUNCTION public.stamp_first_api_key_added()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, public
AS $$
DECLARE
  v_meta JSONB;
  v_existing TIMESTAMPTZ;
BEGIN
  -- Lock the auth.users row so concurrent INSERTs serialize.
  SELECT raw_user_meta_data
    INTO v_meta
    FROM auth.users
    WHERE id = NEW.user_id
    FOR UPDATE;

  IF NOT FOUND THEN
    -- Defensive: api_keys.user_id has FK to profiles(id) which has FK
    -- to auth.users(id), so this should not happen under normal
    -- operation. Don't crash the INSERT — return.
    RETURN NEW;
  END IF;

  -- Defensive: handle the NULL-initial-state case. Some auth.users
  -- rows have raw_user_meta_data NULL until a first metadata write
  -- occurs. Without COALESCE, the `||` merge below would propagate NULL.
  v_meta := COALESCE(v_meta, '{}'::JSONB);
  v_existing := NULLIF(v_meta->>'first_api_key_added_at', '')::TIMESTAMPTZ;

  -- Idempotent: only stamp on the FIRST INSERT per user.
  IF v_existing IS NOT NULL THEN
    RETURN NEW;
  END IF;

  UPDATE auth.users
     SET raw_user_meta_data = COALESCE(raw_user_meta_data, '{}'::JSONB)
                              || jsonb_build_object(
                                   'first_api_key_added_at',
                                   to_char(now() AT TIME ZONE 'UTC',
                                           'YYYY-MM-DD"T"HH24:MI:SS.MS"Z"')
                                 )
   WHERE id = NEW.user_id;

  RETURN NEW;
END;
$$;
