-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260906120000_computation_error_provenance.sql
-- --------------------------------------------------------------------------
-- STEP 3: the invariant, moved from this file's prose to the table
-- --------------------------------------------------------------------------
-- See the header's ⛔⛔ paragraph for the enumerated writers and the measured
-- NULL-sentence scenario this closes. In one line: a statement that CHANGES the
-- sentence WITHOUT RESTATING the provenance drops the provenance.
--
-- SHAPE COPIED FROM `strategy_analytics_stamp_computing_started` (mig
-- 20260803120000:116-186), which enforces the neighbouring
-- computing_started_at invariant on this same table from the same event:
-- SECURITY INVOKER (the default -- the body touches only its own NEW/OLD tuples
-- and needs no privilege the firing statement does not already hold), pinned
-- search_path, self-contained (no helper call -- see 20260516170000:3-11 for the
-- incident class that rule exists to avoid), REVOKEd from the API roles so it is
-- never reachable as a PostgREST RPC, and BEFORE UPDATE FOR EACH ROW.
--
-- ⚠️ IT COEXISTS WITH THAT TRIGGER AND CANNOT FIGHT IT. Two BEFORE ROW triggers
-- on one table fire in name order, each handed the previous one's NEW tuple.
-- This one assigns ONLY the two marker columns; that one assigns ONLY
-- computing_started_at. The column sets are disjoint, so the composition is
-- order-independent and the alphabetical precedence of this name is not a fact
-- anything depends on.
--
-- ⚠️ UPDATE ONLY, deliberately, matching 20260803120000's D-18 scope. An INSERT
-- has no OLD tuple, so there is no prior provenance to invalidate: a fresh row's
-- markers describe the sentence inserted beside them by construction. A DELETE
-- would additionally require the sanitize_user erasure exemption
-- (20260710160000:67), and there is nothing here to enforce on one.
--
-- ⛔ IT NEVER RAISES. It coerces, silently, exactly as the stamp trigger does
-- and for the same reason recorded there: raising would kill a live
-- analytics-service write, burn its retries and strand the strategy. The
-- coercion is toward the pre-164.2 behaviour (no provenance -> the per-kind
-- generic), which is the direction every unknown in this file resolves to.
--
-- ⛔ THE BODY CARRIES NO COMMENTS, AND THAT IS THIS FILE'S H1 RULE APPLIED HERE
-- RATHER THAN AN OVERSIGHT. pg_get_functiondef returns comments, and the
-- self-verify block below anchors on this body's ONE conditional. A comment
-- restating the predicate would satisfy those anchors over a deleted predicate,
-- which is the failure mode the whole self-verify convention exists to avoid.
-- The prose lives here and in the COMMENT ON FUNCTION, neither of which
-- pg_get_functiondef returns.
CREATE OR REPLACE FUNCTION public.strategy_analytics_drop_stale_error_provenance()
RETURNS TRIGGER
LANGUAGE plpgsql
SET search_path = public, pg_catalog
AS $$
BEGIN
  IF NEW.computation_error IS DISTINCT FROM OLD.computation_error
     AND NEW.computation_error_source IS NOT DISTINCT FROM OLD.computation_error_source
     AND NEW.computation_error_job_id IS NOT DISTINCT FROM OLD.computation_error_job_id
  THEN
    NEW.computation_error_source := NULL;
    NEW.computation_error_job_id := NULL;
  END IF;
  RETURN NEW;
END;
$$;
