-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260827120000_strategy_shares_generation_model.sql
-- --------------------------------------------------------------------------
-- STEP 1b: enforce the monotonic-counter invariant IN THE DATABASE
-- --------------------------------------------------------------------------
-- ⛔ THE OWNER SELF-REWIND. Everything above assumes `generation` only ever
-- moves through revoke_strategy_share(). It does not, and the gap was MEASURED
-- (PostgreSQL 16, throwaway replica of this schema, 2026-08-27) rather than
-- reasoned about:
--   * the STEP 2 grant is column-UNRESTRICTED (`GRANT SELECT, INSERT, UPDATE`);
--   * `strategy_shares_owner` is FOR ALL, and an owner's UPDATE of their OWN
--     row satisfies USING *and* WITH CHECK whenever created_by is unchanged.
-- So a plain `PATCH /rest/v1/strategy_shares?strategy_id=eq.<own>` carrying
-- `{"generation": 1, "revoked_at": null}` was accepted: generation went 2 -> 1
-- and the tombstone was cleared, in one request, from an ordinary user token.
-- Every recipient still holding a previously-revoked link regained anonymous
-- access to that owner's UNPUBLISHED factsheet. It also made the table COMMENT
-- above false and defeated the Art. 17 arm in companion migration
-- 20260827130000, whose whole value is that revocation is IRREVERSIBLE.
--
-- ⚠️ COLUMN-LEVEL GRANTS ARE NOT THE FIX **FOR `generation` AND `revoked_at`**,
-- and the earlier absolute phrasing of this paragraph was WRONG — it forbade
-- the very mechanism STEP 2 now relies on. The correct, narrower statement:
-- PostgreSQL requires column-level INSERT/UPDATE privilege only on the columns
-- a statement NAMES. Both RPCs NAME `generation` and `revoked_at`, so revoking
-- those two would disarm revoke_strategy_share(), which is SECURITY INVOKER and
-- writes AS THE CALLER — those privileges must stay, and what must be
-- constrained is the DIRECTION they may move, which is this trigger's job.
-- ⭐ `nonce` is the opposite case, and uniquely so: it is DEFAULT-populated and
-- NAMED BY NO RPC, so `GRANT INSERT (strategy_id, created_by)` /
-- `GRANT UPDATE (revoked_at, generation)` lock it while both RPCs keep working
-- unchanged (MEASURED both ways — see STEP 2). It is therefore the ONLY MAC
-- input that can be made unwritable-by-client without abandoning the founder's
-- SECURITY INVOKER ruling.
--
-- ⭐ WHY A TRIGGER AND NOT A CHECK CONSTRAINT: the invariant spans OLD and NEW,
-- which a CHECK cannot see. And ⛔ **a trigger is NOT bypassed by BYPASSRLS** —
-- unlike every RLS policy on this table, this fires for `service_role` too, so
-- it is the only control here that also covers the admin transport the
-- recipient lane already uses (STEP 2).
--
-- ⛔ THE TWO-REQUEST RE-POINT — why guarding `generation` ALONE is not enough.
-- An earlier version of this trigger compared only the counter and the
-- tombstone. It never looked at `strategy_id`, so the identical end state was
-- reachable in two requests instead of one, both issued as the row's own owner:
--   1. `PATCH /rest/v1/strategy_shares?strategy_id=eq.<A>` `{"strategy_id":"<B>"}`
--      where B is a second strategy the SAME user owns and has never shared.
--      USING passes (created_by is unchanged), the CR-01 WITH CHECK EXISTS
--      passes (they really do own B), UNIQUE(strategy_id) is free because B has
--      no row, and the counter is untouched — so nothing above rejected it. The
--      advanced counter walks away with strategy B and strategy A is left with
--      NO share row at all.
--   2. `create_strategy_share(A)` then takes the INSERT path and lands a fresh
--      row at `generation` DEFAULT 1. HMAC(secret, A || 1) is byte-identical to
--      the token A handed out — and REVOKED — at generation 1, so every
--      recipient holding that dead url is back inside the unpublished factsheet.
-- The counter is only meaningful RELATIVE to the strategy it counts for. That
-- binding is therefore IMMUTABLE, and so are the row identity and provenance
-- columns: STEP 3 tells the reader that reactivation never rewrites
-- created_by/created_at, and before rule (0b) a raw PATCH falsified that claim.
--
-- The five rules together are what make the model sound:
--   (0a) strategy_id NEVER changes. Re-pointing the counter re-issues generation
--        1 for the strategy it was pointed away from.
--   (0b) id, created_by and created_at NEVER change. Provenance on a live
--        capability grant must not be forgeable.
--   (0c) nonce NEVER changes. STEP 2's column grant already denies an ordinary
--        `authenticated` caller any write naming this column — but a grant
--        binds only roles that OBEY grants, and `service_role` holds GRANT ALL
--        and BYPASSRLS and is on this feature's hot path (the recipient lane
--        reads this table through createAdminClient()). MEASURED with rule (0c)
--        absent: `SET ROLE service_role; UPDATE strategy_shares SET nonce = <a
--        nonce recorded earlier>` was ACCEPTED — restoring a recorded nonce is
--        exactly the R2g residual, and the trigger is the only control on this
--        table that reaches that caller. ⚠️ It does not ELIMINATE the residual
--        (an operator who can read SHARE_TOKEN_SECRET can mint any token from
--        scratch); it removes the cheap in-database form of it.
--   (1)  generation NEVER decreases. A rewind re-issues a dead token.
--   (2)  a revocation (revoked_at NULL -> NOT NULL) MUST advance generation.
-- ⛔ RULES (1) AND (2) ARE NOT SUPERSEDED BY THE NONCE and must both stay. The
-- nonce closes resurrection via row DESTRUCTION AND RE-CREATION; (1) and (2)
-- govern the SAME row, which keeps its nonce throughout. A rewind on a
-- surviving row re-derives a dead token with the nonce unchanged — the nonce is
-- simply a constant in that pre-image and contributes nothing.
-- (2) is what lets reactivation stay unconstrained: because every revoked row
-- provably got there by advancing, clearing `revoked_at` without touching the
-- counter — exactly what create_strategy_share() does — can never return the
-- row to a generation that was live before a revoke. Without (2) an owner could
-- raw-stamp revoked_at at generation G (making the link merely go dark), then
-- re-mint and bring that same generation-G token back to life.
--
-- ⚠️ THE FUNCTION NAME IS NOW NARROWER THAN ITS JOB, and is kept anyway:
-- `strategy_shares_enforce_monotonic_generation` / trigger
-- `strategy_shares_monotonic_generation` are pinned by name in STEP 6 (v), by
-- `supabase/tests/test_strategy_shares_rls.sql` (SHAPE 5) and by this table's
-- COMMENT. Renaming to chase the widened scope would touch four sites to buy a
-- better word; the scope is documented here and in the function COMMENT instead.
--
-- ⛔ FOUNDER RULING (2026-08-27) — the alternative fix was CONSIDERED AND
-- REJECTED: revoking the client UPDATE grant outright and converting both RPCs
-- to SECURITY DEFINER would also close the re-point, but it deletes RLS as the
-- ownership wall on this surface and moves the whole tenancy argument inside two
-- function bodies. The column pin plus SECURITY INVOKER is the ruling. Do not
-- re-litigate it.
CREATE OR REPLACE FUNCTION public.strategy_shares_enforce_monotonic_generation()
RETURNS TRIGGER
LANGUAGE plpgsql
SECURITY INVOKER
SET search_path = public, pg_temp
AS $$
BEGIN
  -- (0a) the counter is bound to ONE strategy, permanently.
  IF NEW.strategy_id IS DISTINCT FROM OLD.strategy_id THEN
    RAISE EXCEPTION 'strategy_shares: strategy_id is immutable — refusing to re-point the share row for strategy % at strategy %. The generation counter is only meaningful RELATIVE to the strategy it counts for. Moving it leaves the original strategy with NO share row, so the very next create_strategy_share() inserts a fresh one at generation 1 and re-issues every token that strategy ever had at generation 1 — including the ones that were explicitly REVOKED. Two requests, both legitimate for the row owner, same end state as rewinding the counter.',
      OLD.strategy_id, NEW.strategy_id
      USING ERRCODE = 'check_violation';
  END IF;

  -- (0b) row identity and provenance are write-once.
  IF NEW.id IS DISTINCT FROM OLD.id
     OR NEW.created_by IS DISTINCT FROM OLD.created_by
     OR NEW.created_at IS DISTINCT FROM OLD.created_at THEN
    RAISE EXCEPTION 'strategy_shares: identity and provenance are immutable — refusing to rewrite id, created_by or created_at on strategy %. STEP 3 of this migration tells every future reader that reactivation never rewrites provenance; without this rule a raw PATCH falsifies that claim and forges who minted a live anonymous capability link, and when.',
      OLD.strategy_id
      USING ERRCODE = 'check_violation';
  END IF;

  -- (0c) the MAC witness is write-once. Deliberately its OWN rule and its OWN
  -- message rather than a fourth column bolted onto (0b): (0b) is a provenance
  -- claim (who/when), this is a CRYPTOGRAPHIC one, and the arms that pin them
  -- need distinguishable messages or one deletion hides behind the other's text.
  IF NEW.nonce IS DISTINCT FROM OLD.nonce THEN
    RAISE EXCEPTION 'strategy_shares: nonce is immutable — refusing to rewrite the MAC witness on strategy %. The nonce is what makes a destroyed-and-recreated row land in a token space DISJOINT from every token ever issued; letting it be written back restores a recorded value and resurrects those tokens. STEP 2''s column grant already denies this to `authenticated`, so a write that reaches this rule came from a role that BYPASSES grants — service_role, which holds GRANT ALL and is on this feature''s hot path. A trigger is the only control on this table that binds it.',
      OLD.strategy_id
      USING ERRCODE = 'check_violation';
  END IF;

  IF NEW.generation < OLD.generation THEN
    RAISE EXCEPTION 'strategy_shares: generation is monotonic — refusing to rewind it from % to % on strategy %. A rewind re-issues every share token minted at the lower generation, including ones that were explicitly REVOKED, as anonymous access to an unpublished factsheet.',
      OLD.generation, NEW.generation, OLD.strategy_id
      USING ERRCODE = 'check_violation';
  END IF;

  IF OLD.revoked_at IS NULL
     AND NEW.revoked_at IS NOT NULL
     AND NEW.generation <= OLD.generation THEN
    RAISE EXCEPTION 'strategy_shares: a revocation must ADVANCE generation — refusing to stamp revoked_at on strategy % while generation stays at %. A tombstone without a bump is COSMETIC: the link merely disappears from the active scan, and the next create_strategy_share() clears the tombstone at the SAME generation and brings the supposedly-revoked token back to life.',
      OLD.strategy_id, OLD.generation
      USING ERRCODE = 'check_violation';
  END IF;

  RETURN NEW;
END;
$$;
