-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260525192740_test_force_cold_purge.sql
CREATE OR REPLACE FUNCTION public.test_force_cold_purge(p_id uuid)
RETURNS INT
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_catalog
AS $$
DECLARE
  v_purged INT := 0;
  v_is_service_role BOOLEAN := FALSE;
  v_caller_uid UUID;
BEGIN
  -- H-0010: service_role-only gate. This is a test-cleanup RPC with no
  -- production caller, so we do NOT permit admin users (unlike migration
  -- 122). auth.role() can raise when no JWT is present (→ EXCEPTION
  -- handler) OR return NULL when the role claim is simply absent (e.g. a
  -- direct DB connection). `(NULL = 'service_role')` is NULL, NOT FALSE,
  -- so we MUST use `IS NOT TRUE` below — a plain `IF NOT v_is_service_role`
  -- would be `IF NULL` and silently SKIP the gate, letting a no-role
  -- caller through. `IS NOT TRUE` raises on both NULL and FALSE.
  BEGIN
    v_is_service_role := (auth.role() = 'service_role');
  EXCEPTION WHEN OTHERS THEN
    v_is_service_role := FALSE;
  END;

  IF v_is_service_role IS NOT TRUE THEN
    RAISE EXCEPTION
      'test_force_cold_purge: service_role JWT required (test-only RPC, no production caller). audit-2026-05-07 H-0010.'
      USING ERRCODE = 'insufficient_privilege';
  END IF;

  BEGIN
    v_caller_uid := auth.uid();
  EXCEPTION WHEN OTHERS THEN
    v_caller_uid := NULL;
  END;

  -- Emit an audit_log row BEFORE the destructive delete so the use of
  -- this append-only bypass is itself traceable (mirrors migration 122).
  INSERT INTO audit_log (user_id, action, entity_type, entity_id, metadata)
  VALUES (
    COALESCE(v_caller_uid, '00000000-0000-0000-0000-000000000000'::uuid),
    'test_force_cold_purge',
    'audit_log_cold',
    p_id,
    jsonb_build_object('invoked_via', 'service_role', 'caller_uid', v_caller_uid)
  );

  -- Scoped DELETE: ONLY test-probe rows. The doubled guard
  -- (entity_type = 'test_probe' AND the literal `__cold_test_` action
  -- prefix) makes it impossible to purge a genuine compliance row even
  -- with the service-role key. The underscores are LIKE wildcards, so we
  -- ESCAPE them to match the literal prefix.
  DELETE FROM audit_log_cold
   WHERE id = p_id
     AND entity_type = 'test_probe'
     AND action LIKE '\_\_cold\_test\_%' ESCAPE '\';

  GET DIAGNOSTICS v_purged = ROW_COUNT;
  RETURN v_purged;
END;
$$;
