-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260510172738_strategy_verifications_state_machine.sql
-- ==========================================================================
-- STEP 2: transition_strategy_verification RPC
-- ==========================================================================
-- Legal transitions (hard-coded inside the RPC body):
--   draft            → validated
--   validated        → metrics_captured
--   metrics_captured → encrypted
--   encrypted        → report_queued
--   report_queued    → published
--   *                → draft  (when metadata->>'errors' IS NOT NULL — restart path)
--
-- SECURITY DEFINER + SET search_path = public, pg_temp matches migration
-- 086 H-B hardening (prevents privilege-escalation via search_path pollution).
-- REVOKE ALL FROM PUBLIC, anon — service_role and authenticated only.
CREATE OR REPLACE FUNCTION transition_strategy_verification(
  p_verification_id UUID,
  p_new_status      TEXT,
  p_metadata        JSONB DEFAULT NULL
)
RETURNS JSONB
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public, pg_temp
AS $$
DECLARE
  v_row strategy_verifications%ROWTYPE;
  v_legal BOOLEAN;
  v_legal_pairs CONSTANT TEXT[][] := ARRAY[
    ARRAY['draft','validated'],
    ARRAY['validated','metrics_captured'],
    ARRAY['metrics_captured','encrypted'],
    ARRAY['encrypted','report_queued'],
    ARRAY['report_queued','published']
  ];
  v_pair TEXT[];
  v_metrics_snapshot JSONB;
  v_errors JSONB;
  v_encrypted JSONB;
  v_correlation_id UUID;
  v_result JSONB;
BEGIN
  -- Acquire row lock (FOR UPDATE serializes concurrent transitions)
  SELECT * INTO v_row
    FROM strategy_verifications
   WHERE id = p_verification_id
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'strategy_verification % not found', p_verification_id
      USING ERRCODE = '22023';
  END IF;

  -- Legal-transition check
  v_legal := FALSE;
  FOREACH v_pair SLICE 1 IN ARRAY v_legal_pairs LOOP
    IF v_row.status = v_pair[1] AND p_new_status = v_pair[2] THEN
      v_legal := TRUE;
      EXIT;
    END IF;
  END LOOP;

  -- Restart path: any → draft when metadata has errors (idempotent;
  -- supports the synchronous /process-key router validate-failure path
  -- where draft → draft re-records the error without changing status).
  IF NOT v_legal AND p_new_status = 'draft' AND p_metadata IS NOT NULL AND p_metadata ? 'errors' THEN
    v_legal := TRUE;
  END IF;

  IF NOT v_legal THEN
    RAISE EXCEPTION 'illegal transition % → % for verification %',
      v_row.status, p_new_status, p_verification_id
      USING ERRCODE = '22023';
  END IF;

  -- Merge metadata into respective columns (COALESCE preserves prior values
  -- when the caller does not supply that key).
  v_metrics_snapshot := COALESCE(p_metadata->'metrics_snapshot', v_row.metrics_snapshot);
  v_errors           := COALESCE(p_metadata->'errors', v_row.errors);
  v_encrypted        := COALESCE(p_metadata->'encrypted_credentials', v_row.encrypted_credentials);
  -- correlation_id is UUID — cast text-from-JSONB safely
  IF p_metadata IS NOT NULL AND p_metadata ? 'correlation_id' THEN
    v_correlation_id := (p_metadata->>'correlation_id')::UUID;
  ELSE
    v_correlation_id := v_row.correlation_id;
  END IF;

  UPDATE strategy_verifications
     SET status                 = p_new_status,
         transitioned_at        = now(),
         metrics_snapshot       = v_metrics_snapshot,
         errors                 = v_errors,
         encrypted_credentials  = v_encrypted,
         correlation_id         = v_correlation_id,
         updated_at             = now()
   WHERE id = p_verification_id
   RETURNING to_jsonb(strategy_verifications.*) INTO v_result;

  RETURN v_result;
END;
$$;
