-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.
-- Canonical current body of this function, replayed from supabase/migrations/**.
-- Regenerate with `npm run schema:functions`. See tech-debt #2.

-- source migration: 20260620120000_verification_requests_view_shim_apply.sql
-- ==========================================================================
-- STEP 4 — INSTEAD OF triggers (C-9: INSERT + UPDATE + DELETE all rejected).
-- ==========================================================================
CREATE OR REPLACE FUNCTION verification_requests_view_readonly_trigger()
RETURNS TRIGGER LANGUAGE plpgsql AS $$
BEGIN
  RAISE EXCEPTION 'verification_requests is now a read-only VIEW (Phase 19 / BACKBONE-04 step d). Writes go to strategy_verifications via POST /process-key. See .planning/phase-19/migration-plan.md slot 107.'
    USING ERRCODE = '42501',
          HINT = 'Operation rejected on the verification_requests VIEW. The legacy BASE TABLE was renamed to verification_requests_legacy. GDPR erasure deletes from verification_requests_legacy (see sanitize_user STEP 5.5).';
END;
$$;
