#!/usr/bin/env tsx
/**
 * Canonical SQL function snapshot generator (tech-debt #2).
 *
 * Business logic in this project lives in SECURITY DEFINER SQL functions that
 * are repeatedly redefined via `CREATE OR REPLACE FUNCTION` across ~194
 * append-only migrations (mark_compute_job_done alone is redefined 9x). There
 * was no committed current-state artifact, so the only way to know a function's
 * live body was to grep every migration and mentally apply them in order. That
 * opacity already caused a silent prod regression (G23-187: a rewrite copied a
 * stale body and reverted a GIN fan-in to a seq-scan loop) and a near-miss
 * (B5b). See CHANGELOG / docs/architecture for the history.
 *
 * This script replays every migration in chronological (filename) order and
 * writes the LATEST definition of each function to
 * `supabase/schema/functions/<name>.sql`. The committed snapshot makes
 * `CREATE OR REPLACE` diffs reviewable against the canonical body and replaces
 * the manual "sed-extract the latest body" ritual. A CI gate (--check) keeps it
 * honest: it regenerates and fails if the committed snapshot is stale.
 *
 * SCOPE: functions only (the dominant redefine class + the regression class
 * that actually shipped). Tables/columns/policies/triggers are NOT covered —
 * those evolve via incremental ALTERs that text-replay can't reconstruct, and a
 * full-schema snapshot needs the Supabase local stack in CI (deferred; see
 * docs/deferred-findings.md).
 *
 * Hermetic by design: pure text processing, no DB, no Docker, no secrets — so
 * the gate can never flake. Regenerate locally with `npm run schema:functions`.
 *
 * Usage:
 *   tsx scripts/dump-sql-functions.ts            # regenerate the snapshot
 *   tsx scripts/dump-sql-functions.ts --check    # CI gate: fail if stale
 *   tsx scripts/dump-sql-functions.ts --self-test # parser self-check
 */
import { readFileSync, readdirSync, writeFileSync, mkdirSync, rmSync, existsSync, statSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const REPO_ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const MIGRATIONS_DIR = join(REPO_ROOT, "supabase", "migrations");
const SNAPSHOT_DIR = join(REPO_ROOT, "supabase", "schema", "functions");

const HEADER =
  "-- @generated by scripts/dump-sql-functions.ts — DO NOT EDIT BY HAND.\n" +
  "-- Canonical current body of this function, replayed from supabase/migrations/**.\n" +
  "-- Regenerate with `npm run schema:functions`. See tech-debt #2.\n";

/**
 * Split SQL into top-level statements, respecting the lexical contexts where a
 * `;` does NOT end a statement: line comments, block comments (Postgres nests
 * them), single-quoted strings ('' escape), and dollar-quoted strings
 * ($tag$ ... $tag$, where only the matching tag closes — so a $cron$ body
 * containing $$ is one opaque blob). Returns each statement's raw text.
 */
export function splitStatements(sql: string): string[] {
  const out: string[] = [];
  let buf = "";
  let i = 0;
  const n = sql.length;
  let blockDepth = 0; // /* */ nesting
  let inLine = false; // -- ... \n
  let inSingle = false; // '...'
  let dollarTag: string | null = null; // current open $tag$

  // Try to read a dollar-quote tag at position p: $[A-Za-z_0-9]*$ -> returns the
  // full tag incl. both $, or null.
  const readDollarTag = (p: number): string | null => {
    if (sql[p] !== "$") return null;
    let q = p + 1;
    while (q < n && /[A-Za-z_0-9]/.test(sql[q])) q++;
    if (sql[q] === "$") return sql.slice(p, q + 1);
    return null;
  };

  while (i < n) {
    const c = sql[i];
    const c2 = sql[i + 1];

    if (inLine) {
      buf += c;
      if (c === "\n") inLine = false;
      i++;
      continue;
    }
    if (blockDepth > 0) {
      if (c === "/" && c2 === "*") { blockDepth++; buf += "/*"; i += 2; continue; }
      if (c === "*" && c2 === "/") { blockDepth--; buf += "*/"; i += 2; continue; }
      buf += c; i++;
      continue;
    }
    if (inSingle) {
      if (c === "'" && c2 === "'") { buf += "''"; i += 2; continue; } // escaped quote
      buf += c;
      if (c === "'") inSingle = false;
      i++;
      continue;
    }
    if (dollarTag !== null) {
      if (c === "$") {
        const tag = readDollarTag(i);
        if (tag === dollarTag) { buf += tag; i += tag.length; dollarTag = null; continue; }
      }
      buf += c; i++;
      continue;
    }

    // Not in any quoting/comment context.
    if (c === "-" && c2 === "-") { inLine = true; buf += "--"; i += 2; continue; }
    if (c === "/" && c2 === "*") { blockDepth++; buf += "/*"; i += 2; continue; }
    if (c === "'") { inSingle = true; buf += "'"; i++; continue; }
    if (c === "$") {
      const tag = readDollarTag(i);
      if (tag) { dollarTag = tag; buf += tag; i += tag.length; continue; }
    }
    if (c === ";") {
      buf += ";";
      const trimmed = buf.trim();
      if (trimmed) out.push(trimmed);
      buf = "";
      i++;
      continue;
    }
    buf += c;
    i++;
  }
  const tail = buf.trim();
  if (tail) out.push(tail);
  return out;
}

/** Strip leading line/block comments + whitespace to find the statement keyword. */
function stripLeadingNoise(stmt: string): string {
  let s = stmt;
  for (;;) {
    const before = s;
    s = s.replace(/^\s+/, "");
    s = s.replace(/^--[^\n]*\n/, "");
    s = s.replace(/^\/\*[\s\S]*?\*\//, "");
    if (s === before) break;
  }
  return s;
}

/**
 * Count top-level (paren-depth-1) arguments inside the first balanced (...)
 * group. Must ignore commas that live inside line/block comments, string
 * literals, or dollar-quoted DEFAULT expressions — a parameter-list comment like
 * `-- {asof, value_usd, breakdown}` would otherwise inflate the count and split
 * one function into phantom overloads (this exact bug hit
 * replace_allocator_equity_snapshots, whose real signature is 3 args).
 */
function countArgs(afterName: string): number {
  const open = afterName.indexOf("(");
  if (open === -1) return -1; // no parens -> treat as unknown
  let depth = 0;
  let count = 0;
  let sawAny = false;
  let inLine = false;
  let blockDepth = 0;
  let inSingle = false;
  let dollarTag: string | null = null;
  const n = afterName.length;
  const readDollarTag = (p: number): string | null => {
    if (afterName[p] !== "$") return null;
    let q = p + 1;
    while (q < n && /[A-Za-z_0-9]/.test(afterName[q])) q++;
    return afterName[q] === "$" ? afterName.slice(p, q + 1) : null;
  };
  for (let i = open; i < n; i++) {
    const ch = afterName[i];
    const c2 = afterName[i + 1];
    if (inLine) { if (ch === "\n") inLine = false; continue; }
    if (blockDepth > 0) {
      if (ch === "/" && c2 === "*") { blockDepth++; i++; }
      else if (ch === "*" && c2 === "/") { blockDepth--; i++; }
      continue;
    }
    if (inSingle) {
      if (ch === "'" && c2 === "'") { i++; continue; } // escaped quote
      if (ch === "'") inSingle = false;
      continue;
    }
    if (dollarTag !== null) {
      if (ch === "$") { const t = readDollarTag(i); if (t === dollarTag) { dollarTag = null; i += t.length - 1; } }
      continue;
    }
    // not in any comment/string context
    if (ch === "-" && c2 === "-") { inLine = true; i++; continue; }
    if (ch === "/" && c2 === "*") { blockDepth++; i++; continue; }
    if (ch === "'") { inSingle = true; continue; }
    if (ch === "$") { const t = readDollarTag(i); if (t) { dollarTag = t; i += t.length - 1; continue; } }
    if (ch === "(") depth++;
    else if (ch === ")") { depth--; if (depth === 0) break; }
    else if (ch === "," && depth === 1) count++;
    else if (depth === 1 && /\S/.test(ch)) sawAny = true;
  }
  if (!sawAny) return 0; // empty arg list ()
  return count + 1;
}

interface FnDef {
  name: string; // normalized (public. stripped)
  argCount: number;
  body: string; // verbatim CREATE statement
  source: string; // migration filename
}

const CREATE_RE = /^CREATE\s+(?:OR\s+REPLACE\s+)?FUNCTION\s+("[^"]+"|[A-Za-z_][\w.]*)\s*(\([\s\S]*)?$/i;
const DROP_RE = /^DROP\s+FUNCTION\s+(?:IF\s+EXISTS\s+)?("[^"]+"|[A-Za-z_][\w.]*)\s*(\([\s\S]*)?$/i;

function normalizeName(raw: string): string {
  let name = raw.replace(/"/g, "");
  if (name.startsWith("public.")) name = name.slice("public.".length);
  return name;
}

/** Replay every migration and return the live set of function definitions. */
export function buildSnapshot(migrationSqls: { file: string; sql: string }[]): Map<string, FnDef> {
  // key = `${name}/${argCount}`
  const live = new Map<string, FnDef>();
  for (const { file, sql } of migrationSqls) {
    for (const stmt of splitStatements(sql)) {
      const head = stripLeadingNoise(stmt);
      const cm = head.match(CREATE_RE);
      if (cm) {
        const name = normalizeName(cm[1]);
        const argCount = countArgs(cm[2] ?? "");
        live.set(`${name}/${argCount}`, { name, argCount, body: stmt, source: file });
        continue;
      }
      const dm = head.match(DROP_RE);
      if (dm) {
        const name = normalizeName(dm[1]);
        const argCount = countArgs(dm[2] ?? "");
        if (argCount >= 0) {
          live.delete(`${name}/${argCount}`);
        } else {
          // DROP without a signature: remove all overloads of that name.
          for (const k of [...live.keys()]) {
            if (live.get(k)!.name === name) live.delete(k);
          }
        }
      }
    }
  }
  return live;
}

/** Group live defs by function name; sort overloads by argCount. */
function emitFiles(live: Map<string, FnDef>): Map<string, string> {
  const byName = new Map<string, FnDef[]>();
  for (const def of live.values()) {
    const arr = byName.get(def.name) ?? [];
    arr.push(def);
    byName.set(def.name, arr);
  }
  const files = new Map<string, string>();
  for (const [name, defs] of byName) {
    defs.sort((a, b) => a.argCount - b.argCount);
    const fileName = name.replace(/[^A-Za-z0-9_.]/g, "_") + ".sql";
    const parts = defs.map((d) => `-- source migration: ${d.source}\n${d.body.trim()}\n`);
    files.set(fileName, HEADER + "\n" + parts.join("\n"));
  }
  return files;
}

function readMigrations(): { file: string; sql: string }[] {
  return readdirSync(MIGRATIONS_DIR)
    .filter((f) => f.endsWith(".sql"))
    .sort()
    .map((f) => ({ file: f, sql: readFileSync(join(MIGRATIONS_DIR, f), "utf8") }));
}

function generate(): Map<string, string> {
  return emitFiles(buildSnapshot(readMigrations()));
}

function writeSnapshot(files: Map<string, string>): void {
  rmSync(SNAPSHOT_DIR, { recursive: true, force: true });
  mkdirSync(SNAPSHOT_DIR, { recursive: true });
  for (const [name, content] of files) {
    writeFileSync(join(SNAPSHOT_DIR, name), content);
  }
}

function readCommitted(): Map<string, string> {
  const m = new Map<string, string>();
  if (!existsSync(SNAPSHOT_DIR)) return m;
  for (const f of readdirSync(SNAPSHOT_DIR)) {
    if (f.endsWith(".sql")) m.set(f, readFileSync(join(SNAPSHOT_DIR, f), "utf8"));
  }
  return m;
}

function check(): number {
  const want = generate();
  const have = readCommitted();
  const drift: string[] = [];
  for (const [name, content] of want) {
    if (!have.has(name)) drift.push(`  missing:  supabase/schema/functions/${name}`);
    else if (have.get(name) !== content) drift.push(`  stale:    supabase/schema/functions/${name}`);
  }
  for (const name of have.keys()) {
    if (!want.has(name)) drift.push(`  orphaned: supabase/schema/functions/${name}`);
  }
  if (drift.length) {
    console.error(
      `SQL function snapshot is stale (${drift.length} file(s)) — a migration changed a function\n` +
        `body but supabase/schema/functions/ wasn't regenerated:\n` +
        drift.sort().join("\n") +
        `\n\nRun \`npm run schema:functions\` and commit supabase/schema/functions/.`,
    );
    return 1;
  }
  console.log(`SQL function snapshot is current (${want.size} functions).`);
  return 0;
}

function selfTest(): number {
  // Synthetic migrations exercising: $$ body, named-tag body, nested $cron$ in a
  // DO block (must not confuse the splitter), an overload (same name, diff
  // argcount), a redefine (last wins), and a DROP+recreate (arg evolution).
  const m1 = {
    file: "001_a.sql",
    sql: `
      CREATE OR REPLACE FUNCTION foo(a int) RETURNS int LANGUAGE plpgsql AS $$
      BEGIN RETURN a; END; $$;
      DO $$ BEGIN PERFORM cron.schedule('x', $cron$ SELECT 1; $cron$); END $$;
      CREATE OR REPLACE FUNCTION bar() RETURNS void LANGUAGE sql AS $func$ SELECT 1; $func$;
    `,
  };
  const m2 = {
    file: "002_b.sql",
    sql: `
      -- redefine foo(int): new body must win
      CREATE OR REPLACE FUNCTION foo(a int) RETURNS int LANGUAGE plpgsql AS $$
      BEGIN RETURN a + 1; END; $$;
      -- overload foo with 2 args
      CREATE OR REPLACE FUNCTION foo(a int, b int) RETURNS int LANGUAGE sql AS $$ SELECT a + b; $$;
    `,
  };
  const m3 = {
    file: "003_c.sql",
    sql: `
      DROP FUNCTION IF EXISTS foo(int, int);
      CREATE FUNCTION baz(x text DEFAULT '), not a paren') RETURNS text LANGUAGE sql AS $$ SELECT x; $$;
    `,
  };
  // Comment/string commas in the signature must NOT inflate the arg count
  // (the replace_allocator_equity_snapshots bug: a `-- {a, b, c}` param comment
  // split one 3-arg function into phantom /6 and /7 overloads).
  const m4 = {
    file: "004_d.sql",
    sql: `
      CREATE OR REPLACE FUNCTION qux(
        p_id uuid,
        p_rows jsonb, -- array of {asof, value_usd, breakdown, source}
        p_limit int /* inline, block, comment */ DEFAULT 10
      ) RETURNS void LANGUAGE sql AS $$ SELECT 1; $$;
      CREATE OR REPLACE FUNCTION quux(a text DEFAULT 'x,y,z') RETURNS text LANGUAGE sql AS $$ SELECT a; $$;
    `,
  };
  const live = buildSnapshot([m1, m2, m3, m4]);
  const get = (name: string, n: number) => live.get(`${name}/${n}`);
  const assert = (cond: boolean, msg: string) => {
    if (!cond) { console.error(`SELF-TEST FAIL: ${msg}`); process.exit(1); }
  };
  assert(get("foo", 1) !== undefined, "foo(1 arg) should be live");
  assert(get("foo", 1)!.body.includes("a + 1"), "foo(int) latest body should win");
  assert(get("foo", 1)!.source === "002_b.sql", "foo(int) source should be the redefining migration");
  assert(get("foo", 2) === undefined, "foo(int,int) overload was DROPped -> should be gone");
  assert(get("bar", 0) !== undefined, "bar() (named-tag body) should be live");
  assert(get("baz", 1) !== undefined, "baz(text) (CREATE FUNCTION, paren-in-default) should be live");
  assert(get("baz", 1)!.argCount === 1, "baz default with a ')' literal must still count 1 arg");
  // The DO block + nested $cron$ must not have leaked into any function body.
  assert(![...live.values()].some((d) => d.body.includes("cron.schedule")), "DO block must not be captured as a function");
  // Comment/string commas must not inflate the arg count.
  assert(get("qux", 3) !== undefined, "qux must be 3 args (comment/block commas ignored), not 6+");
  assert([...live.keys()].filter((k) => k.startsWith("qux/")).length === 1, "qux must be a SINGLE def, not phantom overloads");
  assert(get("quux", 1) !== undefined, "quux must be 1 arg (comma inside string literal ignored)");
  console.log("SELF-TEST PASS: 11 assertions.");
  return 0;
}

const arg = process.argv[2];
if (arg === "--check") process.exit(check());
else if (arg === "--self-test") process.exit(selfTest());
else {
  const files = generate();
  writeSnapshot(files);
  console.log(`Wrote ${files.size} function snapshot file(s) to supabase/schema/functions/.`);
}
