"""Phase 5 D-21 cross-runtime parity test (Voice-D2 option a).

Asserts that Phase 4 `feedback_engine._success_value` produces per-row
success values and most-mature deltas that match the TypeScript side's
`tests/fixtures/outcomes-kpi-parity.json` expected payload. Running this
test gated on HAS_PY_ENV=1 prevents drift between Phase 4 (Python) and
Phase 5 (TypeScript) — any change to Phase 4 filter rules must update
BOTH the fixture AND this test in the same PR.
"""
import json
import os
import pathlib

import pytest

pytestmark = pytest.mark.skipif(
    os.environ.get("HAS_PY_ENV") != "1",
    reason="Python parity test gated on HAS_PY_ENV=1 (Phase 5 D-21 / Voice-D2 option a)",
)


REPO_ROOT = pathlib.Path(__file__).resolve().parents[2]
FIXTURE_PATH = REPO_ROOT / "tests" / "fixtures" / "outcomes-kpi-parity.json"


@pytest.fixture(scope="module")
def fixture() -> dict:
    return json.loads(FIXTURE_PATH.read_text())


def test_fixture_path_resolves(fixture: dict) -> None:
    """The TS-side fixture must be readable from the Python tree."""
    assert "outcomes" in fixture
    assert "expected" in fixture
    assert "phase4_success_values" in fixture


def test_success_value_matches_per_row(fixture: dict) -> None:
    """feedback_engine._success_value returns 1 iff most-mature non-NULL delta > 0.

    The fixture's `phase4_success_values` map is the authoritative source
    of expected per-row success values. Any drift here means Phase 5
    dashboard math + Phase 4 scoring engine have diverged.
    """
    from services.feedback_engine import _success_value

    expected = fixture["phase4_success_values"]
    for outcome in fixture["outcomes"]:
        oid = outcome["id"]
        if oid not in expected:
            # Outcome didn't survive Phase 4 filters (e.g. rejected-already_owned
            # or allocated-pending-only) — not asserted here; see
            # test_mature_survivors for filter-level parity.
            continue
        assert _success_value(outcome) == expected[oid], (
            f"Row {oid}: _success_value disagrees with TS expected "
            f"({_success_value(outcome)} vs {expected[oid]})"
        )


def test_mature_survivors_match(fixture: dict) -> None:
    """Rows that SHOULD pass D-08 + D-03 filters for Phase 4 must match
    the TS-side `phase4_mature_survivors` list.
    """
    expected_survivors = set(fixture["phase4_mature_survivors"])
    actual_survivors: set[str] = set()
    for outcome in fixture["outcomes"]:
        kind = outcome["kind"]
        if kind == "rejected":
            if outcome["rejection_reason"] == "already_owned":
                continue
            actual_survivors.add(outcome["id"])
        elif kind == "allocated":
            if (outcome["percent_allocated"] or 0) < 1.0:
                continue
            has_delta = any(
                outcome.get(k) is not None
                for k in ("delta_30d", "delta_90d", "delta_180d")
            )
            if not has_delta:
                continue
            actual_survivors.add(outcome["id"])
    # NOTE: phase4_mature_survivors in the fixture lists ONLY allocated
    # survivors (the TS KPI denominator); rejected-non-already_owned
    # survive Phase 4 for attribution but are out of KPI denominator scope.
    # Restrict the actual set to allocated kind for parity.
    actual_allocated_survivors = {
        outcome["id"]
        for outcome in fixture["outcomes"]
        if outcome["id"] in actual_survivors and outcome["kind"] == "allocated"
    }
    assert actual_allocated_survivors == expected_survivors


# ---------------------------------------------------------------------------
# H-0798 — independent oracle for _success_value.
#
# test_success_value_matches_per_row above compares Python _success_value to
# fixture["phase4_success_values"]. If that fixture was generated by running
# Python _success_value (or by mirroring the TS impl 1:1), the comparison only
# proves both sides encode the SAME logic — including the SAME bug. There is no
# independent truth.
#
# This test pins the D-01 + D-02 + D-04 rule by HAND for each fixture outcome,
# derived from the spec — NOT read from the fixture's expected map. The rule:
#   * rejected → 0 (D-04: rejected counts as failure)
#   * else: take the MOST-MATURE non-NULL delta (180d > 90d > 30d priority);
#     success = 1 iff that delta > 0, else 0
#   * no non-NULL delta → 0
#
# Hand-derivation against the 7 fixture rows (verified by inspecting the fixture
# values, see the comment per row). If a future fixture regen silently changes
# these inputs, the test's hardcoded expectations + the per-row spec re-derivation
# will diverge from _success_value and fail — catching a symmetric-bug regen that
# the fixture-vs-impl test would rubber-stamp.
# ---------------------------------------------------------------------------


# Hand-derived from the D-01/D-02/D-04 spec, NOT copied from the fixture's
# phase4_success_values map. Each value is the independently-reasoned oracle.
_HAND_DERIVED_SUCCESS: dict[str, int] = {
    # allocated, deltas (30d=0.04, 90d=None, 180d=None); most-mature non-NULL
    # is 30d=0.04 > 0 → success.
    "o1": 1,
    # allocated, deltas (30d=0.05, others None); 30d=0.05 > 0 → success.
    # (o2 does not survive D-08 percent>=1 so it's absent from the KPI map,
    # but _success_value itself is precondition-free and still returns 1.)
    "o2": 1,
    # allocated, all deltas None → no signal → 0.
    "o3": 0,
    # rejected (already_owned) → D-04 failure → 0.
    "o4": 0,
    # rejected (mandate_conflict) → D-04 failure → 0.
    "o5": 0,
    # allocated, deltas (30d=None, 90d=0.12, 180d=None); most-mature non-NULL
    # is 90d=0.12 > 0 → success.
    "o6": 1,
    # allocated, deltas (30d=-0.03, 90d=-0.08, 180d=-0.15); most-mature non-NULL
    # is 180d=-0.15, which is NOT > 0 → failure.
    "o7": 0,
}


def test_success_value_matches_independent_oracle(fixture: dict) -> None:
    """_success_value must match a HAND-DERIVED expectation, not the fixture's
    own expected map. This is the independent oracle the cross-runtime parity
    test lacks (H-0798): it cannot be satisfied by a fixture+impl that share a
    bug, because the expectation is reasoned from the spec by hand here."""
    from services.feedback_engine import _success_value

    outcomes_by_id = {o["id"]: o for o in fixture["outcomes"]}
    # The hand-derived map must cover EVERY fixture row — guards against a regen
    # that adds rows we never reasoned about.
    assert set(_HAND_DERIVED_SUCCESS) == set(outcomes_by_id), (
        "fixture outcomes drifted from the hand-derived oracle; re-derive "
        "_HAND_DERIVED_SUCCESS from the D-01/D-02/D-04 spec for the new rows"
    )

    for oid, expected in _HAND_DERIVED_SUCCESS.items():
        actual = _success_value(outcomes_by_id[oid])
        assert actual == expected, (
            f"Row {oid}: _success_value={actual} disagrees with the "
            f"hand-derived spec oracle ({expected}). Either production "
            f"_success_value regressed, or the fixture inputs changed."
        )


def test_independent_oracle_agrees_with_fixture_for_kpi_rows(fixture: dict) -> None:
    """Cross-check: where the fixture DOES carry an expected success value, the
    hand-derived oracle must agree with it. A mismatch here means the fixture's
    expected map encodes a value the spec does not support — i.e. the fixture
    itself is wrong, the exact 'fixture is the sole oracle' failure mode."""
    fixture_expected = fixture["phase4_success_values"]
    for oid, fixture_val in fixture_expected.items():
        assert _HAND_DERIVED_SUCCESS[oid] == fixture_val, (
            f"Row {oid}: fixture expected {fixture_val} but the independent "
            f"spec oracle says {_HAND_DERIVED_SUCCESS[oid]} — the committed "
            f"fixture disagrees with the D-01/D-02/D-04 rule."
        )
