-- Migration: service_role gets an EXPLICIT statement_timeout strictly below the
-- API gateway's 60s ceiling, so a slow service-role read is answered by a
-- catchable Postgres timeout instead of an opaque gateway 504.
-- Phase 164.5.1 / plan 03 / ROADMAP criterion 7 ([164.5.1-GATEWAY-CEILING-INVERSION]).
-- 2026-09-16.
--
-- ⚠️ OPS: merging supabase/migrations/** to main auto-applies to shared TEST
-- FIRST (supabase-migrate.yml's `apply-test` job, holding advisory key
-- 61616158, database-marker query run first) and only then to PROD, behind the
-- `Production` environment's human reviewer gate (needs apply-test success).
-- NO LOCAL PUSH IS PERFORMED FROM THIS CHECKOUT: this checkout's Supabase CLI
-- is linked to PRODUCTION (supabase/.temp/project-ref matches the ref
-- src/lib/test-safety.ts pins), so `supabase db push` / `db reset --linked` /
-- `--project-ref` / `--db-url` all write to PROD from here and are never run
-- for this file. The apply path is exclusively merge -> apply-test -> the
-- human-reviewed PROD `apply` job.
--
-- ⛔ IT IS A FORWARD MIGRATION AND NOT AN EDIT TO AN APPLIED ONE. No existing
-- migration is touched by this file.
--
-- ══════════════════════════════════════════════════════════════════════════
-- THIS MIGRATION REGISTERS NO SCHEDULE AND REMOVES NONE
-- ══════════════════════════════════════════════════════════════════════════
-- It contains zero occurrences, comments included, of a schedule-registration
-- verb or its inverse (the pg_cron catalogue-mutating verbs) — deliberately
-- described here rather than spelled out, so that this file's own prose can
-- never trip Task 2's raw-text no-schedule gate. `20260907120000` states the
-- rule this file also honours: "It REGISTERS NO SCHEDULE and REMOVES NONE...
-- A migration that schedules is a scope violation." D1 (D-01) keeps the live
-- `cron.job` jobid 1 repoint a RUNBOOK operation, never a migration. D2's
-- (D-02) "no forward migration is written by this phase" sentence is SCOPED to
-- scheduling/unscheduling (ROADMAP note, 2026-09-16) — an `ALTER ROLE ... SET
-- statement_timeout` does neither, so this file does not contradict D1 or D2,
-- and no reviewer should read the two as a conflict to be averaged.
-- ══════════════════════════════════════════════════════════════════════════
--
-- ⛔ THIS CHANGES NOTHING ABOUT SPEED. It must never be described, committed,
-- or reported as a performance improvement — it converts an unclassifiable
-- gateway 504 into a named, catchable Postgres error so the service can fail
-- loudly and specifically. The margin between 45s and the measured 44.67s
-- successful run is what criterion 9's request batching (plan 03, Area 2)
-- removes; this migration does not touch request duration itself.
--
-- ROLLBACK / FAILURE NOTE: if the apply returns 42501, the platform refuses
-- this statement for this role and criterion 7 needs a different mechanism —
-- record the error verbatim in the plan 09 runbook session and STOP; do not
-- reach for a console `ALTER ROLE` as a workaround, that is the exact
-- untraceable-change class CRON-DRIFT-01 exists because of. If the apply
-- succeeds and must later be undone, the undo is a NEW forward migration
-- running `ALTER ROLE service_role RESET statement_timeout;` — never a
-- console statement, never an edit to this file.
--
-- ══════════════════════════════════════════════════════════════════════════
-- TWO CARRY-FORWARD CORRECTIONS, recorded in prose, editing neither file
-- ══════════════════════════════════════════════════════════════════════════
-- ⛔ Neither correction below spells the acknowledgment-pragma token or the
-- custom-GUC lineage-header token literally, for the SAME hygiene reason the
-- schedule-registration verb is never spelled above: Task 2's static gate
-- scans this file's RAW text for both tokens, and a gate is the only place
-- in this phase's tree meant to spell them — this file's own prose must
-- never satisfy or trip it.
--
-- (a) [164.7-MIGRATION-COMMENT-DRIFT]: `20260907130000_ledger_refresh_switch_
--     to_system_flags.sql` carries two FILLED PROD-body acknowledgment
--     comment lines (the machine-read pragma scripts/prod-body-drift-check.sh
--     greps for) at its own lines 10-11, while a LATER region in the same
--     file (its "VAC-04 ACKNOWLEDGEMENT — to be EARNED on the PR (plan 06)"
--     block, around lines 119-152) describes that acknowledgment line as
--     "DELIBERATELY ABSENT from this file today" with unfilled
--     `<measured in plan 06>` placeholders. Measured comment-only, no live
--     gate risk today — the acknowledgment line at lines 10-11 is what the
--     drift-check script actually greps for — but the file tells a human
--     reader the opposite of what the gate reads. The file is NOT edited
--     here; this is the pointer the ROADMAP's carry-forward asks this
--     migration's header to carry.
--
-- (b) The superseded PROD-body acknowledgment comment lines. MEASURED
--     2026-09-16 by counting that acknowledgment pragma per file (never
--     transcribed from prose — the ROADMAP says "three" and then names four
--     files):
--       20260906120000_computation_error_provenance.sql          1
--       20260907130000_ledger_refresh_switch_to_system_flags.sql 2
--       20260911120000_vault_tick_hardening.sql                  1
--       20260911130000_ledger_fanout_grantees_and_dormancy.sql   2
--       TOTAL                                                    6
--     These are inert TWICE OVER, not merely stale: (1)
--     scripts/prod-body-drift-check.sh reads that acknowledgment comment
--     ONLY inside its function-body-drift branch, and the bodies each line
--     acknowledges now MATCH the snapshot the drift check compares against,
--     so that branch does not fire for them; and (2) the script greps for
--     the acknowledgment comment only within the files touched by the
--     current PR's diff — an already-merged, untouched migration file is
--     never scanned at all, acknowledged or not.
--
-- ⛔ This migration carries NO PROD-body acknowledgment line of its own: it
-- defines no function body, so there is nothing for the drift check to
-- compare against a PROD snapshot. ⛔ It carries NO custom-GUC lineage
-- header either: `statement_timeout` is a BUILT-IN Postgres GUC, not an
-- `app.*` custom placeholder GUC, so scripts/lint-app-guc.mjs's allowlist
-- mechanism (which covers `app.*` GUCs only) does not apply here. ⛔ This
-- migration carries NO forward pointer to the cron-lineage files
-- (`20260408215026`, `20260408113029`, `20260907120000`,
-- `scripts/lint-app-guc.mjs`, `docs/runbooks/match-engine.md`, `TODOS.md`) —
-- criterion 6's amendment (b), recorded 2026-09-16: an `ALTER ROLE`
-- statement-timeout migration has no lineage relationship to the cron
-- repoint, so a pointer here would be misfiled.
--
-- No successful `ALTER ROLE`/`ALTER DATABASE` precedent exists anywhere in
-- this repo's migration history to copy the statement shape from — every
-- prior grep hit for either verb (`20260407164606`, `20260408113029`,
-- `20260408215026`) sits inside a COMMENT and targets an `app.*` custom GUC,
-- the class that returns 42501 on this platform (superuser-only, regardless
-- of hosting). `statement_timeout` is a BUILT-IN GUC with no such
-- restriction per Supabase's documentation; this statement is written
-- directly from that documented form.

ALTER ROLE service_role SET statement_timeout = '45s';
